force-app-modified/main/default/objects/charters__c/charters__c.object-meta.xml
<CustomObject>
    <label>צ&apos;רטר</label>
    <nameField>
        <displayFormat>CH-{0000}</displayFormat>
        <label>מספר הפלגה</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>צ&apos;רטרים</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Diary__c/Diary__c.object-meta.xml
<CustomObject>
    <label>Diary</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Diary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Diaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app-modified/main/default/objects/Diary__c/fields/CharterId__c.field-meta.xml
<CustomField>
    <fullName>CharterId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Charter</label>
    <referenceTo>charters__c</referenceTo>
    <relationshipLabel>Diaries</relationshipLabel>
    <relationshipName>Diaries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app-modified/main/default/objects/Shared_Documents__c/Shared_Documents__c.object-meta.xml
<CustomObject>
    <label>Shared Documents</label>
    <nameField>
        <label>Shared Documents Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shared Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Shared_Documents__c/fields/Charter__c.field-meta.xml
<CustomField>
    <fullName>Charter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Charter</label>
    <referenceTo>charters__c</referenceTo>
    <relationshipLabel>Shared Documents</relationshipLabel>
    <relationshipName>Shared_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app-modified/main/default/classes/CreateDiarySharedDocOnCharterInsert_Apex.cls
/*
*  Author        :   Sameer Pandey
*  Created on    :   14th Sep 2021
*  Description   :   Trigger handler class to automatically generating the pulink link url of uploaded document
*                    we can then use that link to view and download the document on comunity and public site.
*/

public class CreateDiarySharedDocOnCharterInsert_Apex {
    public static void insertChildRecord(List<charters__c> charterList){
        List<Diary__c> diaryList = new List<Diary__c>();
        List<Shared_Documents__c> sharedDocList = new List<Shared_Documents__c>();
        for(charters__c charter :charterList){
            Diary__c diary = new Diary__c();
            diary.CharterId__c = charter.Id ;
            diaryList.add(diary);
            
            Shared_Documents__c sharedDoc = new Shared_Documents__c();
            sharedDoc.Charter__c = charter.Id ;
            sharedDoc.Name = 'Shared '+ charter.Name ;
            sharedDocList.add(sharedDoc);
        }
        insert diaryList ;
        insert sharedDocList ;
    }
}