force-app-modified/main/default/objects/charters__c/charters__c.object-meta.xml
<CustomObject>
    <label>צ&apos;רטר</label>
    <nameField>
        <displayFormat>CH-{0000}</displayFormat>
        <label>מספר הפלגה</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>צ&apos;רטרים</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app-modified/main/default/objects/charters__c/fields/cabins__c.field-meta.xml
<CustomField>
    <fullName>cabins__c</fullName>
    <label>קבינות</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/charters__c/fields/charter_booking_date__c.field-meta.xml
<CustomField>
    <fullName>charter_booking_date__c</fullName>
    <label>תאריך סגירה</label>
    <type>Date</type>
</CustomField>

force-app-modified/main/default/objects/charters__c/fields/client__c.field-meta.xml
<CustomField>
    <fullName>client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>לקוח</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>צ&apos;רטרים</relationshipLabel>
    <relationshipName>charterclient</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/charters__c/fields/WC__c.field-meta.xml
<CustomField>
    <fullName>WC__c</fullName>
    <label>שירותים/מקלחות</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app-modified/main/default/objects/charters__c/fields/yacht_model__c.field-meta.xml
<CustomField>
    <fullName>yacht_model__c</fullName>
    <label>דגם יאכטה</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Beneteau</fullName>
            </value>
            <value>
                <fullName>Jeanneau</fullName>
            </value>
            <value>
                <fullName>Bavaria</fullName>
            </value>
            <value>
                <fullName>Dufour</fullName>
            </value>
            <value>
                <fullName>Hanse</fullName>
            </value>
            <value>
                <fullName>Lagoon</fullName>
            </value>
            <value>
                <fullName>Bali</fullName>
            </value>
            <value>
                <fullName>Fountaine-Pajot</fullName>
            </value>
            <value>
                <fullName>Moorings (Leopard)</fullName>
            </value>
            <value>
                <fullName>-Moorings (Lagoon)</fullName>
            </value>
            <value>
                <fullName>-Sunsail (Leopard)</fullName>
            </value>
            <value>
                <fullName>-Sunsail (Lagoon)</fullName>
            </value>
            <value>
                <fullName>Nautitech</fullName>
            </value>
            <value>
                <fullName>Elan</fullName>
            </value>
            <value>
                <fullName>Excess</fullName>
            </value>
            <value>
                <fullName>Sunsail</fullName>
            </value>
            <value>
                <fullName>Moorings</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/charters__c/fields/yacht_type__c.field-meta.xml
<CustomField>
    <fullName>yacht_type__c</fullName>
    <label>סוג יאכטה</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>מונו</fullName>
            </value>
            <value>
                <fullName>קטמרן</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Diary__c/Diary__c.object-meta.xml
<CustomObject>
    <label>Diary</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Diary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Diaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app-modified/main/default/objects/Diary__c/fields/CharterId__c.field-meta.xml
<CustomField>
    <fullName>CharterId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Charter</label>
    <referenceTo>charters__c</referenceTo>
    <relationshipLabel>Diaries</relationshipLabel>
    <relationshipName>Diaries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app-modified/main/default/objects/Shared_Documents__c/Shared_Documents__c.object-meta.xml
<CustomObject>
    <label>Shared Documents</label>
    <nameField>
        <label>Shared Documents Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shared Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Shared_Documents__c/fields/Charter__c.field-meta.xml
<CustomField>
    <fullName>Charter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Charter</label>
    <referenceTo>charters__c</referenceTo>
    <relationshipLabel>Shared Documents</relationshipLabel>
    <relationshipName>Shared_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app-modified/main/default/classes/SitePageChartersTab_ApexControllerTest.cls
@isTest
public class SitePageChartersTab_ApexControllerTest {
    
    @isTest
    public static void stePageChartersTabApexControllertestAllMethods(){
        Test.startTest();
        try{
            Account acc = new Account(Name = 'test account');
            insert acc;
            
            Charters__c chart = new Charters__c();
            chart.client__c = acc.id;
            chart.yacht_type__c = 'מונו';
            chart.yacht_model__c = 'Benetaeu'; 
            chart.cabins__c = 3;
            chart.WC__c = 2;
            chart.charter_booking_date__c = date.today();
            insert chart;
       
            List<charters__c> chartersList = SitePageChartersTab_ApexController.getAllChartersRecords(acc.id);
            System.assertEquals(acc.id,chartersList[0].client__c);
            
            Diary__c dary = new Diary__c();
            dary.CharterId__c = chart.id;
            //insert dary;
             
            Map<charters__c,List<ContentDocument>> charterIdVSListOfContentDocumentObj = SitePageChartersTab_ApexController.getAllChartersVsDocumentRecords(acc.id);
            List<charters__c> chatList = new List<charters__c>();
			chatList.addAll(charterIdVSListOfContentDocumentObj.keySet());                                                                                                                                                                                                                                                                                                                                                                                                                             
            System.assertEquals(chart.id ,chatList[0].id);
            
            
            ContentVersion cv = new ContentVersion();
            cv.Title = 'test';
            cv.PathOnClient = 'TestDocument.pdf';
            cv.VersionData = Blob.valueOf('Test document');
            cv.IsMajorVersion = true;
            Insert cv;
            
            //Get Content Documents
            Id conDocId = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =:cv.Id].ContentDocumentId;
            
            Shared_Documents__c sharDoc = new Shared_Documents__c();
            sharDoc.Charter__c = chart.id;
            insert sharDoc;
            
            //Create ContentDocumentLink 
            ContentDocumentLink cdl = New ContentDocumentLink();
            cdl.LinkedEntityId = sharDoc.Id;
            cdl.ContentDocumentId = conDocId;
            cdl.shareType = 'V';
            Insert cdl;
              
            List<ContentDocument> contList =  SitePageChartersTab_ApexController.getAllContentDocumentsSharedDocument(chart.id);
            System.assertEquals(conDocId, contList[0].id);
           
            
            Id sitePageChartersTabId = SitePageChartersTab_ApexController.saveChunk(chart.id, 'test', 'This is version data', 'pdf', '');
        	System.assert(sitePageChartersTabId != null);
           
            Id sitePageChar = SitePageChartersTab_ApexController.saveChunkCharter(chart.id, 'test', 'This is version data', 'pdf', '', 'press1');
            System.assert(sitePageChar != null);
            
            String conDiscription =  SitePageChartersTab_ApexController.getPublicLinkURLForSelectedFile(conDocId);
            ContentDistribution conDist = [Select id, DistributionPublicUrl From ContentDistribution where ContentDocumentId =: conDocId LIMIT 1];
            System.assertEquals(conDist.DistributionPublicUrl,conDiscription);
            
        }
        catch(Exception ex){
            System.debug('Exception '+ex.getMessage());
        }
        Test.stopTest();
    }   
}