force-app-modified/main/default/objects/charters__c/charters__c.object-meta.xml
<CustomObject>
    <label>צ&apos;רטר</label>
    <nameField>
        <displayFormat>CH-{0000}</displayFormat>
        <label>מספר הפלגה</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>צ&apos;רטרים</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app-modified/main/default/objects/charters__c/fields/Agent__c.field-meta.xml
<CustomField>
    <fullName>Agent__c</fullName>
    <label>גורם מטפל</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>תום</fullName>
            </value>
            <value>
                <fullName>רפי</fullName>
            </value>
            <value>
                <fullName>יונתן</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app-modified/main/default/objects/charters__c/fields/cabins__c.field-meta.xml
<CustomField>
    <fullName>cabins__c</fullName>
    <label>קבינות</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app-modified/main/default/objects/charters__c/fields/charter_date__c.field-meta.xml
<CustomField>
    <fullName>charter_date__c</fullName>
    <label>תאריך ההפלגה</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/charters__c/fields/WC__c.field-meta.xml
<CustomField>
    <fullName>WC__c</fullName>
    <label>שירותים/מקלחות</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app-modified/main/default/objects/charters__c/fields/yacht_length__c.field-meta.xml
<CustomField>
    <fullName>yacht_length__c</fullName>
    <label>אורך יאכטה (רגל)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app-modified/main/default/objects/charters__c/fields/yacht_model__c.field-meta.xml
<CustomField>
    <fullName>yacht_model__c</fullName>
    <label>דגם יאכטה</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Beneteau</fullName>
            </value>
            <value>
                <fullName>Jeanneau</fullName>
            </value>
            <value>
                <fullName>Bavaria</fullName>
            </value>
            <value>
                <fullName>Dufour</fullName>
            </value>
            <value>
                <fullName>Hanse</fullName>
            </value>
            <value>
                <fullName>Lagoon</fullName>
            </value>
            <value>
                <fullName>Bali</fullName>
            </value>
            <value>
                <fullName>Fountaine-Pajot</fullName>
            </value>
            <value>
                <fullName>Moorings (Leopard)</fullName>
            </value>
            <value>
                <fullName>-Moorings (Lagoon)</fullName>
            </value>
            <value>
                <fullName>-Sunsail (Leopard)</fullName>
            </value>
            <value>
                <fullName>-Sunsail (Lagoon)</fullName>
            </value>
            <value>
                <fullName>Nautitech</fullName>
            </value>
            <value>
                <fullName>Elan</fullName>
            </value>
            <value>
                <fullName>Excess</fullName>
            </value>
            <value>
                <fullName>Sunsail</fullName>
            </value>
            <value>
                <fullName>Moorings</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/charters__c/fields/yacht_type__c.field-meta.xml
<CustomField>
    <fullName>yacht_type__c</fullName>
    <label>סוג יאכטה</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>מונו</fullName>
            </value>
            <value>
                <fullName>קטמרן</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CreateDiarySharedDocOnCharterInsert_Test.cls
@isTest
public class CreateDiarySharedDocOnCharterInsert_Test {
    @isTest
    public static void CreateDiarySharedDocOnCharterInsertTestMethod(){
        charters__c charter = new charters__c();
        charter.charter_date__c = date.today();
        charter.yacht_type__c = 'מונו';
        charter.yacht_model__c = 'Beneteau';
        charter.yacht_length__c = 6;
        charter.cabins__c = 3;
        charter.WC__c = 6;
        charter.Agent__c = 'תום';
        insert charter;
    }
}