force-app-modified/main/default/objects/Boats__c/Boats__c.object-meta.xml
<CustomObject>
    <label>סירה</label>
    <nameField>
        <label>שם סירה</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>סירות</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app-modified/main/default/objects/Boats__c/fields/Convertion__c.field-meta.xml
<CustomField>
    <fullName>Convertion__c</fullName>
    <formula>0</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>יחס המרה</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Boats__c/fields/Docking__c.field-meta.xml
<CustomField>
    <fullName>Docking__c</fullName>
    <label>מרינה</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Wharf</fullName>
                <label>רציף</label>
            </value>
            <value>
                <fullName>Marina</fullName>
                <label>מרינה</label>
            </value>
            <value>
                <fullName>Herz</fullName>
                <label>הרצליה</label>
            </value>
            <value>
                <fullName>תל אביב</fullName>
            </value>
            <value>
                <fullName>חיפה</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app-modified/main/default/classes/SchemaUtilityServiceTest.cls
@isTest
public with sharing class SchemaUtilityServiceTest {
     public static testMethod void getLabelOfFieldTest(){
       SchemaUtilityService schList = new SchemaUtilityService();
       String [] labelArr = new List<String>{'רציף','מרינה','הרצליה', 'תל אביב','חיפה'};
       integer i=0;
     	map <String, String> MapTest =  SchemaUtilityService.getFieldLabelMap('Boats__c','Convertion__c');
		system.assertEquals(MapTest.get('Convertion__c'),'יחס המרה');
		test.startTest();
        	map <String, String> MapTestPickList =  SchemaUtilityService.getFieldLabelMap('Boats__c','Docking__c');
        test.stopTest();
        for (String apiItem: MapTestPickList.keyset()){
            system.debug('MapTestPickList.get(apiItem)= '+ MapTestPickList.get(apiItem));
            system.assertEquals(MapTestPickList.get(apiItem),labelArr[i]);
            i++;
        }
     }
     
}