force-app-modified/main/default/objects/Boats__c/Boats__c.object-meta.xml
<CustomObject>
    <label>סירה</label>
    <nameField>
        <label>שם סירה</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>סירות</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app-modified/main/default/objects/Boats__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>סוג סירה</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Boat_Type</valueSetName>
    </valueSet>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/Cruise__c.object-meta.xml
<CustomObject>
    <label>הפלגה</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>מספר הפלגה</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>הפלגות</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app-modified/main/default/objects/Cruise__c/fields/AccountName__c.field-meta.xml
<CustomField>
    <fullName>AccountName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>שם לקוח</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>הפלגות</relationshipLabel>
    <relationshipName>Cruises</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cruise__c/fields/Boat__c.field-meta.xml
<CustomField>
    <fullName>Boat__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>סירה</label>
    <referenceTo>Boats__c</referenceTo>
    <relationshipLabel>הפלגות</relationshipLabel>
    <relationshipName>Boat</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cruise__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>תאריך סיום</label>
    <type>DateTime</type>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/fields/Payment_Required__c.field-meta.xml
<CustomField>
    <fullName>Payment_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>דרוש תשלום</label>
    <type>Checkbox</type>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>תאריך התחלה</label>
    <type>DateTime</type>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <label>עסקאות</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>הפלגות</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Cruise__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>סוג הסירה</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>מפרשית</fullName>
            </value>
            <value>
                <fullName>יאכטה</fullName>
            </value>
            <value>
                <fullName>קטמרן</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/recordTypes/Club.recordType-meta.xml
<RecordType>
    <fullName>Club</fullName>
    <active>true</active>
    <label>Club</label>
</RecordType>

force-app-modified/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>עסקה</label>
    <nameField>
        <label>שם עסקה</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>עסקאות</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>שם לקוח</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>עסקאות</relationshipLabel>
    <relationshipName>Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Date_of_Transaction__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Transaction__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>תאריך העסקה</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <defaultValue>today()+365</defaultValue>
    <label>תאריך סיום</label>
    <type>Date</type>
</CustomField>

force-app-modified/main/default/objects/Transaction__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <defaultValue>today()</defaultValue>
    <label>תאריך התחלה</label>
    <type>Date</type>
</CustomField>

force-app-modified/main/default/objects/Transaction__c/fields/Transaction_Number__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Number__c</fullName>
    <displayFormat>D-{00000}</displayFormat>
    <label>מספר עסקה</label>
    <type>AutoNumber</type>
</CustomField>

force-app-modified/main/default/objects/Transaction__c/fields/type_of_membership__c.field-meta.xml
<CustomField>
    <fullName>type_of_membership__c</fullName>
    <label>סוג מנוי</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>חבר מועדון כולל פרטיות</fullName>
            </value>
            <value>
                <fullName>מודרכות בלבד</fullName>
            </value>
            <value>
                <fullName>תלמיד</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/recordTypes/RecordType.recordType-meta.xml
<RecordType>
    <fullName>RecordType</fullName>
    <active>false</active>
    <label>מוצרים אחרים</label>
</RecordType>

force-app-modified/main/default/classes/CreateCruise.cls
public class CreateCruise {
    private Map<String, String> param = ApexPages.currentPage().getParameters();

    public Boolean isClassic { set; get; }
    public String createParam { set; get; }
    public String rts { set; get; }
    public Cruise__c cruise  { set; get; }
    public String retURL { set; get; }

    public CreateCruise() {
        createParam = 'null';
        rts = JSON.serialize([SELECT Id, Description FROM RecordType WHERE SObjectType='Cruise__c']);
        cruise = new Cruise__c(RecordTypeId=[SELECT Id FROM RecordType WHERE SObjectType='Cruise__c' AND Name='Club' LIMIT 1].Id);
        retURL = param.get('retURL') != null ? param.get('retURL') : '/a04/o';
    }

    public PageReference save() {
        createParam = 'null';
        RecordType rt = [SELECT Id, Name FROM RecordType WHERE Id=:cruise.RecordTypeId LIMIT 1];
        Account account;
        if (rt.Name == 'Club')
            if (cruise.AccountName__c != null) account = [SELECT Id, Name FROM Account WHERE Id=:cruise.AccountName__c LIMIT 1];
            else return null;
        Boats__c boat = [SELECT Id, Name, Type__c FROM Boats__c WHERE Id=:param.get('boatId') LIMIT 1];
        String start = param.get('start');
        String endd = param.get('end');
        String payment = '0';
        Transaction__c trans;
        if (rt.Name == 'Club')
            try {
                trans = [select Id, Date_of_Transaction__c, Name, Type__c, Account_Name__c from Transaction__c where Account_Name__c=:account.Id and RecordType.Name='נקודות' Order by Date_of_Transaction__c DESC limit 1];
            }catch (QueryException ep) {   
                try {
                    trans = [SELECT Id, Name, Type__c FROM Transaction__c WHERE Account_Name__c=:account.Id AND Type__c=:boat.Type__c ORDER BY Date_of_Transaction__c DESC LIMIT 1];
                } catch (QueryException e) {
                    if(Test.isRunningTest()){
                        payment = '1';
                        trans = new Transaction__c(
                            Account_Name__c=account.Id,
                            Type__c=boat.Type__c,
                            type_of_membership__c = 'חבר מועדון כולל פרטיות',
                            Name='עסקה חדשה - ' + boat.Type__c
                        );
                        insert trans;
                    }
                    else
                        throw new QueryException('לא נמצאה עסקה מתאימה במערכת');
                }
            }
        else
            trans = [SELECT Id, Name FROM Transaction__c WHERE Transaction_Number__c='D-00001' LIMIT 1];

        if (isClassic) {
            PageReference pRef = new PageReference('/a04/e');
            param = pRef.getParameters();
            param.put('CF00N0Y00000R49jV', boat.Name);
            param.put('CF00N0Y00000R49jV_lkid', boat.Id);
            param.put('00N0Y00000R49jp', start);
            param.put('00N0Y00000R49je', endd);
            param.put('RecordType', rt.Id);
            if (account != null) {
                param.put('CF00N0Y00000R49jR', account.Name);
                param.put('CF00N0Y00000R49jR_lkid', account.Id);
            }
            param.put('00N0Y00000R49jo', payment);
            param.put('CF00N0Y00000R49iq', trans.Name);
            param.put('CF00N0Y00000R49iq_lkid', trans.Id);
            param.put('retURL', retURL);
            pRef.setRedirect(true);
            return pRef;
        } else {
            createParam = JSON.serialize(new Map<String, Object>{
                'Boat__c' => boat.Id,
                    
                // commented by bali for Date-time parsing was changed from Datetime.parse() to Datetime.newInstance()
                //'Start_Date__c' => Datetime.parse(start),
                //'End_Date__c' => Datetime.parse(endd),
                
                    
                 'Start_Date__c' => Datetime.newInstance(
                    Integer.valueOf(start.split(' ')[1].split('/')[2]), Integer.valueOf(start.split(' ')[1].split('/')[1]), Integer.valueOf(start.split(' ')[1].split('/')[0]), 
                    Integer.valueOf(start.split(' ')[0].split(':')[0]), Integer.valueOf(start.split(' ')[0].split(':')[1]), 0),
                'End_Date__c' => Datetime.newInstance(
                    Integer.valueOf(endd.split(' ')[1].split('/')[2]), Integer.valueOf(endd.split(' ')[1].split('/')[1]), Integer.valueOf(endd.split(' ')[1].split('/')[0]),
                    Integer.valueOf(endd.split(' ')[0].split(':')[0]), Integer.valueOf(endd.split(' ')[0].split(':')[1]), 0 ),
                                    
                    
                    
                'AccountName__c' => account != null ? account.Id : null,
                'Payment_Required__c' => payment == '1',
                'Transaction__c' => trans.Id
            });
            return null;
        }
    }

}