force-app-modified/main/default/objects/Boats__c/Boats__c.object-meta.xml
<CustomObject>
    <label>סירה</label>
    <nameField>
        <label>שם סירה</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>סירות</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Boats__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>סטטוס פעיל/לא פעיל</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Co_Cruise_Members__c/Co_Cruise_Members__c.object-meta.xml
<CustomObject>
    <label>לקוח משנה להפלגה</label>
    <nameField>
        <displayFormat>M-{00000}</displayFormat>
        <label>מספר מפליג משנה</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>לקוחות משנה להפלגה</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app-modified/main/default/objects/Co_Cruise_Members__c/fields/Account_Co__c.field-meta.xml
<CustomField>
    <fullName>Account_Co__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>לקוח</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>לקוחות משנה להפלגה</relationshipLabel>
    <relationshipName>Co_Cruise_Sailres</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Co_Cruise_Members__c/fields/Cruise__c.field-meta.xml
<CustomField>
    <fullName>Cruise__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>הפלגה</label>
    <referenceTo>Cruise__c</referenceTo>
    <relationshipLabel>לקוחות משנה להפלגה</relationshipLabel>
    <relationshipName>Co_Cruise_Sailres</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app-modified/main/default/objects/Co_Cruise_Members__c/fields/SailType__c.field-meta.xml
<CustomField>
    <fullName>SailType__c</fullName>
    <formula>Cruise__r.RecordType.DeveloperName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>סוג הפלגה</label>
    <type>Text</type>
</CustomField>

force-app-modified/main/default/objects/Co_Cruise_Members__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>TEXT(Cruise__r.Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>סטטוס הפלגה</label>
    <type>Text</type>
</CustomField>

force-app-modified/main/default/objects/Co_Cruise_Members__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>עסקה</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>לקוחות משנה להפלגה</relationshipLabel>
    <relationshipName>Co_Cruise_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/Cruise__c.object-meta.xml
<CustomObject>
    <label>הפלגה</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>מספר הפלגה</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>הפלגות</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app-modified/main/default/objects/Cruise__c/fields/AccountName__c.field-meta.xml
<CustomField>
    <fullName>AccountName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>שם לקוח</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>הפלגות</relationshipLabel>
    <relationshipName>Cruises</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cruise__c/fields/Additional_Info__c.field-meta.xml
<CustomField>
    <fullName>Additional_Info__c</fullName>
    <label>מידע נוסף למשתתפים</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Cruise__c/fields/Boat__c.field-meta.xml
<CustomField>
    <fullName>Boat__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>סירה</label>
    <referenceTo>Boats__c</referenceTo>
    <relationshipLabel>הפלגות</relationshipLabel>
    <relationshipName>Boat</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cruise__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>תאריך סיום</label>
    <type>DateTime</type>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>תאריך התחלה</label>
    <type>DateTime</type>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>סטטוס</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Guide Matching</fullName>
                <label>לתיאום מדריך</label>
            </value>
            <value>
                <fullName>Awaiting for Approval</fullName>
                <label>ממתינה לאישור</label>
            </value>
            <value>
                <fullName>For Payment</fullName>
                <label>ממתין לתשלום</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
                <label>מבוטלת</label>
            </value>
            <value>
                <fullName>Ready</fullName>
                <label>מוכן להזמנה</label>
            </value>
            <value>
                <fullName>Occupied</fullName>
                <label>תפוס</label>
            </value>
            <value>
                <fullName>No Qualification</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <label>עסקאות</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>הפלגות</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/recordTypes/Club.recordType-meta.xml
<RecordType>
    <fullName>Club</fullName>
    <active>true</active>
    <label>Club</label>
</RecordType>

force-app-modified/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>עסקה</label>
    <nameField>
        <label>שם עסקה</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>עסקאות</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app-modified/main/default/objects/Transaction__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <description>T.A 12-11-2020: it was : IF(TODAY()&gt; End_Date__c , True,False)</description>
    <formula>IF(TODAY()&lt; End_Date__c , True,False)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>פעיל</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <defaultValue>today()+365</defaultValue>
    <label>תאריך סיום</label>
    <type>Date</type>
</CustomField>

force-app-modified/main/default/objects/Transaction__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <defaultValue>today()</defaultValue>
    <label>תאריך התחלה</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Transaction__c/recordTypes/RecordType.recordType-meta.xml
<RecordType>
    <fullName>RecordType</fullName>
    <active>false</active>
    <label>מוצרים אחרים</label>
</RecordType>

force-app/main/default/classes/HomePageController.cls
/**
 * @description Apex controller class for Home page.
 * @author Ceptes
 * @date Tuesday-July-09-2024
 **/

public without sharing class HomePageController {

    static SeaTimeAppSelector selector = new SeaTimeAppSelector();
   
    @AuraEnabled
    public static Map<string, object> getHomePageTabsData(id accountId) {

        Transaction__c transactionData;
        Map<String, Object> homePageDataToReturn = new Map<String, Object>();

        Cruise__c[] cruiseRecordsArray    = selector.getRecentCruiseRecords(accountId);
        Account accountData               = selector.getAccountFromId(accountId);
        Transaction__c transactionRec = selector.getTransactionFromAccount(accountId);
        transactionData = transactionRec.Id != null ? transactionRec : null;

        List<PastSailing> pastClubCruises = getPastSailings(accountId, false);
        
        homePageDataToReturn.put('cruiseRecordsArray', cruiseRecordsArray);
        homePageDataToReturn.put('pastClubCruises', pastClubCruises);
        homePageDataToReturn.put('account', accountData);
        homePageDataToReturn.put('transaction', transactionData);

        return homePageDataToReturn;
    }

    @AuraEnabled
    public static List<PastSailing> getPastSailings(Id accountId, Boolean allPast) {
        List<PastSailing> results = new List<PastSailing>();

        Account acc = selector.getAccountFromId(accountId);
        Transaction__c trans = selector.getTransactionFromAccount(accountId);
        Boolean isStudent = acc != null && acc.StudentMeshit30__c == true;
        Id activeTransId = (trans != null && trans.Id != null && trans.Active__c) ? trans.Id : null;

        // 1. Private Cruises (RecordType = Club, AccountName__c = accountId)
        String privateQuery = 'SELECT Id, Boat__r.Name, Start_Date__c, End_Date__c, Additional_Info__c, Status__c, Transaction__c FROM Cruise__c WHERE AccountName__c = :accountId AND RecordType.Name = \'Club\' AND Status__c != \'Canceled\' AND Start_Date__c < TODAY';
        if (!allPast && activeTransId != null) {
            privateQuery += ' AND Transaction__c = :activeTransId';
        }
        List<Cruise__c> privateCruises = Database.query(privateQuery);
        for (Cruise__c c : privateCruises) {
            PastSailing ps = new PastSailing();
            ps.Id = c.Id;
            ps.boatName = c.Boat__r != null ? c.Boat__r.Name : '';
            ps.startDate = c.Start_Date__c;
            ps.endDate = c.End_Date__c;
            ps.additionalInfo = c.Additional_Info__c;
            ps.status = c.Status__c;
            ps.sailingType = 'Private';
            results.add(ps);
        }

        // 2. Guided Cruises (Co_Cruise_Members__c)
        String guidedQuery = 'SELECT Id, Cruise__r.Boat__r.Name, Cruise__r.Start_Date__c, Cruise__r.End_Date__c, Cruise__r.Additional_Info__c, Status__c, Transaction__c, SailType__c FROM Co_Cruise_Members__c WHERE Account_Co__c = :accountId AND Status__c != \'Canceled\' AND Cruise__r.Status__c != \'Canceled\' AND Cruise__r.Start_Date__c < TODAY';
        if (!allPast && activeTransId != null && !isStudent) {
            guidedQuery += ' AND Transaction__c = :activeTransId';
        }
        List<Co_Cruise_Members__c> guidedCruises = Database.query(guidedQuery);
        for (Co_Cruise_Members__c ccm : guidedCruises) {
            PastSailing ps = new PastSailing();
            ps.Id = ccm.Id;
            ps.boatName = ccm.Cruise__r != null && ccm.Cruise__r.Boat__r != null ? ccm.Cruise__r.Boat__r.Name : '';
            ps.startDate = ccm.Cruise__r != null ? ccm.Cruise__r.Start_Date__c : null;
            ps.endDate = ccm.Cruise__r != null ? ccm.Cruise__r.End_Date__c : null;
            ps.additionalInfo = ccm.Cruise__r != null ? ccm.Cruise__r.Additional_Info__c : '';
            ps.status = ccm.Status__c;
            ps.sailingType = 'Guided';
            results.add(ps);
        }

        results.sort();
        return results;
    }

    public class PastSailing implements Comparable {
        @AuraEnabled public Id Id {get;set;}
        @AuraEnabled public String boatName {get;set;}
        @AuraEnabled public DateTime startDate {get;set;}
        @AuraEnabled public DateTime endDate {get;set;}
        @AuraEnabled public String additionalInfo {get;set;}
        @AuraEnabled public String status {get;set;}
        @AuraEnabled public String sailingType {get;set;}

        public Integer compareTo(Object compareTo) {
            PastSailing compareToSailing = (PastSailing)compareTo;
            if (this.startDate == null || compareToSailing.startDate == null) return 0;
            if (this.startDate == compareToSailing.startDate) return 0;
            if (this.startDate > compareToSailing.startDate) return -1;
            return 1;
        }
    }
}