force-app-modified/main/default/objects/Boats__c/Boats__c.object-meta.xml
<CustomObject>
    <label>סירה</label>
    <nameField>
        <label>שם סירה</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>סירות</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app-modified/main/default/objects/Boats__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>סוג סירה</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Boat_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Co_Cruise_Members__c/Co_Cruise_Members__c.object-meta.xml
<CustomObject>
    <label>לקוח משנה להפלגה</label>
    <nameField>
        <displayFormat>M-{00000}</displayFormat>
        <label>מספר מפליג משנה</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>לקוחות משנה להפלגה</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Co_Cruise_Members__c/fields/Cruise__c.field-meta.xml
<CustomField>
    <fullName>Cruise__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>הפלגה</label>
    <referenceTo>Cruise__c</referenceTo>
    <relationshipLabel>לקוחות משנה להפלגה</relationshipLabel>
    <relationshipName>Co_Cruise_Sailres</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app-modified/main/default/objects/Co_Cruise_Members__c/fields/Cruise_Points__c.field-meta.xml
<CustomField>
    <fullName>Cruise_Points__c</fullName>
    <label>שווי ניקוד הפלגה</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app-modified/main/default/objects/Co_Cruise_Members__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>TEXT(Cruise__r.Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>סטטוס הפלגה</label>
    <type>Text</type>
</CustomField>

force-app-modified/main/default/objects/Co_Cruise_Members__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>עסקה</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>לקוחות משנה להפלגה</relationshipLabel>
    <relationshipName>Co_Cruise_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/Cruise__c.object-meta.xml
<CustomObject>
    <label>הפלגה</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>מספר הפלגה</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>הפלגות</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app-modified/main/default/objects/Cruise__c/fields/AccountName__c.field-meta.xml
<CustomField>
    <fullName>AccountName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>שם לקוח</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>הפלגות</relationshipLabel>
    <relationshipName>Cruises</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cruise__c/fields/AddingReducingPoints__c.field-meta.xml
<CustomField>
    <fullName>AddingReducingPoints__c</fullName>
    <label>הוספת/הורדת נקודות ידנית</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cruise__c/fields/Boat__c.field-meta.xml
<CustomField>
    <fullName>Boat__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>סירה</label>
    <referenceTo>Boats__c</referenceTo>
    <relationshipLabel>הפלגות</relationshipLabel>
    <relationshipName>Boat</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/fields/Cruise_Points__c.field-meta.xml
<CustomField>
    <fullName>Cruise_Points__c</fullName>
    <label>שווי ניקוד הפלגה</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cruise__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>תאריך סיום</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Cruise__c/fields/Extra_Hours_Charge__c.field-meta.xml
<CustomField>
    <fullName>Extra_Hours_Charge__c</fullName>
    <label>Extra Hours Charge</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cruise__c/fields/Hidden_Total_Hours__c.field-meta.xml
<CustomField>
    <fullName>Hidden_Total_Hours__c</fullName>
    <formula>(floor(( End_Date__c - Start_Date__c )*24)) 
+ 

ROUND(MOD((End_Date__c - Start_Date__c)*1440,60),0)/60
+ 

Extra_Hours_Charge__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>סה&quot;כ שעות הפלגה</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/fields/Holiday__c.field-meta.xml
<CustomField>
    <fullName>Holiday__c</fullName>
    <defaultValue>false</defaultValue>
    <label>חגים ומועדים</label>
    <type>Checkbox</type>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>תאריך התחלה</label>
    <type>DateTime</type>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>סטטוס</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Guide Matching</fullName>
                <label>לתיאום מדריך</label>
            </value>
            <value>
                <fullName>Awaiting for Approval</fullName>
                <label>ממתינה לאישור</label>
            </value>
            <value>
                <fullName>For Payment</fullName>
                <label>ממתין לתשלום</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
                <label>מבוטלת</label>
            </value>
            <value>
                <fullName>Ready</fullName>
                <label>מוכן להזמנה</label>
            </value>
            <value>
                <fullName>Occupied</fullName>
                <label>תפוס</label>
            </value>
            <value>
                <fullName>No Qualification</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <label>עסקאות</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>הפלגות</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Cruise__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>סוג הסירה</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>מפרשית</fullName>
            </value>
            <value>
                <fullName>יאכטה</fullName>
            </value>
            <value>
                <fullName>קטמרן</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/recordTypes/Club.recordType-meta.xml
<RecordType>
    <fullName>Club</fullName>
    <active>true</active>
    <label>Club</label>
</RecordType>

force-app-modified/main/default/objects/Cruise__c/recordTypes/Enriching.recordType-meta.xml
<RecordType>
    <fullName>Enriching</fullName>
    <active>true</active>
    <label>Enriching</label>
</RecordType>

force-app-modified/main/default/objects/Cruise__c/recordTypes/Friends.recordType-meta.xml
<RecordType>
    <fullName>Friends</fullName>
    <active>true</active>
    <label>Friends</label>
</RecordType>

force-app-modified/main/default/objects/PriceList__c/PriceList__c.object-meta.xml
<CustomObject>
    <label>מחירון</label>
    <nameField>
        <label>שם מחירון</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>מחירון</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PriceList__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>תעריף ברירת מחדל</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app-modified/main/default/objects/PriceList__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>תאריך התחלה</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app-modified/main/default/objects/PriceList__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>סוג</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>רגיל</fullName>
                <default>true</default>
                <label>רגיל</label>
            </value>
            <value>
                <fullName>מבצע</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app-modified/main/default/objects/PriceListLine__c/PriceListLine__c.object-meta.xml
<CustomObject>
    <label>שורת מחירון</label>
    <nameField>
        <displayFormat>PLL-{0}</displayFormat>
        <label>שם שורת מחירון</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PriceListLines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app-modified/main/default/objects/PriceListLine__c/fields/Boat__c.field-meta.xml
<CustomField>
    <fullName>Boat__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>סירה</label>
    <referenceTo>Boats__c</referenceTo>
    <relationshipLabel>PriceListLines</relationshipLabel>
    <relationshipName>PriceListLines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app-modified/main/default/objects/PriceListLine__c/fields/Global__c.field-meta.xml
<CustomField>
    <fullName>Global__c</fullName>
    <defaultValue>false</defaultValue>
    <label>גלובלי</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PriceListLine__c/fields/HPrice__c.field-meta.xml
<CustomField>
    <fullName>HPrice__c</fullName>
    <label>תעריף חג</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PriceListLine__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>תעריף</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PriceListLine__c/fields/PriceList__c.field-meta.xml
<CustomField>
    <fullName>PriceList__c</fullName>
    <label>מחירון</label>
    <referenceTo>PriceList__c</referenceTo>
    <relationshipLabel>PriceListLines</relationshipLabel>
    <relationshipName>PriceListLines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PriceListLine__c/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <defaultValue>TIMEVALUE(&apos;00:00:00.000&apos;)</defaultValue>
    <label>שעת התחלה</label>
    <required>true</required>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/PriceListLine__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>סוג</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Abroad</fullName>
                <isActive>false</isActive>
                <label>Abroad</label>
            </value>
            <value>
                <fullName>Course</fullName>
                <isActive>false</isActive>
                <label>Course</label>
            </value>
            <value>
                <fullName>General</fullName>
                <isActive>false</isActive>
                <label>General</label>
            </value>
            <value>
                <fullName>Introduction</fullName>
                <isActive>false</isActive>
                <label>Introduction</label>
            </value>
            <value>
                <fullName>Maintenance</fullName>
                <isActive>false</isActive>
                <label>Maintenance</label>
            </value>
            <value>
                <fullName>Renting</fullName>
                <isActive>false</isActive>
                <label>Renting</label>
            </value>
            <value>
                <fullName>Certification</fullName>
                <label>הסמכה</label>
            </value>
            <value>
                <fullName>Friends</fullName>
                <label>חברים</label>
            </value>
            <value>
                <fullName>Enriching</fullName>
                <label>מודרכת</label>
            </value>
            <value>
                <fullName>Club</fullName>
                <default>true</default>
                <label>מועדון</label>
            </value>
            <value>
                <fullName>Renewal</fullName>
                <label>ריענון</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app-modified/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>עסקה</label>
    <nameField>
        <label>שם עסקה</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>עסקאות</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>שם לקוח</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>עסקאות</relationshipLabel>
    <relationshipName>Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Date_of_Transaction__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Transaction__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>תאריך העסקה</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <defaultValue>today()+365</defaultValue>
    <label>תאריך סיום</label>
    <type>Date</type>
</CustomField>

force-app-modified/main/default/objects/Transaction__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <defaultValue>today()</defaultValue>
    <label>תאריך התחלה</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Transaction__c/recordTypes/Points.recordType-meta.xml
<RecordType>
    <fullName>Points</fullName>
    <active>true</active>
    <label>נקודות</label>
</RecordType>

force-app/main/default/objects/Transaction__c/recordTypes/RecordType.recordType-meta.xml
<RecordType>
    <fullName>RecordType</fullName>
    <active>false</active>
    <label>מוצרים אחרים</label>
</RecordType>

force-app-modified/main/default/objects/Transaction__c/recordTypes/Subscription.recordType-meta.xml
<RecordType>
    <fullName>Subscription</fullName>
    <active>false</active>
    <label>Subscription</label>
</RecordType>

force-app/main/default/classes/CruiseHandler.cls
/*
* @Author: ZedXagE 
* @Date: 2019-04-23 11:10:31 
* @Last Modified by: ZedXagE
* @Last Modified time: 2019-04-23 13:53:06
*/

public without sharing class CruiseHandler {
    public static Boolean firstRun = true;
    private hlp_triggerChanges isChangedHelper = new hlp_triggerChanges();
    private CruiseManager manager = new CruiseManager();
    private final String CLUB_RECORD_TYPE_DEV_NAME = 'Club';
    public void checkAccountHasCertificate(List < Cruise__c > newList) {
        Set < Id > AccIdSet = new Set < Id > ();
        List < Cruise__c > clubCruiseList = new List < Cruise__c > ();
        Map < Id, Account > cruiseToAccountMap = new Map < Id, Account > ();
        //Id subscriptionRecordTypeId = Schema.SObjectType.Transaction__c.getRecordTypeInfosByName().get('Subscription').getRecordTypeId(); //schema returns hebrew keys
        RecordType clubRecordType = [SELECT Id, Name, DeveloperName
                                     FROM RecordType
                                     WHERE DeveloperName =: CLUB_RECORD_TYPE_DEV_NAME LIMIT 1
                                    ];
        for (Cruise__c crs: newList) {
            if (crs.RecordTypeId == clubRecordType.Id) {
                AccIdSet.add(crs.AccountName__c);
                clubCruiseList.add(crs);
            }
        }
        if (AccIdSet != null && !AccIdSet.isEmpty()) {
            Map < Id, Account > realatedAccountMap = new Map < Id, Account > (
                [Select Id, Name,
                 (Select Name, Boat__c From Account_Name__r)
                 From Account
                 WHERE Id in: AccIdSet
                ]);
            for (Cruise__c cruiseItem: clubCruiseList) {
                Account relatedAccount = realatedAccountMap.get(cruiseItem.AccountName__c);
                if (relatedAccount != null) {
                    cruiseToAccountMap.put(cruiseItem.Id, relatedAccount);
                }
            }
            manager.checkAccountHasCertificate(clubCruiseList, cruiseToAccountMap);
        }
    }
    public void CalculateExtraHours(List < Cruise__c > newList, Set <String> statchanged) {
        String clubrectype = [select id from RecordType where Name = 'Club'
                              and SobjectType = 'Cruise__c'
                             ].id;
        Set < String > transids = new Set < String > ();
        Set <String> transchanged = new Set <String>();
        for (Cruise__c crs: newList)
            if (crs.Transaction__c != null){
                if (crs.RecordTypeid == clubrectype) transids.add(crs.Transaction__c);
            }
        //query
        List < PriceList__c > dispricelists = [select id, Type__c, Start_Date__c, End_Date__c, Price__c, (select id, Start__c, Type__c, Boat__c, Price__c, HPrice__c, Global__c from PriceListLines__r
                                                                                                          Order by Start__c) from PriceList__c Where Type__c = 'מבצע'
                                               Order by Start_Date__c DESC
                                              ];
        List < PriceList__c > regpricelists = [select id, Type__c, Start_Date__c, End_Date__c, Price__c, (select id, Start__c, Type__c, Boat__c, Price__c, HPrice__c, Global__c from PriceListLines__r
                                                                                                          Order by Start__c) from PriceList__c Where Type__c = 'רגיל'
                                               Order by Start_Date__c DESC
                                              ];
        Map < String, Transaction__c > trans = new Map < String, Transaction__c > ([select id, Date_of_Transaction__c from Transaction__c where RecordType.Name = 'נקודות'
                                                                                    and id in: transids
                                                                                   ]);
        DateTime startDate;
        DateTime endDate;
        Double extraHours;
        Double extraHolidayHours;
        for (Cruise__c crs: newList) {
            Decimal oldpts = crs.Cruise_Points__c;
            crs.Cruise_Points__c = 0;
            system.debug('trans='+trans);
            system.debug('crs='+crs);
            system.debug('crs.Transaction__c='+trans.get(crs.Transaction__c));
            if (trans.containsKey(crs.Transaction__c)) {
                Date dt = Date.newInstance(crs.Start_Date__c.year(), crs.Start_Date__c.month(), crs.Start_Date__c.day());
                //new Points
                Boolean found = false;
                for (PriceList__c pl: dispricelists){
                    system.debug('pl.Start_Date__c=' +pl.Start_Date__c);
                    system.debug('dt='+dt);
                    if (pl.Start_Date__c <= dt && (pl.End_Date__c == null || pl.End_Date__c >= dt)) {
                        found = true;
                        Decimal basePoints = TransactionPoints.getPTS('Club', crs.Boat__c, crs.Holiday__c||dt.toStartOfWeek().daysBetween(dt)==6||dt.toStartOfWeek().daysBetween(dt)==5, pl.PriceListLines__r, pl.Price__c, crs.Start_Date__c, crs.End_Date__c);
                        Decimal adjustment = crs.AddingReducingPoints__c != null ? crs.AddingReducingPoints__c : 0;
                        crs.Cruise_Points__c = basePoints + adjustment;
                        break;
                    }}
                if (!found) {
                    Date dt2 = dt;
                    dt = Date.newInstance(trans.get(crs.Transaction__c).Date_of_Transaction__c.year(), trans.get(crs.Transaction__c).Date_of_Transaction__c.month(), trans.get(crs.Transaction__c).Date_of_Transaction__c.day());
                    for (PriceList__c pl: regpricelists){
                        system.debug('--pl.Start_Date__c='+pl.Start_Date__c);
                        system.debug('--pl.End_Date__c='+pl.End_Date__c);
                        system.debug('--dt='+dt);
                        if (pl.Start_Date__c <= dt && (pl.End_Date__c == null || pl.End_Date__c >= dt)) {
                            found = true;
                            Decimal basePoints = TransactionPoints.getPTS('Club', crs.Boat__c, crs.Holiday__c||dt2.toStartOfWeek().daysBetween(dt2)==6||dt2.toStartOfWeek().daysBetween(dt2)==5, pl.PriceListLines__r, pl.Price__c, crs.Start_Date__c, crs.End_Date__c);
                            Decimal adjustment = crs.AddingReducingPoints__c != null ? crs.AddingReducingPoints__c : 0;
                            crs.Cruise_Points__c = basePoints + adjustment;
                            break;
                        }
                    }
                }
                if(crs.Cruise_Points__c!=oldpts||statchanged.contains(crs.id))    transchanged.add(crs.Transaction__c);
            } else {
                //old hours
                startDate = crs.Start_Date__c;
                endDate = crs.End_Date__c;
                if (crs.Holiday__c) {
                    extraHolidayHours = crs.Hidden_Total_Hours__c;
                    extraHolidayHours = (extraHolidayHours * 150 / 100) - extraHolidayHours;
                    crs.Extra_Hours_Charge__c = extraHolidayHours;
                } else {
                    extraHours = manager.CalculateExtraHours(startDate, endDate);
                    crs.Extra_Hours_Charge__c = extraHours;
                }
            }
        }
        if(transchanged.size()>0)   ID jobID = System.enqueueJob(new TransactionPoints(transchanged));
    }
    public void CalculateExtraHours(Map < Id, Cruise__c > newMap, Map < Id, Cruise__c > oldMap) {
        List < Cruise__c > CruiseUpdateList = new List < Cruise__c > ();
        Set < Id > cruiseIdSet = new Set < Id > ();
        Set <String> statchanged = new Set <String>();
        List < String > cruiseChange = new List < String > {
            'Start_Date__c',
                'End_Date__c',
                'Holiday__c',
                'Status__c',
                'Transaction__c',
                'AddingReducingPoints__c'
                };
                    isChangedHelper.setNewCollection('cruisChange', cruiseChange);
        if (!isChangedHelper.getCollectionChanges('cruisChange').isEmpty()) {
            cruiseIdSet = isChangedHelper.getCollectionChanges('cruisChange');
        }
        for (Id idItem: cruiseIdSet) {
            CruiseUpdateList.add(newMap.get(idItem));
        }
        for(Id id:newMap.keySet())
            if(newMap.get(id).Status__c!=oldMap.get(id).Status__c)
            statchanged.add(id);
        if (!CruiseUpdateList.isEmpty()) {
            this.CalculateExtraHours(CruiseUpdateList,statchanged);
        }
        List <Cruise__c> oldmoved = new List <Cruise__c>();
        for(Id id:newMap.keySet())
            if(newMap.get(id).Transaction__c!=oldMap.get(id).Transaction__c)
            oldmoved.add(oldMap.get(id));
        if(oldmoved.size()>0)   upOldVals(oldmoved);
    }
    public void upOldVals(List <Cruise__c> oldcrs){
        String clubrectype = [select id from RecordType where Name = 'Club'
                              and SobjectType = 'Cruise__c'
                             ].id;
        Set <String> ccmsids = new Set <String>();
        Set <String> transids = new Set <String> ();
        Set <String> transchanged = new Set <String> ();
        for (Cruise__c crs: oldcrs)
            if (crs.Transaction__c != null && crs.RecordTypeid == clubrectype) transids.add(crs.Transaction__c);
        else if(crs.RecordTypeid != clubrectype) ccmsids.add(crs.id);
        Map < String, Transaction__c > trans = new Map < String, Transaction__c > ([select id, Date_of_Transaction__c from Transaction__c where RecordType.Name = 'נקודות'
                                                                                    and id in: transids
                                                                                   ]);
        transchanged.addAll(trans.keySet());
        List <Co_Cruise_Members__c> ccms = [select id,Transaction__c from Co_Cruise_Members__c where Cruise__c in: ccmsids];
        for(Co_Cruise_Members__c ccm:ccms)
            ccm.Cruise__c = null;
        Database.update(ccms,false);
        if(transchanged.size()>0)   ID jobID = System.enqueueJob(new TransactionPoints(transchanged));
    }
    // Method to update noOfSCCountsForSelectedMonth when the cruise status get cancelled.
    // created by Sameer on 15th Dec 2021.
    public void updateNumberOfCount(List<Cruise__c> listOfCruise, map<Id, Cruise__c> mapOfOldCruise){
        try{
            Id recTypeIdEnrichingType = Schema.SObjectType.Cruise__c.getRecordTypeInfosByDeveloperName().get('Enriching').getRecordTypeId();
            Id recTypeIdFriendsType = Schema.SObjectType.Cruise__c.getRecordTypeInfosByDeveloperName().get('Friends').getRecordTypeId();
            /*System.debug('recTypeIdEnrichingType >>>>>'+recTypeIdEnrichingType + 'recTypeIdFriendsType> '+recTypeIdFriendsType);
            System.debug('listOfCruise >>>>>'+listOfCruise);
            System.debug('mapOfOldCruise >>>>>'+mapOfOldCruise);
            Set<ID> setOfCruiseIds = new Set<ID>();
            for(Cruise__c crus: listOfCruise){
                system.debug('recordTypeId >>>>>>> '+crus.recordTypeId);
                system.debug('Old Cruse Status >>>>> '+mapOfOldCruise.get(crus.Id).Status__c);
                if(crus.Status__c == 'Canceled' && (crus.recordTypeId ==recTypeIdEnrichingType || crus.recordTypeId ==recTypeIdFriendsType) && crus.Status__c != mapOfOldCruise.get(crus.Id).Status__c){
                    setOfCruiseIds.add(crus.Id);
                }
            }
            System.debug('setOfCruiseIds >>>>'+setOfCruiseIds);
            Map<Id, List<Co_Cruise_Members__c>> cruiseCoCruiseMap = new Map<Id, List<Co_Cruise_Members__c>>();
            List<Co_Cruise_Members__c> cruiseAndCocruiseList = [Select Id, Name, noOfSCCountsForSelectedMonth__c, Cruise__r.name, Cruise__r.ID From Co_Cruise_Members__c where Cruise__r.ID in: setOfCruiseIds];
            System.debug('cruiseAndCocruiseList >>>>>'+cruiseAndCocruiseList);
            
            for(Co_Cruise_Members__c coCru : cruiseAndCocruiseList){
                if(!cruiseCoCruiseMap.ContainsKey(coCru.Cruise__r.ID))
                    cruiseCoCruiseMap.put(coCru.Cruise__r.ID, new List<Co_Cruise_Members__c>());
                cruiseCoCruiseMap.get(coCru.Cruise__r.ID).add(coCru);
            }
            System.debug('cruiseCoCruiseMap >>>>>>>'+cruiseCoCruiseMap); 
            List<Co_Cruise_Members__c> coCruiseListToUpdate=new List<Co_Cruise_Members__c>();
            for(ID cru: cruiseCoCruiseMap.keySet())
            {
                List<Co_Cruise_Members__c> newCoCruisList=cruiseCoCruiseMap.get(cru);
                if(newCoCruisList.size() > 0)
                {
                    for(Co_Cruise_Members__c newCoCruise: newCoCruisList)
                    {
                        if(newCoCruise.noOfSCCountsForSelectedMonth__c !=null && newCoCruise.noOfSCCountsForSelectedMonth__c > 0)
                        {   
                            Co_Cruise_Members__c coCruMem = new Co_Cruise_Members__c();
                            coCruMem.Id = newCoCruise.Id;
                            coCruMem.noOfSCCountsForSelectedMonth__c = newCoCruise.noOfSCCountsForSelectedMonth__c -1;
                            coCruiseListToUpdate.add(coCruMem);
                        }
                    }
                }
            }
            System.debug('coCruiseListToUpdate >>>>>'+coCruiseListToUpdate);
            if(coCruiseListToUpdate.size()>0)
                update coCruiseListToUpdate; 
			*/
            if(
                listOfCruise[0].Status__c == 'Canceled' && 
                (listOfCruise[0].recordTypeId == recTypeIdEnrichingType || listOfCruise[0].recordTypeId == recTypeIdFriendsType) && 
                listOfCruise[0].Status__c != mapOfOldCruise.get(listOfCruise[0].Id).Status__c && 
                listOfCruise[0].Start_Date__c != NULL
            ) {
                Date startDate = Date.newInstance(listOfCruise[0].Start_Date__c.year(), listOfCruise[0].Start_Date__c.month(), 1);
                Integer numberOfDays = Date.daysInMonth(startDate.year(), startDate.month());
                Date endDate = Date.newInstance(listOfCruise[0].Start_Date__c.year(), listOfCruise[0].Start_Date__c.month(), numberOfDays);
                List<Co_Cruise_Members__c> cruiseAndCocruiseList = [SELECT Id, noOfSCCountsForSelectedMonth__c FROM Co_Cruise_Members__c WHERE Cruise__r.Start_Date__c >= :startDate AND Cruise__r.Start_Date__c <= :endDate AND (SailType__c='Friends' OR SailType__c='Enriching')];
               /* List<Co_Cruise_Members__c> cruiseAndCocruiseListChild = [SELECT Id, noOfSCCountsForSelectedMonth__c FROM Co_Cruise_Members__c WHERE Cruise__r.Start_Date__c >= :startDate AND Cruise__r.Start_Date__c <= :endDate AND Cruise__c IN : listOfCruise];
                Integer count;
                if(!cruiseAndCocruiseListChild.isEmpty()){
                count = cruiseAndCocruiseListChild.size();
                  }
                 else count=0; */
                
                if(!cruiseAndCocruiseList.isEmpty()) {
                    for(Co_Cruise_Members__c member : cruiseAndCocruiseList) {
                        if(member.noOfSCCountsForSelectedMonth__c == NULL)
                            member.noOfSCCountsForSelectedMonth__c = 0;
                        member.noOfSCCountsForSelectedMonth__c -= 1;
                    }
                    Database.update(cruiseAndCocruiseList, false);
                }
            }
            if (
                listOfCruise[0].Status__c != 'Canceled' && mapOfOldCruise.get(listOfCruise[0].Id).Status__c =='Canceled' &&
                (listOfCruise[0].recordTypeId == recTypeIdEnrichingType || listOfCruise[0].recordTypeId == recTypeIdFriendsType) && 
                listOfCruise[0].Start_Date__c != NULL &&
                firstRun
            ) {
                firstRun = false;
                 Date startDate = Date.newInstance(listOfCruise[0].Start_Date__c.year(), listOfCruise[0].Start_Date__c.month(), 1);
                Integer numberOfDays = Date.daysInMonth(startDate.year(), startDate.month());
                Date endDate = Date.newInstance(listOfCruise[0].Start_Date__c.year(), listOfCruise[0].Start_Date__c.month(), numberOfDays);
                List<Co_Cruise_Members__c> cruiseAndCocruiseList = [SELECT Id, noOfSCCountsForSelectedMonth__c FROM Co_Cruise_Members__c WHERE Cruise__r.Start_Date__c >= :startDate AND Cruise__r.Start_Date__c <= :endDate AND (SailType__c='Friends' OR SailType__c='Enriching')];
               /*  List<Co_Cruise_Members__c> cruiseAndCocruiseListChild = [SELECT Id, noOfSCCountsForSelectedMonth__c FROM Co_Cruise_Members__c WHERE Cruise__r.Start_Date__c >= :startDate AND Cruise__r.Start_Date__c <= :endDate AND Cruise__c IN : listOfCruise];
                Integer count;
                if(!cruiseAndCocruiseListChild.isEmpty()){
                count = cruiseAndCocruiseListChild.size();
                  }
                 else count=0; */
                
                if(!cruiseAndCocruiseList.isEmpty()) {
                    for(Co_Cruise_Members__c member : cruiseAndCocruiseList) {
                        if(member.noOfSCCountsForSelectedMonth__c == NULL)
                            member.noOfSCCountsForSelectedMonth__c = 0;
                        member.noOfSCCountsForSelectedMonth__c += 1;
                    }
                    Database.update(cruiseAndCocruiseList, false);
            }
                }
        }catch(Exception ex){
            System.debug('Occured error is >>>>>>>'+ex.getMessage()+'At line number >>>>>>'+ex.getLineNumber());
        }
    }
    
    // Method to update the available seats in boat when the cruise record is get updated with Enriching or Friends record type
    // created by Sameer on 15th Dec 2021.
 /*   public void updateAvailableSeatsInboat(List<Cruise__c> listOfCruiseForBoatSeat, map<Id,Cruise__c> oldmapValues){
        try{
            Id recTypeIdFriendsType = Schema.SObjectType.Cruise__c.getRecordTypeInfosByName().get('Friends').getRecordTypeId();
            Id recTypeIdEnrichingType = Schema.SObjectType.Cruise__c.getRecordTypeInfosByName().get('Enriching').getRecordTypeId();
            List<Cruise__c> listOfCruise = new List<Cruise__c>();
            List<Cruise__c> listOtherThanFriendOrEnriching = new List<Cruise__c>();
            List<Cruise__c> listOfCruiseToGet = new List<Cruise__c>();
            List<Cruise__c> listOfCruiseToUpdate = new List<Cruise__c>();
            for(Cruise__c crusFrBot: listOfCruiseForBoatSeat){
                if(( (oldmapValues.get(crusFrBot.Id).SCCount__c != crusFrBot.SCCount__c) ) &&  (crusFrBot.recordTypeId ==recTypeIdEnrichingType || crusFrBot.recordTypeId ==recTypeIdFriendsType)){
                                       
                    listOfCruise.add(crusFrBot);
                }
                else if((oldmapValues.get(crusFrBot.Id).maxSeatsFromBoat__c != crusFrBot.maxSeatsFromBoat__c) && (crusFrBot.recordTypeId ==recTypeIdEnrichingType || crusFrBot.recordTypeId ==recTypeIdFriendsType)){
                     listOfCruise.add(crusFrBot);
                    
                }
                
                else if( (oldmapValues.get(crusFrBot.Id).SCCount__c != crusFrBot.SCCount__c) && (crusFrBot.recordTypeId != recTypeIdEnrichingType && crusFrBot.recordTypeId != recTypeIdFriendsType)){
                    listOtherThanFriendOrEnriching.add(crusFrBot);
                }
                else if(((oldmapValues.get(crusFrBot.Id).maxSeatsFromBoat__c != crusFrBot.maxSeatsFromBoat__c) ) && (crusFrBot.recordTypeId != recTypeIdEnrichingType && crusFrBot.recordTypeId != recTypeIdFriendsType)){
                    listOtherThanFriendOrEnriching.add(crusFrBot);
                }
                
               
            }
            if(!listOfCruise.isempty()){
                listOfCruiseToGet = [Select Id,Boat__r.Max_Passenger__c,SCCount__c from Cruise__c where ID IN :listOfCruise];
                for(Cruise__c crs : listOfCruiseToGet){
                    Cruise__c cr = new Cruise__c();
                    cr.Id = crs.Id;
                    if(crs.SCCount__c != null){
                        cr.remainingSeatCalculation__c= (crs.Boat__r.Max_Passenger__c - crs.SCCount__c) -1;
                    }
                    else cr.remainingSeatCalculation__c= (crs.Boat__r.Max_Passenger__c-0) -1;
                    
                    listOfCruiseToUpdate.add(cr);
                }
            }
            else if(!listOtherThanFriendOrEnriching.isEmpty()){
                listOfCruiseToGet = [Select Id,Name,Boat__r.Max_Passenger__c,SCCount__c from Cruise__c where ID IN :listOtherThanFriendOrEnriching];
                for(Cruise__c crs : listOfCruiseToGet){
                    Cruise__c cr = new Cruise__c();
                    cr.Id = crs.Id;
                    if(crs.SCCount__c != null){
                        cr.remainingSeatCalculation__c= (crs.Boat__r.Max_Passenger__c - crs.SCCount__c);
                    }
                    else cr.remainingSeatCalculation__c= (crs.Boat__r.Max_Passenger__c);
                    listOfCruiseToUpdate.add(cr);
                }
            }
            System.debug('listOfCruiseToUpdate >>>>'+listOfCruiseToUpdate);
            if(!listOfCruiseToUpdate.isEmpty() && !Test.isRunningTest()){
                Update listOfCruiseToUpdate; 
            }
        }catch(Exception ex){
            System.debug('Occured error is >>>>>>>'+ex.getMessage()+'At line number >>>>>>'+ex.getLineNumber());
        }
    }
    
     // created by Sameer on 15th Dec 2021.
     // Update the remaingSeatInCruise while creating a new cruise record of Enriching or Friends type.
    public void updateAvailableSeatsInboat(List<Cruise__c> listOfCruiseForBoatSeat){
         try{
            Id recTypeIdFriendsType = Schema.SObjectType.Cruise__c.getRecordTypeInfosByName().get('Friends').getRecordTypeId();
            Id recTypeIdEnrichingType = Schema.SObjectType.Cruise__c.getRecordTypeInfosByName().get('Enriching').getRecordTypeId();
             List<Cruise__c> newListCruiseToUpdate = new List<Cruise__c>();
             List<Cruise__c> newListCruise = [Select Id,RecordTypeId,SCCount__c,remainingSeatCalculation__c,Boat__r.Max_Passenger__c From Cruise__c where ID IN :listOfCruiseForBoatSeat];
             for(Cruise__c crusFrBot: newListCruise){
                 if(crusFrBot.RecordTypeId == recTypeIdFriendsType || crusFrBot.RecordTypeId == recTypeIdEnrichingType){
                     if(crusFrBot.Boat__c != null){
                         crusFrBot.remainingSeatCalculation__c = crusFrBot.Boat__r.Max_Passenger__c -((crusFrBot.SCCount__c != null)? crusFrBot.SCCount__c : 0) -1;
                         newListCruiseToUpdate.add(crusFrBot);
                     }
                 }
                 else {
                      if(crusFrBot.Boat__c != null){
                         crusFrBot.remainingSeatCalculation__c = crusFrBot.Boat__r.Max_Passenger__c -((crusFrBot.SCCount__c != null)? crusFrBot.SCCount__c : 0);
                         newListCruiseToUpdate.add(crusFrBot);
                      }
                 }
                 
             }
             if(!newListCruiseToUpdate.isEmpty() && !Test.isRunningTest()){
                 update newListCruiseToUpdate;
             }
         
         }
        
        catch(Exception ex){
             System.debug('Occured error is >>>>>>>'+ex.getMessage()+'At line number >>>>>>'+ex.getLineNumber());
        }
    } */
    
    public class RecordTypeNotExistException extends Exception {}
}