force-app-modified/main/default/objects/Boats__c/Boats__c.object-meta.xml
<CustomObject>
    <label>סירה</label>
    <nameField>
        <label>שם סירה</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>סירות</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Boats__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>סטטוס פעיל/לא פעיל</label>
    <type>Checkbox</type>
</CustomField>

force-app-modified/main/default/objects/Boats__c/fields/License_Number__c.field-meta.xml
<CustomField>
    <fullName>License_Number__c</fullName>
    <label>ישן</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app-modified/main/default/objects/Boats__c/fields/Max_Passenger__c.field-meta.xml
<CustomField>
    <fullName>Max_Passenger__c</fullName>
    <label>כמות נוסעים מקסימלית</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app-modified/main/default/objects/Boats__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>סוג סירה</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Boat_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Co_Cruise_Members__c/Co_Cruise_Members__c.object-meta.xml
<CustomObject>
    <label>לקוח משנה להפלגה</label>
    <nameField>
        <displayFormat>M-{00000}</displayFormat>
        <label>מספר מפליג משנה</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>לקוחות משנה להפלגה</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app-modified/main/default/objects/Co_Cruise_Members__c/fields/Account_Co__c.field-meta.xml
<CustomField>
    <fullName>Account_Co__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>לקוח</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>לקוחות משנה להפלגה</relationshipLabel>
    <relationshipName>Co_Cruise_Sailres</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Co_Cruise_Members__c/fields/Cruise__c.field-meta.xml
<CustomField>
    <fullName>Cruise__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>הפלגה</label>
    <referenceTo>Cruise__c</referenceTo>
    <relationshipLabel>לקוחות משנה להפלגה</relationshipLabel>
    <relationshipName>Co_Cruise_Sailres</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app-modified/main/default/objects/Co_Cruise_Members__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <formula>Account_Co__r.Email__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Email</label>
    <type>Text</type>
</CustomField>

force-app-modified/main/default/objects/Co_Cruise_Members__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>TEXT(Cruise__r.Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>סטטוס הפלגה</label>
    <type>Text</type>
</CustomField>

force-app-modified/main/default/objects/Co_Cruise_Members__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>עסקה</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>לקוחות משנה להפלגה</relationshipLabel>
    <relationshipName>Co_Cruise_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/Cruise__c.object-meta.xml
<CustomObject>
    <label>הפלגה</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>מספר הפלגה</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>הפלגות</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cruise__c/fields/Additional_Info__c.field-meta.xml
<CustomField>
    <fullName>Additional_Info__c</fullName>
    <label>מידע נוסף למשתתפים</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Cruise__c/fields/Boat__c.field-meta.xml
<CustomField>
    <fullName>Boat__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>סירה</label>
    <referenceTo>Boats__c</referenceTo>
    <relationshipLabel>הפלגות</relationshipLabel>
    <relationshipName>Boat</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cruise__c/fields/Course_Type__c.field-meta.xml
<CustomField>
    <fullName>Course_Type__c</fullName>
    <label>Course Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>קורס 7 מטר</fullName>
            </value>
            <value>
                <fullName>30 קורס משיט</fullName>
            </value>
            <value>
                <fullName>IYT קורס</fullName>
            </value>
            <value>
                <fullName>כללי</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cruise__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>תאריך סיום</label>
    <type>DateTime</type>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/fields/SCCount__c.field-meta.xml
<CustomField>
    <fullName>SCCount__c</fullName>
    <label>SCCount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>תאריך התחלה</label>
    <type>DateTime</type>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>סטטוס</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Guide Matching</fullName>
                <label>לתיאום מדריך</label>
            </value>
            <value>
                <fullName>Awaiting for Approval</fullName>
                <label>ממתינה לאישור</label>
            </value>
            <value>
                <fullName>For Payment</fullName>
                <label>ממתין לתשלום</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
                <label>מבוטלת</label>
            </value>
            <value>
                <fullName>Ready</fullName>
                <label>מוכן להזמנה</label>
            </value>
            <value>
                <fullName>Occupied</fullName>
                <label>תפוס</label>
            </value>
            <value>
                <fullName>No Qualification</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <label>עסקאות</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>הפלגות</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Cruise__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>סוג הסירה</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>מפרשית</fullName>
            </value>
            <value>
                <fullName>יאכטה</fullName>
            </value>
            <value>
                <fullName>קטמרן</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cruise__c/fields/type_of_enriching__c.field-meta.xml
<CustomField>
    <fullName>type_of_enriching__c</fullName>
    <label>סוג מודרכת</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>בית ספר</fullName>
            </value>
            <value>
                <fullName>מועדון</fullName>
            </value>
            <value>
                <fullName>תאוריה</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/recordTypes/Certification.recordType-meta.xml
<RecordType>
    <fullName>Certification</fullName>
    <active>true</active>
    <label>Certification</label>
</RecordType>

force-app-modified/main/default/objects/Cruise__c/recordTypes/Course.recordType-meta.xml
<RecordType>
    <fullName>Course</fullName>
    <active>true</active>
    <label>Course</label>
</RecordType>

force-app-modified/main/default/objects/Cruise__c/recordTypes/Enriching.recordType-meta.xml
<RecordType>
    <fullName>Enriching</fullName>
    <active>true</active>
    <label>Enriching</label>
</RecordType>

force-app-modified/main/default/objects/Cruise__c/recordTypes/Friends.recordType-meta.xml
<RecordType>
    <fullName>Friends</fullName>
    <active>true</active>
    <label>Friends</label>
</RecordType>

force-app-modified/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>עסקה</label>
    <nameField>
        <label>שם עסקה</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>עסקאות</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>שם לקוח</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>עסקאות</relationshipLabel>
    <relationshipName>Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app-modified/main/default/objects/Transaction__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <description>T.A 12-11-2020: it was : IF(TODAY()&gt; End_Date__c , True,False)</description>
    <formula>IF(TODAY()&lt; End_Date__c , True,False)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>פעיל</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Date_of_Transaction__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Transaction__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>תאריך העסקה</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <defaultValue>today()+365</defaultValue>
    <label>תאריך סיום</label>
    <type>Date</type>
</CustomField>

force-app-modified/main/default/objects/Transaction__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <defaultValue>today()</defaultValue>
    <label>תאריך התחלה</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Total_Points__c.field-meta.xml
<CustomField>
    <fullName>Total_Points__c</fullName>
    <label>סה&quot;כ נקודות</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app-modified/main/default/objects/Transaction__c/fields/type_of_membership__c.field-meta.xml
<CustomField>
    <fullName>type_of_membership__c</fullName>
    <label>סוג מנוי</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>חבר מועדון כולל פרטיות</fullName>
            </value>
            <value>
                <fullName>מודרכות בלבד</fullName>
            </value>
            <value>
                <fullName>תלמיד</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app-modified/main/default/objects/Transaction__c/fields/Used_Points__c.field-meta.xml
<CustomField>
    <fullName>Used_Points__c</fullName>
    <defaultValue>0</defaultValue>
    <label>נקודות שנוצלו</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app-modified/main/default/classes/SeatimeSchedulerBookingControllerTest.cls
@isTest
public class SeatimeSchedulerBookingControllerTest {
  @isTest
  static void testSeaTimeSchedulerBookingWithAllCriteriaTrue() {
    try {
      Account testAccount = new Account();
      testAccount.Name = 'Test Account';
      testAccount.Phone = '1234567890';
      testAccount.Email__c = 'abc@gmail.com';
      testAccount.Student7Meter__c = true;
      testAccount.StudentMeshit30__c = false;

      insert testAccount;
      system.debug('accountid:::' + testAccount.id);

      Transaction__c transactionInstance = new Transaction__c();
      transactionInstance.Name = 'Test Transatcion';
      transactionInstance.Start_Date__c = Date.today();
      transactionInstance.End_Date__c = Date.today() + 1;
      transactionInstance.Account_Name__c = testAccount.Id;
      transactionInstance.Date_of_Transaction__c = Date.today();
      transactionInstance.Total_Points__c = 45;
      transactionInstance.Used_Points__c = 5;

      transactionInstance.type_of_membership__c = 'חבר מועדון כולל פרטיות';
    insert transactionInstance;
      system.debug('Transaction:::' + transactionInstance.Id);

      Boats__c boatInstance = new Boats__c();
      boatInstance.Name = 'Test Boat';
      boatInstance.Active__c = true;
      boatInstance.License_Number__c = 234;
      boatInstance.Type__c = 'sailboat';
      boatInstance.Max_Passenger__c = 40;

      insert boatInstance;

      Id recordTypeIdSailEnriching = Schema.SObjectType.Cruise__c.getRecordTypeInfosByDeveloperName()
        .get('Enriching')
        .getRecordTypeId();

      system.debug(
        'recordTypeIdSailEnriching:::: ' + recordTypeIdSailEnriching
      );

      Cruise__c sailInstance1 = new Cruise__c();
      sailInstance1.RecordTypeId = recordTypeIdSailEnriching;
      sailInstance1.Transaction__c = transactionInstance.Id;
      sailInstance1.Boat__c = boatInstance.Id;
      sailInstance1.Start_Date__c = date.today();
      sailInstance1.End_Date__c = Date.today() + 1;
      sailInstance1.Status__c = 'Approved';
      sailInstance1.Additional_Info__c = 'Hello';
      sailInstance1.SCCount__c = 5;

      insert sailInstance1;

      Id recordTypeIdSailFriend = Schema.SObjectType.Cruise__c.getRecordTypeInfosByDeveloperName()
        .get('Friends')
        .getRecordTypeId();

      Cruise__c sailInstance2 = new Cruise__c();
      sailInstance2.RecordTypeId = recordTypeIdSailFriend;
      sailInstance2.Transaction__c = transactionInstance.Id;
      sailInstance2.Boat__c = boatInstance.Id;
      sailInstance2.Start_Date__c = date.today();
      sailInstance2.End_Date__c = Date.today() + 1;
      sailInstance2.Status__c = 'Approved';
      sailInstance2.SCCount__c = 5;

      insert sailInstance2;
      system.debug('sailInstance2:::' + sailInstance2.Id);

      Id recordTypeIdSailCourse = Schema.SObjectType.Cruise__c.getRecordTypeInfosByDeveloperName()
        .get('Course')
        .getRecordTypeId();

      Cruise__c sailInstance3 = new Cruise__c();
      sailInstance3.RecordTypeId = recordTypeIdSailCourse;
      sailInstance3.Transaction__c = transactionInstance.Id;
      sailInstance3.Boat__c = boatInstance.Id;
      sailInstance3.Start_Date__c = date.today();
      sailInstance3.End_Date__c = Date.today() + 1;
      sailInstance3.Status__c = 'Approved';
      sailInstance3.SCCount__c = 5;
      sailInstance3.Course_Type__c = 'קורס 7 מטר';

      insert sailInstance3;
      system.debug('sailInstance3:::' + sailInstance3);

      Id recordTypeIdSailCertification = Schema.SObjectType.Cruise__c.getRecordTypeInfosByDeveloperName()
        .get('Certification')
        .getRecordTypeId();

      Cruise__c sailInstance4 = new Cruise__c();
      sailInstance4.RecordTypeId = recordTypeIdSailCertification;
      sailInstance4.Transaction__c = transactionInstance.Id;
      sailInstance4.Boat__c = boatInstance.Id;
      sailInstance4.Start_Date__c = date.today();
      sailInstance4.End_Date__c = Date.today() + 1;
      sailInstance4.Status__c = 'Approved';
      sailInstance4.SCCount__c = 5;

      insert sailInstance4;
      system.debug('sailInstance4:::' + sailInstance4);

      Test.startTest();

      SeatimeSchedulerBookingController.WrapperController wrappedObj = SeatimeSchedulerBookingController.seaTimeSchedulerBooking(
        testAccount.id
      );
      Test.stopTest();

      Assert.areEqual(
        4,
        wrappedObj.innerWrp.size(),
        'The innerWrp obj should have 4 sail object records'
      );
    } catch (Exception e) {
      system.debug('Message in Test Class::' + e.getMessage());
      system.debug('Line Number in Test Class::' + e.getLineNumber());
    }
  }

  @isTest
  static void testSeaTimeSchedulerBookingWithStudent7MeterFalse() {
    try {
      Account testAccount = new Account();
      testAccount.Name = 'Test Account';
      testAccount.Phone = '1234567890';
      testAccount.Email__c = 'abc@gmail.com';
      testAccount.Student7Meter__c = false;
      testAccount.StudentMeshit30__c = false;

      insert testAccount;
      system.debug('accountid:::' + testAccount.id);

      Transaction__c transactionInstance = new Transaction__c();
      transactionInstance.Name = 'Test Transatcion';
      transactionInstance.Start_Date__c = Date.today();
      transactionInstance.End_Date__c = Date.today() + 1;
      transactionInstance.Account_Name__c = testAccount.Id;
      transactionInstance.Date_of_Transaction__c = Date.today();
      transactionInstance.Total_Points__c = 45;
      transactionInstance.Used_Points__c = 0;

      transactionInstance.type_of_membership__c = 'חבר מועדון כולל פרטיות';
    insert transactionInstance;
      system.debug('Transaction:::' + transactionInstance.Id);

      Boats__c boatInstance = new Boats__c();
      boatInstance.Name = 'Test Boat';
      boatInstance.Active__c = true;
      boatInstance.License_Number__c = 234;
      boatInstance.Type__c = 'sailboat';
      boatInstance.Max_Passenger__c = 40;

      insert boatInstance;

      Id recordTypeIdSailEnriching = Schema.SObjectType.Cruise__c.getRecordTypeInfosByDeveloperName()
        .get('Enriching')
        .getRecordTypeId();

      system.debug(
        'recordTypeIdSailEnriching:::: ' + recordTypeIdSailEnriching
      );

      Cruise__c sailInstance1 = new Cruise__c();
      sailInstance1.RecordTypeId = recordTypeIdSailEnriching;
      sailInstance1.Transaction__c = transactionInstance.Id;
      sailInstance1.Boat__c = boatInstance.Id;
      sailInstance1.Start_Date__c = date.today();
      sailInstance1.End_Date__c = Date.today() + 1;
      sailInstance1.Status__c = 'Approved';
      sailInstance1.Additional_Info__c = 'Hello';
      sailInstance1.SCCount__c = 5;

      insert sailInstance1;

      Id recordTypeIdSailFriend = Schema.SObjectType.Cruise__c.getRecordTypeInfosByDeveloperName()
        .get('Friends')
        .getRecordTypeId();

      Cruise__c sailInstance2 = new Cruise__c();
      sailInstance2.RecordTypeId = recordTypeIdSailFriend;
      sailInstance2.Transaction__c = transactionInstance.Id;
      sailInstance2.Boat__c = boatInstance.Id;
      sailInstance2.Start_Date__c = date.today();
      sailInstance2.End_Date__c = Date.today() + 1;
      sailInstance2.Status__c = 'Approved';
      sailInstance2.SCCount__c = 5;

      insert sailInstance2;
      system.debug('sailInstance2:::' + sailInstance2.Id);

      Id recordTypeIdSailCourse = Schema.SObjectType.Cruise__c.getRecordTypeInfosByDeveloperName()
        .get('Course')
        .getRecordTypeId();

      Cruise__c sailInstance3 = new Cruise__c();
      sailInstance3.RecordTypeId = recordTypeIdSailCourse;
      sailInstance3.Transaction__c = transactionInstance.Id;
      sailInstance3.Boat__c = boatInstance.Id;
      sailInstance3.Start_Date__c = date.today();
      sailInstance3.End_Date__c = Date.today() + 1;
      sailInstance3.Status__c = 'Approved';
      sailInstance3.SCCount__c = 5;
      sailInstance3.Course_Type__c = 'קורס 7 מטר';

      insert sailInstance3;
      system.debug('sailInstance3:::' + sailInstance3);

      Id recordTypeIdSailCertification = Schema.SObjectType.Cruise__c.getRecordTypeInfosByDeveloperName()
        .get('Certification')
        .getRecordTypeId();

      Cruise__c sailInstance4 = new Cruise__c();
      sailInstance4.RecordTypeId = recordTypeIdSailCertification;
      sailInstance4.Transaction__c = transactionInstance.Id;
      sailInstance4.Boat__c = boatInstance.Id;
      sailInstance4.Start_Date__c = date.today();
      sailInstance4.End_Date__c = Date.today() + 1;
      sailInstance4.Status__c = 'Approved';
      sailInstance4.SCCount__c = 5;

      insert sailInstance4;
      system.debug('sailInstance4:::' + sailInstance4);

      Test.startTest();

      SeatimeSchedulerBookingController.WrapperController wrappedObj = SeatimeSchedulerBookingController.seaTimeSchedulerBooking(
        testAccount.id
      );
      Test.stopTest();

      Assert.areEqual(
        3,
        wrappedObj.innerWrp.size(),
        'The innerWrp obj should have 3 sail object records'
      );
    } catch (Exception e) {
      system.debug('Message in Test Class::' + e.getMessage());
      system.debug('Line Number in Test Class::' + e.getLineNumber());
    }
  }
  @isTest
  static void testSeaTimeSchedulerBookingWithStudent7MeterTrue() {
    try {
      Account testAccount = new Account();
      testAccount.Name = 'Test Account';
      testAccount.Phone = '1234567890';
      testAccount.Email__c = 'abc@gmail.com';
      testAccount.Student7Meter__c = true;
      testAccount.StudentMeshit30__c = false;

      insert testAccount;
      system.debug('accountid:::' + testAccount.id);

      Transaction__c transactionInstance = new Transaction__c();
      transactionInstance.Name = 'Test Transatcion';
      transactionInstance.Start_Date__c = Date.today();
      transactionInstance.End_Date__c = Date.today() + 1;
      transactionInstance.Account_Name__c = testAccount.Id;
      transactionInstance.Date_of_Transaction__c = Date.today();
      transactionInstance.Total_Points__c = 45;
      transactionInstance.Used_Points__c = 40;

      transactionInstance.type_of_membership__c = 'חבר מועדון כולל פרטיות';
    insert transactionInstance;
      system.debug('Transaction:::' + transactionInstance.Id);

      Boats__c boatInstance = new Boats__c();
      boatInstance.Name = 'Test Boat';
      boatInstance.Active__c = true;
      boatInstance.License_Number__c = 234;
      boatInstance.Type__c = 'sailboat';
      boatInstance.Max_Passenger__c = 40;

      insert boatInstance;

      Id recordTypeIdSailEnriching = Schema.SObjectType.Cruise__c.getRecordTypeInfosByDeveloperName()
        .get('Enriching')
        .getRecordTypeId();

      system.debug(
        'recordTypeIdSailEnriching:::: ' + recordTypeIdSailEnriching
      );

      Cruise__c sailInstance1 = new Cruise__c();
      sailInstance1.RecordTypeId = recordTypeIdSailEnriching;
      sailInstance1.Transaction__c = transactionInstance.Id;
      sailInstance1.Boat__c = boatInstance.Id;
      sailInstance1.Start_Date__c = date.today();
      sailInstance1.End_Date__c = Date.today() + 1;
      sailInstance1.Status__c = 'Approved';
      sailInstance1.Additional_Info__c = 'Hello';
      sailInstance1.SCCount__c = 5;

      insert sailInstance1;

      Id recordTypeIdSailFriend = Schema.SObjectType.Cruise__c.getRecordTypeInfosByDeveloperName()
        .get('Friends')
        .getRecordTypeId();

      Cruise__c sailInstance2 = new Cruise__c();
      sailInstance2.RecordTypeId = recordTypeIdSailFriend;
      sailInstance2.Transaction__c = transactionInstance.Id;
      sailInstance2.Boat__c = boatInstance.Id;
      sailInstance2.Start_Date__c = date.today();
      sailInstance2.End_Date__c = Date.today() + 1;
      sailInstance2.Status__c = 'Approved';
      sailInstance2.SCCount__c = 5;

      insert sailInstance2;
      system.debug('sailInstance2:::' + sailInstance2.Id);

      Id recordTypeIdSailCourse = Schema.SObjectType.Cruise__c.getRecordTypeInfosByDeveloperName()
        .get('Course')
        .getRecordTypeId();

      Cruise__c sailInstance3 = new Cruise__c();
      sailInstance3.RecordTypeId = recordTypeIdSailCourse;
      sailInstance3.Transaction__c = transactionInstance.Id;
      sailInstance3.Boat__c = boatInstance.Id;
      sailInstance3.Start_Date__c = date.today();
      sailInstance3.End_Date__c = Date.today() + 1;
      sailInstance3.Status__c = 'Approved';
      sailInstance3.SCCount__c = 5;
      sailInstance3.Course_Type__c = 'קורס 7 מטר';

      insert sailInstance3;
      system.debug('sailInstance3:::' + sailInstance3);

      Id recordTypeIdSailCertification = Schema.SObjectType.Cruise__c.getRecordTypeInfosByDeveloperName()
        .get('Certification')
        .getRecordTypeId();

      Cruise__c sailInstance4 = new Cruise__c();
      sailInstance4.RecordTypeId = recordTypeIdSailCertification;
      sailInstance4.Transaction__c = transactionInstance.Id;
      sailInstance4.Boat__c = boatInstance.Id;
      sailInstance4.Start_Date__c = date.today();
      sailInstance4.End_Date__c = Date.today() + 1;
      sailInstance4.Status__c = 'Approved';
      sailInstance4.SCCount__c = 5;

      insert sailInstance4;
      system.debug('sailInstance4:::' + sailInstance4);

      Test.startTest();

      SeatimeSchedulerBookingController.WrapperController wrappedObj = SeatimeSchedulerBookingController.seaTimeSchedulerBooking(
        testAccount.id
      );
      Test.stopTest();

      Assert.areEqual(
        1,
        wrappedObj.innerWrp.size(),
        'The innerWrp obj should have 1 sail object records'
      );
    } catch (Exception e) {
      system.debug('Message in Test Class::' + e.getMessage());
      system.debug('Line Number in Test Class::' + e.getLineNumber());
    }
  }

  @isTest
  static void testSeaTimeSchedulerBookingWithTxnPointsLessThanThirty() {
    try {
      Account testAccount = new Account();
      testAccount.Name = 'Test Account';
      testAccount.Phone = '1234567890';
      testAccount.Email__c = 'abc@gmail.com';
      testAccount.Student7Meter__c = true;
      testAccount.StudentMeshit30__c = false;

      insert testAccount;
      system.debug('accountid:::' + testAccount.id);

      Transaction__c transactionInstance = new Transaction__c();
      transactionInstance.Name = 'Test Transatcion';
      transactionInstance.Start_Date__c = Date.today();
      transactionInstance.End_Date__c = Date.today() + 1;
      transactionInstance.Account_Name__c = testAccount.Id;
      transactionInstance.Date_of_Transaction__c = Date.today();
      transactionInstance.Total_Points__c = 45;
      transactionInstance.Used_Points__c = 40;

      transactionInstance.type_of_membership__c = 'חבר מועדון כולל פרטיות';
    insert transactionInstance;
      system.debug('Transaction:::' + transactionInstance.Id);

      Boats__c boatInstance = new Boats__c();
      boatInstance.Name = 'Test Boat';
      boatInstance.Active__c = true;
      boatInstance.License_Number__c = 234;
      boatInstance.Type__c = 'sailboat';
      boatInstance.Max_Passenger__c = 40;

      insert boatInstance;

      Id recordTypeIdSailEnriching = Schema.SObjectType.Cruise__c.getRecordTypeInfosByDeveloperName()
        .get('Enriching')
        .getRecordTypeId();

      system.debug(
        'recordTypeIdSailEnriching:::: ' + recordTypeIdSailEnriching
      );

      Cruise__c sailInstance1 = new Cruise__c();
      sailInstance1.RecordTypeId = recordTypeIdSailEnriching;
      sailInstance1.Transaction__c = transactionInstance.Id;
      sailInstance1.Boat__c = boatInstance.Id;
      sailInstance1.Start_Date__c = date.today();
      sailInstance1.End_Date__c = Date.today() + 1;
      sailInstance1.Status__c = 'Approved';
      sailInstance1.Additional_Info__c = 'Hello';
      sailInstance1.SCCount__c = 5;

      insert sailInstance1;

      Id recordTypeIdSailFriend = Schema.SObjectType.Cruise__c.getRecordTypeInfosByDeveloperName()
        .get('Friends')
        .getRecordTypeId();

      Cruise__c sailInstance2 = new Cruise__c();
      sailInstance2.RecordTypeId = recordTypeIdSailFriend;
      sailInstance2.Transaction__c = transactionInstance.Id;
      sailInstance2.Boat__c = boatInstance.Id;
      sailInstance2.Start_Date__c = date.today();
      sailInstance2.End_Date__c = Date.today() + 1;
      sailInstance2.Status__c = 'Approved';
      sailInstance2.SCCount__c = 5;

      insert sailInstance2;
      system.debug('sailInstance2:::' + sailInstance2.Id);

      Id recordTypeIdSailCourse = Schema.SObjectType.Cruise__c.getRecordTypeInfosByDeveloperName()
        .get('Course')
        .getRecordTypeId();

      Cruise__c sailInstance3 = new Cruise__c();
      sailInstance3.RecordTypeId = recordTypeIdSailCourse;
      sailInstance3.Transaction__c = transactionInstance.Id;
      sailInstance3.Boat__c = boatInstance.Id;
      sailInstance3.Start_Date__c = date.today();
      sailInstance3.End_Date__c = Date.today() + 1;
      sailInstance3.Status__c = 'Approved';
      sailInstance3.SCCount__c = 5;
      sailInstance3.Course_Type__c = 'קורס 7 מטר';

      insert sailInstance3;
      system.debug('sailInstance3:::' + sailInstance3);

      Id recordTypeIdSailCertification = Schema.SObjectType.Cruise__c.getRecordTypeInfosByDeveloperName()
        .get('Certification')
        .getRecordTypeId();

      Cruise__c sailInstance4 = new Cruise__c();
      sailInstance4.RecordTypeId = recordTypeIdSailCertification;
      sailInstance4.Transaction__c = transactionInstance.Id;
      sailInstance4.Boat__c = boatInstance.Id;
      sailInstance4.Start_Date__c = date.today();
      sailInstance4.End_Date__c = Date.today() + 1;
      sailInstance4.Status__c = 'Approved';
      sailInstance4.SCCount__c = 5;

      insert sailInstance4;
      system.debug('sailInstance4:::' + sailInstance4);

      Test.startTest();

      SeatimeSchedulerBookingController.WrapperController wrappedObj = SeatimeSchedulerBookingController.seaTimeSchedulerBooking(
        testAccount.id
      );
      Test.stopTest();

      Assert.areEqual(
        1,
        wrappedObj.innerWrp.size(),
        'The innerWrp obj should have 1 sail object records'
      );
    } catch (Exception e) {
      system.debug('Message in Test Class::' + e.getMessage());
      system.debug('Line Number in Test Class::' + e.getLineNumber());
    }
  }

  @isTest
  static void testSeaTimeSchedulerBookingWithStudentMeshit30True() {
    try {
      Account testAccount = new Account();
      testAccount.Name = 'Test Account';
      testAccount.Phone = '1234567890';
      testAccount.Email__c = 'abc@gmail.com';
      testAccount.Student7Meter__c = true;
      testAccount.StudentMeshit30__c = true;

      insert testAccount;
      system.debug('accountid:::' + testAccount.id);

      Transaction__c transactionInstance = new Transaction__c();
      transactionInstance.Name = 'Test Transatcion';
      transactionInstance.Start_Date__c = Date.today();
      transactionInstance.End_Date__c = Date.today() + 1;
      transactionInstance.Account_Name__c = testAccount.Id;
      transactionInstance.Date_of_Transaction__c = Date.today();
      transactionInstance.Total_Points__c = 45;
      transactionInstance.Used_Points__c = 40;

      transactionInstance.type_of_membership__c = 'חבר מועדון כולל פרטיות';
    insert transactionInstance;
      system.debug('Transaction:::' + transactionInstance.Id);

      Boats__c boatInstance = new Boats__c();
      boatInstance.Name = 'Test Boat';
      boatInstance.Active__c = true;
      boatInstance.License_Number__c = 234;
      boatInstance.Type__c = 'sailboat';
      boatInstance.Max_Passenger__c = 40;

      insert boatInstance;

      Id recordTypeIdSailEnriching = Schema.SObjectType.Cruise__c.getRecordTypeInfosByDeveloperName()
        .get('Enriching')
        .getRecordTypeId();

      system.debug(
        'recordTypeIdSailEnriching:::: ' + recordTypeIdSailEnriching
      );

      Cruise__c sailInstance1 = new Cruise__c();
      sailInstance1.RecordTypeId = recordTypeIdSailEnriching;
      sailInstance1.Transaction__c = transactionInstance.Id;
      sailInstance1.Boat__c = boatInstance.Id;
      sailInstance1.Start_Date__c = date.today();
      sailInstance1.End_Date__c = Date.today() + 1;
      sailInstance1.Status__c = 'Approved';
      sailInstance1.Additional_Info__c = 'Hello';
      sailInstance1.SCCount__c = 5;

      insert sailInstance1;

      Id recordTypeIdSailFriend = Schema.SObjectType.Cruise__c.getRecordTypeInfosByDeveloperName()
        .get('Friends')
        .getRecordTypeId();

      Cruise__c sailInstance2 = new Cruise__c();
      sailInstance2.RecordTypeId = recordTypeIdSailFriend;
      sailInstance2.Transaction__c = transactionInstance.Id;
      sailInstance2.Boat__c = boatInstance.Id;
      sailInstance2.Start_Date__c = date.today();
      sailInstance2.End_Date__c = Date.today() + 1;
      sailInstance2.Status__c = 'Approved';
      sailInstance2.SCCount__c = 5;

      insert sailInstance2;
      system.debug('sailInstance2:::' + sailInstance2.Id);

      Id recordTypeIdSailCourse = Schema.SObjectType.Cruise__c.getRecordTypeInfosByDeveloperName()
        .get('Course')
        .getRecordTypeId();

      Cruise__c sailInstance3 = new Cruise__c();
      sailInstance3.RecordTypeId = recordTypeIdSailCourse;
      sailInstance3.Transaction__c = transactionInstance.Id;
      sailInstance3.Boat__c = boatInstance.Id;
      sailInstance3.Start_Date__c = date.today();
      sailInstance3.End_Date__c = Date.today() + 1;
      sailInstance3.Status__c = 'Approved';
      sailInstance3.SCCount__c = 5;
      sailInstance3.Course_Type__c = 'קורס 7 מטר';

      insert sailInstance3;
      system.debug('sailInstance3:::' + sailInstance3);

      Id recordTypeIdSailCertification = Schema.SObjectType.Cruise__c.getRecordTypeInfosByDeveloperName()
        .get('Certification')
        .getRecordTypeId();

      Cruise__c sailInstance4 = new Cruise__c();
      sailInstance4.RecordTypeId = recordTypeIdSailCertification;
      sailInstance4.Transaction__c = transactionInstance.Id;
      sailInstance4.Boat__c = boatInstance.Id;
      sailInstance4.Start_Date__c = date.today();
      sailInstance4.End_Date__c = Date.today() + 1;
      sailInstance4.Status__c = 'Approved';
      sailInstance4.SCCount__c = 5;

      insert sailInstance4;
      system.debug('sailInstance4:::' + sailInstance4);

      Test.startTest();

      SeatimeSchedulerBookingController.WrapperController wrappedObj = SeatimeSchedulerBookingController.seaTimeSchedulerBooking(
        testAccount.id
      );
      Test.stopTest();

      Assert.areEqual(
        3,
        wrappedObj.innerWrp.size(),
        'The innerWrp obj should have 3 sail object records'
      );
    } catch (Exception e) {
      system.debug('Message in Test Class::' + e.getMessage());
      system.debug('Line Number in Test Class::' + e.getLineNumber());
    }
  }

  @isTest
  static void testSeaTimeSchedulerBookingWithAllCriteriaFalse() {
    try {
      Account testAccount = new Account();
      testAccount.Name = 'Test Account';
      testAccount.Phone = '1234567890';
      testAccount.Email__c = 'abc@gmail.com';
      testAccount.Student7Meter__c = false;
      testAccount.StudentMeshit30__c = false;

      insert testAccount;
      system.debug('accountid:::' + testAccount.id);

      Transaction__c transactionInstance = new Transaction__c();
      transactionInstance.Name = 'Test Transatcion';
      transactionInstance.Start_Date__c = Date.today();
      transactionInstance.End_Date__c = Date.today() + 1;
      transactionInstance.Account_Name__c = testAccount.Id;
      transactionInstance.Date_of_Transaction__c = Date.today();
      transactionInstance.Total_Points__c = 45;
      transactionInstance.Used_Points__c = 40;

      transactionInstance.type_of_membership__c = 'חבר מועדון כולל פרטיות';
    insert transactionInstance;
      system.debug('Transaction:::' + transactionInstance.Id);

      Boats__c boatInstance = new Boats__c();
      boatInstance.Name = 'Test Boat';
      boatInstance.Active__c = true;
      boatInstance.License_Number__c = 234;
      boatInstance.Type__c = 'sailboat';
      boatInstance.Max_Passenger__c = 40;

      insert boatInstance;

      Id recordTypeIdSailEnriching = Schema.SObjectType.Cruise__c.getRecordTypeInfosByDeveloperName()
        .get('Enriching')
        .getRecordTypeId();

      system.debug(
        'recordTypeIdSailEnriching:::: ' + recordTypeIdSailEnriching
      );

      Cruise__c sailInstance1 = new Cruise__c();
      sailInstance1.RecordTypeId = recordTypeIdSailEnriching;
      sailInstance1.Transaction__c = transactionInstance.Id;
      sailInstance1.Boat__c = boatInstance.Id;
      sailInstance1.Start_Date__c = date.today();
      sailInstance1.End_Date__c = Date.today() + 1;
      sailInstance1.Status__c = 'Approved';
      sailInstance1.Additional_Info__c = 'Hello';
      sailInstance1.SCCount__c = 5;

      insert sailInstance1;

      Id recordTypeIdSailFriend = Schema.SObjectType.Cruise__c.getRecordTypeInfosByDeveloperName()
        .get('Friends')
        .getRecordTypeId();

      Cruise__c sailInstance2 = new Cruise__c();
      sailInstance2.RecordTypeId = recordTypeIdSailFriend;
      sailInstance2.Transaction__c = transactionInstance.Id;
      sailInstance2.Boat__c = boatInstance.Id;
      sailInstance2.Start_Date__c = date.today();
      sailInstance2.End_Date__c = Date.today() + 1;
      sailInstance2.Status__c = 'Approved';
      sailInstance2.SCCount__c = 5;

      insert sailInstance2;
      system.debug('sailInstance2:::' + sailInstance2.Id);

      Id recordTypeIdSailCourse = Schema.SObjectType.Cruise__c.getRecordTypeInfosByDeveloperName()
        .get('Course')
        .getRecordTypeId();

      Cruise__c sailInstance3 = new Cruise__c();
      sailInstance3.RecordTypeId = recordTypeIdSailCourse;
      sailInstance3.Transaction__c = transactionInstance.Id;
      sailInstance3.Boat__c = boatInstance.Id;
      sailInstance3.Start_Date__c = date.today();
      sailInstance3.End_Date__c = Date.today() + 1;
      sailInstance3.Status__c = 'Approved';
      sailInstance3.SCCount__c = 5;
      sailInstance3.Course_Type__c = 'קורס 7 מטר';

      insert sailInstance3;
      system.debug('sailInstance3:::' + sailInstance3);

      Id recordTypeIdSailCertification = Schema.SObjectType.Cruise__c.getRecordTypeInfosByDeveloperName()
        .get('Certification')
        .getRecordTypeId();

      Cruise__c sailInstance4 = new Cruise__c();
      sailInstance4.RecordTypeId = recordTypeIdSailCertification;
      sailInstance4.Transaction__c = transactionInstance.Id;
      sailInstance4.Boat__c = boatInstance.Id;
      sailInstance4.Start_Date__c = date.today();
      sailInstance4.End_Date__c = Date.today() + 1;
      sailInstance4.Status__c = 'Approved';
      sailInstance4.SCCount__c = 5;

      insert sailInstance4;
      system.debug('sailInstance4:::' + sailInstance4);

      Test.startTest();

      SeatimeSchedulerBookingController.WrapperController wrappedObj = SeatimeSchedulerBookingController.seaTimeSchedulerBooking(
        testAccount.id
      );
      Test.stopTest();

      Assert.areEqual(
        0,
        wrappedObj.innerWrp.size(),
        'The innerWrp obj should have 0 sail object records'
      );
    } catch (Exception e) {
      system.debug('Message in Test Class::' + e.getMessage());
      system.debug('Line Number in Test Class::' + e.getLineNumber());
    }
  }

  @isTest
  static void testInsertSubCustomers() {
    Account testAccount = new Account();
    testAccount.Name = 'Test Account';
    testAccount.Phone = '1234567890';
    testAccount.Email__c = 'abc@gmail.com';

    insert testAccount;

    Transaction__c transactionInstance = new Transaction__c();
    transactionInstance.Name = 'Test Transatcion';
    transactionInstance.Start_Date__c = Date.today();
    transactionInstance.End_Date__c = Date.today() + 1;
    transactionInstance.Account_Name__c = testAccount.Id;
    transactionInstance.Date_of_Transaction__c = Date.today();
    transactionInstance.Total_Points__c = 45;
    transactionInstance.Used_Points__c = 5;

    transactionInstance.type_of_membership__c = 'חבר מועדון כולל פרטיות';
    insert transactionInstance;

    Boats__c boatInstance = new Boats__c();
    boatInstance.Name = 'Test Boat';
    boatInstance.Active__c = true;
    boatInstance.License_Number__c = 234;
    boatInstance.Type__c = 'sailboat';
    boatInstance.Max_Passenger__c = 40;

    insert boatInstance;

    Id recordTypeIdSailEnriching = Schema.SObjectType.Cruise__c.getRecordTypeInfosByDeveloperName()
      .get('Enriching')
      .getRecordTypeId();

    Cruise__c sailInstance = new Cruise__c();
    sailInstance.RecordTypeId = recordTypeIdSailEnriching;
    sailInstance.Transaction__c = transactionInstance.Id;
    sailInstance.type_of_enriching__c = 'מועדון';
    sailInstance.Boat__c = boatInstance.Id;
    sailInstance.Start_Date__c = date.today();
    sailInstance.End_Date__c = Date.today() + 1;
    sailInstance.Status__c = 'Approved';
    sailInstance.Additional_Info__c = 'Hello';
    sailInstance.SCCount__c = 5;

    insert sailInstance;

    Test.startTest();
    SeatimeSchedulerBookingController.WrapperController wrappedObj = SeatimeSchedulerBookingController.seaTimeSchedulerBooking(
      testAccount.Id
    );
    SeatimeSchedulerBookingController.insertSubCustomers(
      sailInstance.Id,
      wrappedObj.innerWrp[0].sailStartMonthYear,
      (String) testAccount.Id
    );
    Test.stopTest();

    List<Co_Cruise_Members__c> ccm = [
      SELECT Id, Account_Co__c, Cruise__c
      FROM Co_Cruise_Members__c
      WHERE Account_Co__c = :testAccount.Id
      WITH SYSTEM_MODE
    ];

    Assert.areEqual(
      1,
      ccm.size(),
      'There should be one Co_Cruise_Members__c record'
    );

    Assert.areEqual(
      testAccount.Id,
      ccm[0].Account_Co__c,
      'Account of Co_Cruise_Members__c record is not correct'
    );

    Assert.areEqual(
      sailInstance.Id,
      ccm[0].Cruise__c,
      'The sail for Co_Cruise_Members__c is not correct'
    );
  }
}