force-app-modified/main/default/objects/Boats__c/Boats__c.object-meta.xml
<CustomObject>
    <label>סירה</label>
    <nameField>
        <label>שם סירה</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>סירות</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Boats__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>סטטוס פעיל/לא פעיל</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Boats__c/fields/BoatsSchedulerOrder__c.field-meta.xml
<CustomField>
    <fullName>BoatsSchedulerOrder__c</fullName>
    <label>סדר במתזמן</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app-modified/main/default/objects/Boats__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>סוג סירה</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Boat_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Co_Cruise_Members__c/Co_Cruise_Members__c.object-meta.xml
<CustomObject>
    <label>לקוח משנה להפלגה</label>
    <nameField>
        <displayFormat>M-{00000}</displayFormat>
        <label>מספר מפליג משנה</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>לקוחות משנה להפלגה</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app-modified/main/default/objects/Co_Cruise_Members__c/fields/Account_Co__c.field-meta.xml
<CustomField>
    <fullName>Account_Co__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>לקוח</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>לקוחות משנה להפלגה</relationshipLabel>
    <relationshipName>Co_Cruise_Sailres</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Co_Cruise_Members__c/fields/Cruise__c.field-meta.xml
<CustomField>
    <fullName>Cruise__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>הפלגה</label>
    <referenceTo>Cruise__c</referenceTo>
    <relationshipLabel>לקוחות משנה להפלגה</relationshipLabel>
    <relationshipName>Co_Cruise_Sailres</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app-modified/main/default/objects/Co_Cruise_Members__c/fields/day__c.field-meta.xml
<CustomField>
    <fullName>day__c</fullName>
    <formula>DATEVALUE(Date__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>day</label>
    <type>Date</type>
</CustomField>

force-app-modified/main/default/objects/Co_Cruise_Members__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <formula>Account_Co__r.Phone</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>טלפון</label>
    <type>Text</type>
</CustomField>

force-app-modified/main/default/objects/Co_Cruise_Members__c/fields/SailType__c.field-meta.xml
<CustomField>
    <fullName>SailType__c</fullName>
    <formula>Cruise__r.RecordType.DeveloperName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>סוג הפלגה</label>
    <type>Text</type>
</CustomField>

force-app-modified/main/default/objects/Co_Cruise_Members__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>TEXT(Cruise__r.Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>סטטוס הפלגה</label>
    <type>Text</type>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/Cruise__c.object-meta.xml
<CustomObject>
    <label>הפלגה</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>מספר הפלגה</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>הפלגות</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app-modified/main/default/objects/Cruise__c/fields/AccountName__c.field-meta.xml
<CustomField>
    <fullName>AccountName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>שם לקוח</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>הפלגות</relationshipLabel>
    <relationshipName>Cruises</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cruise__c/fields/Additional_Info__c.field-meta.xml
<CustomField>
    <fullName>Additional_Info__c</fullName>
    <label>מידע נוסף למשתתפים</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Cruise__c/fields/Boat__c.field-meta.xml
<CustomField>
    <fullName>Boat__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>סירה</label>
    <referenceTo>Boats__c</referenceTo>
    <relationshipLabel>הפלגות</relationshipLabel>
    <relationshipName>Boat</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cruise__c/fields/Course_Type__c.field-meta.xml
<CustomField>
    <fullName>Course_Type__c</fullName>
    <label>Course Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>קורס 7 מטר</fullName>
            </value>
            <value>
                <fullName>30 קורס משיט</fullName>
            </value>
            <value>
                <fullName>IYT קורס</fullName>
            </value>
            <value>
                <fullName>כללי</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cruise__c/fields/cruise_time_formula__c.field-meta.xml
<CustomField>
    <fullName>cruise_time_formula__c</fullName>
    <formula>RIGHT(&quot;0&quot; &amp; TEXT(HOUR(TIMEVALUE(Start_Date__c + (3/24)))), 2) &amp;
&quot;:&quot; &amp;
RIGHT(&quot;0&quot; &amp; TEXT(MINUTE(TIMEVALUE(Start_Date__c + (3/24)))), 2) &amp;
&quot;-&quot; &amp;
RIGHT(&quot;0&quot; &amp; TEXT(HOUR(TIMEVALUE(End_Date__c + (3/24)))), 2) &amp;
&quot;:&quot; &amp;
RIGHT(&quot;0&quot; &amp; TEXT(MINUTE(TIMEVALUE(End_Date__c + (3/24)))), 2)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>שעות הפלגה (נוסחה)</label>
    <type>Text</type>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/fields/CUSTOMER_NAME__c.field-meta.xml
<CustomField>
    <fullName>CUSTOMER_NAME__c</fullName>
    <label>שם לקוח</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/fields/CUSTOMER_PHONE__c.field-meta.xml
<CustomField>
    <fullName>CUSTOMER_PHONE__c</fullName>
    <label>טלפון לקוח</label>
    <type>Phone</type>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/fields/day__c.field-meta.xml
<CustomField>
    <fullName>day__c</fullName>
    <formula>DATEVALUE( Start_Date__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>day</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Cruise__c/fields/Employee_Email__c.field-meta.xml
<CustomField>
    <fullName>Employee_Email__c</fullName>
    <label>אימייל מדריך</label>
    <type>Email</type>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/fields/Employee_Phone__c.field-meta.xml
<CustomField>
    <fullName>Employee_Phone__c</fullName>
    <label>טלפון מדריך</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cruise__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>תאריך סיום</label>
    <type>DateTime</type>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/fields/Guide__c.field-meta.xml
<CustomField>
    <fullName>Guide__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>מדריך להפלגה</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>הפלגות</relationshipLabel>
    <relationshipName>Guide_to_cruise</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/fields/information__c.field-meta.xml
<CustomField>
    <fullName>information__c</fullName>
    <label>מידע פנימי נוסף</label>
    <length>256</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Cruise__c/fields/Skipper__c.field-meta.xml
<CustomField>
    <fullName>Skipper__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Skipper</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>הפלגות (Skipper)</relationshipLabel>
    <relationshipName>Cruise</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>תאריך התחלה</label>
    <type>DateTime</type>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>סטטוס</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Guide Matching</fullName>
                <label>לתיאום מדריך</label>
            </value>
            <value>
                <fullName>Awaiting for Approval</fullName>
                <label>ממתינה לאישור</label>
            </value>
            <value>
                <fullName>For Payment</fullName>
                <label>ממתין לתשלום</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
                <label>מבוטלת</label>
            </value>
            <value>
                <fullName>Ready</fullName>
                <label>מוכן להזמנה</label>
            </value>
            <value>
                <fullName>Occupied</fullName>
                <label>תפוס</label>
            </value>
            <value>
                <fullName>No Qualification</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cruise__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>סוג הסירה</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>מפרשית</fullName>
            </value>
            <value>
                <fullName>יאכטה</fullName>
            </value>
            <value>
                <fullName>קטמרן</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cruise__c/fields/type_of_enriching__c.field-meta.xml
<CustomField>
    <fullName>type_of_enriching__c</fullName>
    <label>סוג מודרכת</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>בית ספר</fullName>
            </value>
            <value>
                <fullName>מועדון</fullName>
            </value>
            <value>
                <fullName>תאוריה</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>מדריך</label>
    <nameField>
        <label>שם המדריך</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>מדריכים</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <label>מדריך פעיל</label>
    <type>Checkbox</type>
    <defaultValue>true</defaultValue>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Employee_Email__c.field-meta.xml
<CustomField>
    <fullName>Employee_Email__c</fullName>
    <label>מייל מדריך</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Employee_Phone__c.field-meta.xml
<CustomField>
    <fullName>Employee_Phone__c</fullName>
    <label>טלפון</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Employee_Type__c.field-meta.xml
<CustomField>
    <fullName>Employee_Type__c</fullName>
    <label>סוג שכר</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>שעתי</fullName>
                <default>true</default>
                <label>שעתי</label>
            </value>
            <value>
                <fullName>חודשי</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/StaffPortalController.cls
public without sharing class StaffPortalController {

    @AuraEnabled(cacheable=true)
    public static List<Cruise__c> getDailyCruises(Date selectedDate) {
        if (selectedDate == null) {
            selectedDate = Date.today();
        }
        DateTime dayStart = DateTime.newInstance(selectedDate, Time.newInstance(0, 0, 0, 0));
        DateTime dayEnd = DateTime.newInstance(selectedDate.addDays(1), Time.newInstance(0, 0, 0, 0));
        
        return [SELECT Id, Name, Boat__c, Boat__r.Name, Boat__r.BoatsSchedulerOrder__c, Start_Date__c, End_Date__c, 
                       Status__c, RecordType.Name, RecordType.DeveloperName, Guide__r.Name, Employee_Phone__c, 
                       Employee_Email__c, CUSTOMER_NAME__c, CUSTOMER_PHONE__c, Additional_Info__c, AccountName__r.Name, 
                       Skipper__r.Name, Course_Type__c, type_of_enriching__c, information__c 
                FROM Cruise__c 
                WHERE Start_Date__c >= :dayStart AND Start_Date__c < :dayEnd AND Status__c != 'Canceled' 
                ORDER BY Boat__r.BoatsSchedulerOrder__c, Start_Date__c];
    }

    @AuraEnabled(cacheable=true)
    public static List<Cruise__c> getGuideCruises(Id employeeId) {
        if (employeeId == null) {
            return new List<Cruise__c>();
        }
        Date today = Date.today();
        DateTime startOfToday = DateTime.newInstance(today, Time.newInstance(0, 0, 0, 0));
        return [SELECT Id, Name, Start_Date__c, End_Date__c, Boat__r.Name, RecordType.Name, RecordType.DeveloperName, Additional_Info__c, 
                       Status__c, day__c, cruise_time_formula__c, CUSTOMER_NAME__c, CUSTOMER_PHONE__c, information__c 
                FROM Cruise__c 
                WHERE Guide__c = :employeeId AND Guide__c != null AND Status__c != 'Canceled' AND Start_Date__c >= :startOfToday 
                ORDER BY Start_Date__c ASC];
    }

    @AuraEnabled(cacheable=true)
    public static List<Co_Cruise_Members__c> getCruiseParticipants(Id cruiseId) {
        if (cruiseId == null) {
            return new List<Co_Cruise_Members__c>();
        }
        return [SELECT Id, Account_Co__r.Name, Phone__c, Status__c, SailType__c 
                FROM Co_Cruise_Members__c 
                WHERE Cruise__c = :cruiseId AND Status__c != 'Canceled' 
                ORDER BY Account_Co__r.Name];
    }

    @AuraEnabled(cacheable=true)
    public static List<Boats__c> getActiveBoats() {
        return [SELECT Id, Name, Type__c, BoatsSchedulerOrder__c 
                FROM Boats__c 
                WHERE Active__c = true 
                ORDER BY BoatsSchedulerOrder__c];
    }

    @AuraEnabled(cacheable=true)
    public static Employee__c getEmployeeDetails(Id employeeId) {
        if (employeeId == null) return null;
        List<Employee__c> emps = [SELECT Id, Name, Employee_Type__c, Active__c FROM Employee__c WHERE Id = :employeeId LIMIT 1];
        return emps.isEmpty() ? null : emps[0];
    }
}