force-app-modified/main/default/objects/Boats__c/Boats__c.object-meta.xml
<CustomObject>
    <label>סירה</label>
    <nameField>
        <label>שם סירה</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>סירות</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Boats__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>סטטוס פעיל/לא פעיל</label>
    <type>Checkbox</type>
</CustomField>

force-app-modified/main/default/objects/Boats__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>סוג סירה</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Boat_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Certification__c/Certification__c.object-meta.xml
<CustomObject>
    <label>הסמכה</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>שם הסמכה</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>הסמכות</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Certification__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>שם הלקוח</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>הסמכות</relationshipLabel>
    <relationshipName>Account_Name</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app-modified/main/default/objects/Certification__c/fields/Boat__c.field-meta.xml
<CustomField>
    <fullName>Boat__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>סירה</label>
    <referenceTo>Boats__c</referenceTo>
    <relationshipLabel>הסמכות</relationshipLabel>
    <relationshipName>Certified_boat</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app-modified/main/default/objects/Certification__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <defaultValue>today()</defaultValue>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/Cruise__c.object-meta.xml
<CustomObject>
    <label>הפלגה</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>מספר הפלגה</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>הפלגות</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app-modified/main/default/objects/Cruise__c/fields/AccountName__c.field-meta.xml
<CustomField>
    <fullName>AccountName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>שם לקוח</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>הפלגות</relationshipLabel>
    <relationshipName>Cruises</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cruise__c/fields/Boat__c.field-meta.xml
<CustomField>
    <fullName>Boat__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>סירה</label>
    <referenceTo>Boats__c</referenceTo>
    <relationshipLabel>הפלגות</relationshipLabel>
    <relationshipName>Boat</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cruise__c/fields/DATE__c.field-meta.xml
<CustomField>
    <fullName>DATE__c</fullName>
    <label>DATE</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Cruise__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>תאריך סיום</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Cruise__c/fields/MaxParticipants__c.field-meta.xml
<CustomField>
    <fullName>MaxParticipants__c</fullName>
    <defaultValue>if ( $RecordType.DeveloperName  == &apos;Enriching&apos;,7,if($RecordType.DeveloperName  == &apos;Course&apos;,3, If($RecordType.DeveloperName  == &apos;Certification&apos;,3,If ($RecordType.DeveloperName  == &apos;Friends&apos;,8,0))))</defaultValue>
    <label>מספר משתתפים מקסימלי</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/fields/SCCount__c.field-meta.xml
<CustomField>
    <fullName>SCCount__c</fullName>
    <label>SCCount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>תאריך התחלה</label>
    <type>DateTime</type>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>סטטוס</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Guide Matching</fullName>
                <label>לתיאום מדריך</label>
            </value>
            <value>
                <fullName>Awaiting for Approval</fullName>
                <label>ממתינה לאישור</label>
            </value>
            <value>
                <fullName>For Payment</fullName>
                <label>ממתין לתשלום</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
                <label>מבוטלת</label>
            </value>
            <value>
                <fullName>Ready</fullName>
                <label>מוכן להזמנה</label>
            </value>
            <value>
                <fullName>Occupied</fullName>
                <label>תפוס</label>
            </value>
            <value>
                <fullName>No Qualification</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <label>עסקאות</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>הפלגות</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Cruise__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>סוג הסירה</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>מפרשית</fullName>
            </value>
            <value>
                <fullName>יאכטה</fullName>
            </value>
            <value>
                <fullName>קטמרן</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/recordTypes/Certification.recordType-meta.xml
<RecordType>
    <fullName>Certification</fullName>
    <active>true</active>
    <label>Certification</label>
</RecordType>

force-app-modified/main/default/objects/Cruise__c/recordTypes/Club.recordType-meta.xml
<RecordType>
    <fullName>Club</fullName>
    <active>true</active>
    <label>Club</label>
</RecordType>

force-app-modified/main/default/objects/Cruise__c/recordTypes/Course.recordType-meta.xml
<RecordType>
    <fullName>Course</fullName>
    <active>true</active>
    <label>Course</label>
</RecordType>

force-app-modified/main/default/objects/Cruise__c/recordTypes/Enriching.recordType-meta.xml
<RecordType>
    <fullName>Enriching</fullName>
    <active>true</active>
    <label>Enriching</label>
</RecordType>

force-app-modified/main/default/objects/PriceList__c/PriceList__c.object-meta.xml
<CustomObject>
    <label>מחירון</label>
    <nameField>
        <label>שם מחירון</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>מחירון</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PriceList__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>תעריף ברירת מחדל</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app-modified/main/default/objects/PriceList__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>תאריך התחלה</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app-modified/main/default/objects/PriceList__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>סוג</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>רגיל</fullName>
                <default>true</default>
                <label>רגיל</label>
            </value>
            <value>
                <fullName>מבצע</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app-modified/main/default/objects/PriceListLine__c/PriceListLine__c.object-meta.xml
<CustomObject>
    <label>שורת מחירון</label>
    <nameField>
        <displayFormat>PLL-{0}</displayFormat>
        <label>שם שורת מחירון</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PriceListLines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app-modified/main/default/objects/PriceListLine__c/fields/Boat__c.field-meta.xml
<CustomField>
    <fullName>Boat__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>סירה</label>
    <referenceTo>Boats__c</referenceTo>
    <relationshipLabel>PriceListLines</relationshipLabel>
    <relationshipName>PriceListLines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PriceListLine__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>תעריף</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PriceListLine__c/fields/PriceList__c.field-meta.xml
<CustomField>
    <fullName>PriceList__c</fullName>
    <label>מחירון</label>
    <referenceTo>PriceList__c</referenceTo>
    <relationshipLabel>PriceListLines</relationshipLabel>
    <relationshipName>PriceListLines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PriceListLine__c/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <defaultValue>TIMEVALUE(&apos;00:00:00.000&apos;)</defaultValue>
    <label>שעת התחלה</label>
    <required>true</required>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/PriceListLine__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>סוג</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Abroad</fullName>
                <isActive>false</isActive>
                <label>Abroad</label>
            </value>
            <value>
                <fullName>Course</fullName>
                <isActive>false</isActive>
                <label>Course</label>
            </value>
            <value>
                <fullName>General</fullName>
                <isActive>false</isActive>
                <label>General</label>
            </value>
            <value>
                <fullName>Introduction</fullName>
                <isActive>false</isActive>
                <label>Introduction</label>
            </value>
            <value>
                <fullName>Maintenance</fullName>
                <isActive>false</isActive>
                <label>Maintenance</label>
            </value>
            <value>
                <fullName>Renting</fullName>
                <isActive>false</isActive>
                <label>Renting</label>
            </value>
            <value>
                <fullName>Certification</fullName>
                <label>הסמכה</label>
            </value>
            <value>
                <fullName>Friends</fullName>
                <label>חברים</label>
            </value>
            <value>
                <fullName>Enriching</fullName>
                <label>מודרכת</label>
            </value>
            <value>
                <fullName>Club</fullName>
                <default>true</default>
                <label>מועדון</label>
            </value>
            <value>
                <fullName>Renewal</fullName>
                <label>ריענון</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app-modified/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>עסקה</label>
    <nameField>
        <label>שם עסקה</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>עסקאות</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>שם לקוח</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>עסקאות</relationshipLabel>
    <relationshipName>Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app-modified/main/default/objects/Transaction__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <description>T.A 12-11-2020: it was : IF(TODAY()&gt; End_Date__c , True,False)</description>
    <formula>IF(TODAY()&lt; End_Date__c , True,False)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>פעיל</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Date_of_Transaction__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Transaction__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>תאריך העסקה</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <defaultValue>today()+365</defaultValue>
    <label>תאריך סיום</label>
    <type>Date</type>
</CustomField>

force-app-modified/main/default/objects/Transaction__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <defaultValue>today()</defaultValue>
    <label>תאריך התחלה</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Total_Points__c.field-meta.xml
<CustomField>
    <fullName>Total_Points__c</fullName>
    <label>סה&quot;כ נקודות</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app-modified/main/default/objects/Transaction__c/fields/type_of_membership__c.field-meta.xml
<CustomField>
    <fullName>type_of_membership__c</fullName>
    <label>סוג מנוי</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>חבר מועדון כולל פרטיות</fullName>
            </value>
            <value>
                <fullName>מודרכות בלבד</fullName>
            </value>
            <value>
                <fullName>תלמיד</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SeaTimeAppTest.cls
/**
 * @description
 * @author Ceptes
 * @date Wednesday-August-14-2024
 **/

 @isTest
public class SeaTimeAppTest {

    @TestSetup
    static void createSeaTimeAppTestData() {
        
        Account accountData  = new Account();
        accountData.Name     = 'Test Account'; 
        accountData.Phone    = '123456'; 
        accountData.Email__c = 'gs650x@gmail.com';
        accountData.code__c  = '1234';
        insert accountData;

        Boats__c boat  = new Boats__c();
        boat.Name      = 'boat 1';
        boat.Type__c   = 'Yacht';
        boat.Active__c = true;
        insert boat;

        Transaction__c transactionData  = new Transaction__c();
        transactionData.Total_Points__c = 3000;
        transactionData.Account_Name__c = accountData.Id;
        transactionData.End_Date__c     = Date.today().addDays(1);
        transactionData.Date_of_Transaction__c = Date.today();
        transactionData.type_of_membership__c = 'חבר מועדון כולל פרטיות';
        insert transactionData;

        Certification__c certification    = new Certification__c();
        certification.Account_Name__c     = accountData.Id;
        certification.Boat__c             = boat.Id;
        certification.Date__c             = Date.today().addDays(1);
        certification.Expiration_Date__c  = Date.today().addDays(30);  
        certification.Boat__c             = boat.Id;
        insert certification;

        //Id clubRecordTypeId = Schema.SObjectType.Cruise__c.getRecordTypeInfosByName().get('Club').getRecordTypeId();

        Cruise__c cruise      = new Cruise__c();
        cruise.Boat__c        = boat.Id;
        cruise.recordTypeId   = '0120Y00000073ApQAI'/*clubRecordTypeId*/;
        cruise.Start_Date__c  = Date.Today().addDays(1);
        cruise.End_Date__c    = Date.Today().addDays(2);
        cruise.Transaction__c = transactionData.Id;
        cruise.Status__c      = 'Awaiting for Approval';
        cruise.AccountName__c = accountData.Id;
        cruise.SCCount__c     = 5;
        cruise.MaxParticipants__c  = 10;
        insert cruise;
        
        PriceList__c priceList = new PriceList__c(Name='בדיקה יונתן ',End_Date__c=Date.valueOf('2025-09-03'),Start_Date__c = Date.valueOf('2024-09-03') ,Type__c='רגיל',Price__c = 2);
        insert priceList;
        
         List<PriceListLine__c> priceLinelist = new List<PriceListLine__c>();
        Id boatId = getBoatId();
        
        priceLinelist.add(new PriceListLine__c(
            Price__c = 21.3,
            Boat__c = boatId,
            Type__c = 'Certification',
            PriceList__c = priceList.Id
        ));
        
        priceLinelist.add(new PriceListLine__c(
            Price__c = 21.3,
            Type__c = 'Enriching',
            PriceList__c = priceList.Id
        ));
        insert priceLinelist;
    }

    @isTest
    static void testLoginPage() {

        Map<String, string> userCredentials = new Map<String, string>{
            'userName' => 'gs650x@gmail.com',
            'password' => '123456'
        };

        Map<string, object> validCredsData = LoginPageAppController.isValidCredentials(userCredentials);

        Assert.isNotNull(validCredsData);

        id accountId = getAccountId();

        Map<string, object> validOtpData = LoginPageAppController.isValidOtp(accountId, '1234');

        Assert.isNotNull(validOtpData);
    }

    @isTest
    static void testHomePage() {

        id accountId = getAccountId();

        Map<string, object> homePageData = HomePageController.getHomePageTabsData(accountId);

        Assert.isNotNull(homePageData);
    }

    @isTest
    static void testPrivateReservationPage() {

        Map<String, object> searchData = new Map<String, object>{
            'boatTypes' => new List<string>{'Yacht'},
            'date' => String.valueOf(Date.today())
        };

        Map<String, object> privateReservationData = PrivateReservationPageController.getPrivateReservationData(searchData);

        Assert.isNotNull(privateReservationData);

        id accountId = getAccountId();
        id boatId    = getBoatId();

        Map<String, object> selectedBoat = new Map<String, object>{
            'startTime' => '10:12',
            'endTime' =>  '10:22',
            'date' => '2024-04-04',
            'boatId' => boatId,
            'accountId' => accountId
        };

        Id cruiseId = PrivateReservationPageController.createPrivateReservation(selectedBoat);

        Assert.isNotNull(cruiseId);

        Transaction__c trans = [SELECT Id FROM Transaction__c LIMIT 1];
        String result = PrivateReservationPageController.generateAndSendClubContract(trans.Id);
        Assert.areEqual('SUCCESS', result);
    }

    @isTest
    static void testClubCruisepage() {

        id boatId    = getBoatId();
        id accountId = getAccountId();
        id cruiseId  = getCruiseId();
        String startDate ='2024-09-03T07:00:00.000Z';

        List<PriceListLine__c> PriceListLineList = getPriceListLineList();
                                         
        List<Object> clubCruisesArray = (List<Object>)JSON.deserializeUntyped('[{"id":"' + cruiseId + '", "accountId": "' + accountId + '","recordTypeName":"Certification","boatId": "' + boatId + '","boatName":"Rosie","boatType":"Yacht","startDate":"' + startDate + '","endTime":"' + startDate + '"},{"id":"' + cruiseId + '", "accountId": "' + accountId + '","recordTypeName":"Enriching","boatId": "' + boatId + '","boatName":"Rosie","boatType":"Yacht","startDate":"' + startDate + '","endTime":"' + startDate + '"},{"id":"' + cruiseId + '", "accountId": "' + accountId + '","recordTypeName":"Enriching","boatId": "' + boatId + '","boatName":"Rosie","boatType":"Yacht","startDate":"' + startDate + '","endTime":"' + startDate + '"},{"id":"' + cruiseId + '","recordTypeName":"Course","boatId": "' + boatId + '","boatName":"Rosie","boatType":"Yacht","startDate":"' + startDate + '","endTime":"' + startDate + '"}]');

        ClubCruisesPageController.getClubCruisePrices(JSON.serialize(clubCruisesArray));

        Map<String, object> selectedCruise = new Map<String, object>{
            'id' => cruiseId,
            'accountId' => accountId
        };

        Boolean isCoCruiseMemberCreated = ClubCruisesPageController.createCoCruiseMember(selectedCruise);

        Assert.areEqual(true, isCoCruiseMemberCreated);
    }

    static Id getCruiseId() {
        return [SELECT id FROM Cruise__c LIMIT 1]?.Id;
    }

    static Id getAccountId() {
        return [SELECT id FROM Account LIMIT 1]?.Id;
    }

    static Id getBoatId() {
        return [SELECT id FROM Boats__c LIMIT 1]?.Id;
    }
    
    static List<PriceListLine__c> getPriceListLineList() {
        return [SELECT id, Price__c, Start__c,Type__c, Boat__c,
                                             PriceList__r.Start_Date__c,PriceList__r.End_Date__c FROM 
                                             PriceListLine__c WHERE Type__c != 'Club' AND PriceList__r.Start_Date__c <=: Date.valueOf('2024-09-03') AND
                                             PriceList__r.End_Date__c >=: Date.valueOf('2024-09-03') ORDER BY PriceList__r.CreatedDate];
    }
}