force-app-modified/main/default/objects/Boats__c/Boats__c.object-meta.xml
<CustomObject>
    <label>סירה</label>
    <nameField>
        <label>שם סירה</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>סירות</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app-modified/main/default/objects/Boats__c/fields/License_Number__c.field-meta.xml
<CustomField>
    <fullName>License_Number__c</fullName>
    <label>ישן</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app-modified/main/default/objects/Boats__c/fields/Max_Passenger__c.field-meta.xml
<CustomField>
    <fullName>Max_Passenger__c</fullName>
    <label>כמות נוסעים מקסימלית</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app-modified/main/default/objects/Boats__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>סוג סירה</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Boat_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Co_Cruise_Members__c/Co_Cruise_Members__c.object-meta.xml
<CustomObject>
    <label>לקוח משנה להפלגה</label>
    <nameField>
        <displayFormat>M-{00000}</displayFormat>
        <label>מספר מפליג משנה</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>לקוחות משנה להפלגה</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Co_Cruise_Members__c/fields/Cruise__c.field-meta.xml
<CustomField>
    <fullName>Cruise__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>הפלגה</label>
    <referenceTo>Cruise__c</referenceTo>
    <relationshipLabel>לקוחות משנה להפלגה</relationshipLabel>
    <relationshipName>Co_Cruise_Sailres</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app-modified/main/default/objects/Co_Cruise_Members__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <formula>Account_Co__r.Email__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Email</label>
    <type>Text</type>
</CustomField>

force-app-modified/main/default/objects/Co_Cruise_Members__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>TEXT(Cruise__r.Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>סטטוס הפלגה</label>
    <type>Text</type>
</CustomField>

force-app-modified/main/default/objects/Co_Cruise_Members__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>עסקה</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>לקוחות משנה להפלגה</relationshipLabel>
    <relationshipName>Co_Cruise_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/Cruise__c.object-meta.xml
<CustomObject>
    <label>הפלגה</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>מספר הפלגה</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>הפלגות</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app-modified/main/default/objects/Cruise__c/fields/AccountName__c.field-meta.xml
<CustomField>
    <fullName>AccountName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>שם לקוח</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>הפלגות</relationshipLabel>
    <relationshipName>Cruises</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cruise__c/fields/Boat__c.field-meta.xml
<CustomField>
    <fullName>Boat__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>סירה</label>
    <referenceTo>Boats__c</referenceTo>
    <relationshipLabel>הפלגות</relationshipLabel>
    <relationshipName>Boat</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cruise__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>תאריך סיום</label>
    <type>DateTime</type>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/fields/Holiday__c.field-meta.xml
<CustomField>
    <fullName>Holiday__c</fullName>
    <defaultValue>false</defaultValue>
    <label>חגים ומועדים</label>
    <type>Checkbox</type>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>תאריך התחלה</label>
    <type>DateTime</type>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>סטטוס</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Guide Matching</fullName>
                <label>לתיאום מדריך</label>
            </value>
            <value>
                <fullName>Awaiting for Approval</fullName>
                <label>ממתינה לאישור</label>
            </value>
            <value>
                <fullName>For Payment</fullName>
                <label>ממתין לתשלום</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
                <label>מבוטלת</label>
            </value>
            <value>
                <fullName>Ready</fullName>
                <label>מוכן להזמנה</label>
            </value>
            <value>
                <fullName>Occupied</fullName>
                <label>תפוס</label>
            </value>
            <value>
                <fullName>No Qualification</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <label>עסקאות</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>הפלגות</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Cruise__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>סוג הסירה</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>מפרשית</fullName>
            </value>
            <value>
                <fullName>יאכטה</fullName>
            </value>
            <value>
                <fullName>קטמרן</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/recordTypes/Club.recordType-meta.xml
<RecordType>
    <fullName>Club</fullName>
    <active>true</active>
    <label>Club</label>
</RecordType>

force-app-modified/main/default/objects/PriceList__c/PriceList__c.object-meta.xml
<CustomObject>
    <label>מחירון</label>
    <nameField>
        <label>שם מחירון</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>מחירון</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PriceList__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>תעריף ברירת מחדל</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app-modified/main/default/objects/PriceList__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>תאריך התחלה</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app-modified/main/default/objects/PriceList__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>סוג</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>רגיל</fullName>
                <default>true</default>
                <label>רגיל</label>
            </value>
            <value>
                <fullName>מבצע</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app-modified/main/default/objects/PriceListLine__c/PriceListLine__c.object-meta.xml
<CustomObject>
    <label>שורת מחירון</label>
    <nameField>
        <displayFormat>PLL-{0}</displayFormat>
        <label>שם שורת מחירון</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PriceListLines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app-modified/main/default/objects/PriceListLine__c/fields/Boat__c.field-meta.xml
<CustomField>
    <fullName>Boat__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>סירה</label>
    <referenceTo>Boats__c</referenceTo>
    <relationshipLabel>PriceListLines</relationshipLabel>
    <relationshipName>PriceListLines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app-modified/main/default/objects/PriceListLine__c/fields/Global__c.field-meta.xml
<CustomField>
    <fullName>Global__c</fullName>
    <defaultValue>false</defaultValue>
    <label>גלובלי</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PriceListLine__c/fields/HPrice__c.field-meta.xml
<CustomField>
    <fullName>HPrice__c</fullName>
    <label>תעריף חג</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PriceListLine__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>תעריף</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PriceListLine__c/fields/PriceList__c.field-meta.xml
<CustomField>
    <fullName>PriceList__c</fullName>
    <label>מחירון</label>
    <referenceTo>PriceList__c</referenceTo>
    <relationshipLabel>PriceListLines</relationshipLabel>
    <relationshipName>PriceListLines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PriceListLine__c/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <defaultValue>TIMEVALUE(&apos;00:00:00.000&apos;)</defaultValue>
    <label>שעת התחלה</label>
    <required>true</required>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/PriceListLine__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>סוג</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Abroad</fullName>
                <isActive>false</isActive>
                <label>Abroad</label>
            </value>
            <value>
                <fullName>Course</fullName>
                <isActive>false</isActive>
                <label>Course</label>
            </value>
            <value>
                <fullName>General</fullName>
                <isActive>false</isActive>
                <label>General</label>
            </value>
            <value>
                <fullName>Introduction</fullName>
                <isActive>false</isActive>
                <label>Introduction</label>
            </value>
            <value>
                <fullName>Maintenance</fullName>
                <isActive>false</isActive>
                <label>Maintenance</label>
            </value>
            <value>
                <fullName>Renting</fullName>
                <isActive>false</isActive>
                <label>Renting</label>
            </value>
            <value>
                <fullName>Certification</fullName>
                <label>הסמכה</label>
            </value>
            <value>
                <fullName>Friends</fullName>
                <label>חברים</label>
            </value>
            <value>
                <fullName>Enriching</fullName>
                <label>מודרכת</label>
            </value>
            <value>
                <fullName>Club</fullName>
                <default>true</default>
                <label>מועדון</label>
            </value>
            <value>
                <fullName>Renewal</fullName>
                <label>ריענון</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app-modified/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>עסקה</label>
    <nameField>
        <label>שם עסקה</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>עסקאות</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>שם לקוח</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>עסקאות</relationshipLabel>
    <relationshipName>Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Date_of_Transaction__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Transaction__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>תאריך העסקה</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <defaultValue>today()+365</defaultValue>
    <label>תאריך סיום</label>
    <type>Date</type>
</CustomField>

force-app-modified/main/default/objects/Transaction__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <defaultValue>today()</defaultValue>
    <label>תאריך התחלה</label>
    <type>Date</type>
</CustomField>

force-app-modified/main/default/objects/Transaction__c/fields/type_of_membership__c.field-meta.xml
<CustomField>
    <fullName>type_of_membership__c</fullName>
    <label>סוג מנוי</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>חבר מועדון כולל פרטיות</fullName>
            </value>
            <value>
                <fullName>מודרכות בלבד</fullName>
            </value>
            <value>
                <fullName>תלמיד</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app-modified/main/default/objects/Transaction__c/recordTypes/Subscription.recordType-meta.xml
<RecordType>
    <fullName>Subscription</fullName>
    <active>false</active>
    <label>Subscription</label>
</RecordType>

force-app/main/default/classes/SeaTimeControllerTest.cls
/**
 * @description App controller subscription page
 * @author Ceptes
 * @date Thursday-July-04-2024
 **/


@isTest
public class SeaTimeControllerTest {
    
    @TestSetup
    static void createSeaTimeAppTestData() {
        account acc = new account(Name='Account record', phone='1234',Email__c='Account@gmail.com');
        insert acc;
        
        Transaction__c sub = new Transaction__c(Name='Boat',Account_Name__c=acc.Id,
                                                         Date_of_Transaction__c=system.today(),Start_Date__c=system.today(),
                                                         End_Date__c=system.today(), type_of_membership__c = 'חבר מועדון כולל פרטיות');
        insert sub;
        Boats__c boat = new Boats__c(Name='Rosie',License_Number__c = 123,Max_Passenger__c=10);
        insert boat;
        Cruise__c cruise = new Cruise__c( Transaction__c=sub.Id,Boat__c	= boat.Id, Start_Date__c=system.today(),End_Date__c=system.today(),AccountName__c=acc.Id,status__c='For Payment',Holiday__c = true);
        insert cruise;
        List<PriceList__c> priceListRecList = new List<PriceList__c>();
        PriceList__c priceListRec = new PriceList__c(Type__c = 'רגיל',Start_Date__c=system.today(),End_Date__c = system.today(),Price__c=2.00);
        PriceList__c priceListRec1 = new PriceList__c(Type__c = 'מבצע',Start_Date__c=system.today(),End_Date__c = system.today(),Price__c=2.00);
        priceListRecList.add(priceListRec);
        priceListRecList.add(priceListRec1);
        insert priceListRecList;
         List<PriceListLine__c> priceListLineList = new List<PriceListLine__c>();   
        PriceListLine__c plLineRec = new PriceListLine__c(Start__c = Time.newInstance(20, 20, 20, 20),PriceList__c= priceListRecList[0].Id,Type__c='Club',Boat__c = boat.Id,Price__c=20,HPrice__c=200,Global__c = false);
        PriceListLine__c plLineRec2 = new PriceListLine__c(Start__c = Time.newInstance(10, 10, 10, 10),PriceList__c= priceListRecList[1].Id,Type__c='Club',Boat__c = boat.Id,Price__c=20,HPrice__c=200,Global__c = false);
		priceListLineList.add(plLineRec);
        priceListLineList.add(plLineRec2);
        insert priceListLineList;
        //Co_Cruise_Members__c cmember = new Co_Cruise_Members__c(Cruise__c=cruise.Id,Transaction__c=sub.Id,Account_Co__c=acc.Id);
    }
	@isTest
    public static void getSubscriptionDetailsTest(){
       account acc = [Select id,name,phone,Email__c from account limit 1];
       Cruise__c cruise = [Select id,Transaction__c,Boat__c,Start_Date__c,End_Date__c,AccountName__c,status__c from Cruise__c limit 1];
        Test.startTest();
        SeaTimeController.getSubscriptionDetails(String.valueOf(acc.Id));
        try{
        SeaTimeController.updateCruiseStatus(cruise.Id);
        SeaTimeController.updateCruiseStatus('');
        PrivateReservationPageController.getTransactionFromAccount(acc.Id);
        }catch(exception e){
            system.debug(e.getMessage());
        }
        Test.stopTest();
    }
   @isTest
    public static void calculateCruisePriceTest(){
       List<Cruise__c> cruiseList = [Select id,Transaction__c,Boat__c,Start_Date__c,End_Date__c,AccountName__c,status__c,Holiday__c from Cruise__c ];
       List<PriceListLine__c> priceListLineRec = [select id, Start__c, Type__c, Boat__c, Price__c, HPrice__c, Global__c from PriceListLine__c];
		List < PriceList__c > dispricelists = [select id, Type__c, Start_Date__c, End_Date__c, Price__c, (select id, Start__c, Type__c, Boat__c, Price__c, HPrice__c, Global__c from PriceListLines__r
                                                                                                          Order by Start__c) from PriceList__c Where Type__c = 'מבצע'
                                               Order by Start_Date__c DESC];

        Test.startTest();
        for(Cruise__c cr:cruiseList){
			SeaTimeController.calculateCruisePrice(cr);            
        }
        
        Test.stopTest();
    }
    @isTest
    public static void calculateCruisePriceTest2(){
        Cruise__c cruise = [Select id,Transaction__c,Boat__c,Start_Date__c,End_Date__c,AccountName__c,status__c,Holiday__c from Cruise__c limit 1];
        List<PriceListLine__c> priceListLineRec = [select id, Start__c, Type__c, Boat__c, Price__c, HPrice__c, Global__c from PriceListLine__c];
        for(PriceListLine__c plLine:priceListLineRec){
            plLine.Boat__c = null;
        }

        update priceListLineRec;
        List < PriceList__c > regpricelists = [select id, Type__c, Start_Date__c, End_Date__c, Price__c, (select id, Start__c, Type__c, Boat__c, Price__c, HPrice__c, Global__c from PriceListLines__r
                                                                                                          Order by Start__c) from PriceList__c Where Type__c = 'רגיל'
                                               Order by Start_Date__c DESC
                                              ];
        Test.startTest();
        SeaTimeController.calculateCruisePrice(cruise);
        Test.stopTest();
    }

    @isTest
    public static void cancelCoCruiseMemberTest() {
        Transaction__c sub = [SELECT Id FROM Transaction__c LIMIT 1];
        account acc = [SELECT Id FROM account LIMIT 1];
        Boats__c boat = [SELECT Id FROM Boats__c LIMIT 1];

        Cruise__c cruise = new Cruise__c(Transaction__c=sub.Id, Boat__c=boat.Id, Start_Date__c=System.today().addDays(5), End_Date__c=System.today().addDays(5), AccountName__c=acc.Id, status__c='Approved');
        insert cruise;

        Co_Cruise_Members__c member = new Co_Cruise_Members__c(Cruise__c=cruise.Id, Transaction__c=sub.Id, Account_Co__c=acc.Id);
        insert member;

        Test.startTest();
        SeaTimeController.cancelCoCruiseMember(member.Id);
        Test.stopTest();
    }

    @isTest
    public static void cancelCoCruiseSailresTest() {
        Transaction__c sub = [SELECT Id FROM Transaction__c LIMIT 1];
        account acc = [SELECT Id FROM account LIMIT 1];
        Cruise__c cruise = [SELECT Id FROM Cruise__c LIMIT 1];
        cruise.Start_Date__c = System.today().addDays(5);
        update cruise;

        Co_Cruise_Members__c sailres = new Co_Cruise_Members__c(Cruise__c=cruise.Id, Transaction__c=sub.Id, Account_Co__c=acc.Id);
        insert sailres;

        Test.startTest();
        SeaTimeController.cancelCoCruiseSailres(sailres.Id);
        Test.stopTest();
    }
}