force-app-modified/main/default/objects/Boats__c/Boats__c.object-meta.xml
<CustomObject>
    <label>סירה</label>
    <nameField>
        <label>שם סירה</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>סירות</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Boats__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>סטטוס פעיל/לא פעיל</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Boats__c/fields/BoatsSchedulerOrder__c.field-meta.xml
<CustomField>
    <fullName>BoatsSchedulerOrder__c</fullName>
    <label>סדר במתזמן</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/Cruise__c.object-meta.xml
<CustomObject>
    <label>הפלגה</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>מספר הפלגה</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>הפלגות</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app-modified/main/default/objects/Cruise__c/fields/AccountName__c.field-meta.xml
<CustomField>
    <fullName>AccountName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>שם לקוח</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>הפלגות</relationshipLabel>
    <relationshipName>Cruises</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cruise__c/fields/Additional_Info__c.field-meta.xml
<CustomField>
    <fullName>Additional_Info__c</fullName>
    <label>מידע נוסף למשתתפים</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Cruise__c/fields/Boat__c.field-meta.xml
<CustomField>
    <fullName>Boat__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>סירה</label>
    <referenceTo>Boats__c</referenceTo>
    <relationshipLabel>הפלגות</relationshipLabel>
    <relationshipName>Boat</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cruise__c/fields/Co_Cruise__c.field-meta.xml
<CustomField>
    <fullName>Co_Cruise__c</fullName>
    <defaultValue>false</defaultValue>
    <label>הפלגה חברתית</label>
    <type>Checkbox</type>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/fields/Cruise_Purpose__c.field-meta.xml
<CustomField>
    <fullName>Cruise_Purpose__c</fullName>
    <label>מטרה</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Leisure and Fun</fullName>
                <label>פנאי וכיף</label>
            </value>
            <value>
                <fullName>Challenge</fullName>
                <label>אתגרי</label>
            </value>
            <value>
                <fullName>Training</fullName>
                <label>אימון</label>
            </value>
            <value>
                <fullName>Couples</fullName>
                <label>זוגות</label>
            </value>
            <value>
                <fullName>Children</fullName>
                <label>ילדים</label>
            </value>
            <value>
                <fullName>Fishing</fullName>
                <label>דייג</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cruise__c/fields/Decline_Reason__c.field-meta.xml
<CustomField>
    <fullName>Decline_Reason__c</fullName>
    <label>סיבת דחיה</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/fields/Employee_Phone__c.field-meta.xml
<CustomField>
    <fullName>Employee_Phone__c</fullName>
    <label>טלפון מדריך</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cruise__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>תאריך סיום</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Cruise__c/fields/Extra_Hours_Charge__c.field-meta.xml
<CustomField>
    <fullName>Extra_Hours_Charge__c</fullName>
    <label>Extra Hours Charge</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/fields/Guide__c.field-meta.xml
<CustomField>
    <fullName>Guide__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>מדריך להפלגה</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>הפלגות</relationshipLabel>
    <relationshipName>Guide_to_cruise</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/fields/Hidden_Additional_Hours__c.field-meta.xml
<CustomField>
    <fullName>Hidden_Additional_Hours__c</fullName>
    <label>שדה עזר תוספת שעות</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cruise__c/fields/Hidden_Total_Hours__c.field-meta.xml
<CustomField>
    <fullName>Hidden_Total_Hours__c</fullName>
    <formula>(floor(( End_Date__c - Start_Date__c )*24)) 
+ 

ROUND(MOD((End_Date__c - Start_Date__c)*1440,60),0)/60
+ 

Extra_Hours_Charge__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>סה&quot;כ שעות הפלגה</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/fields/Holiday__c.field-meta.xml
<CustomField>
    <fullName>Holiday__c</fullName>
    <defaultValue>false</defaultValue>
    <label>חגים ומועדים</label>
    <type>Checkbox</type>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/fields/information__c.field-meta.xml
<CustomField>
    <fullName>information__c</fullName>
    <label>מידע פנימי נוסף</label>
    <length>256</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Cruise__c/fields/key_location__c.field-meta.xml
<CustomField>
    <fullName>key_location__c</fullName>
    <formula>Boat__r.KEY__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>key location</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cruise__c/fields/Marina__c.field-meta.xml
<CustomField>
    <fullName>Marina__c</fullName>
    <formula>TEXT(Boat__r.Docking__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>מרינה</label>
    <type>Text</type>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/fields/Payment_Required__c.field-meta.xml
<CustomField>
    <fullName>Payment_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>דרוש תשלום</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Cruise__c/fields/pier__c.field-meta.xml
<CustomField>
    <fullName>pier__c</fullName>
    <formula>Boat__r.DOCK__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>pier</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cruise__c/fields/skill_level__c.field-meta.xml
<CustomField>
    <fullName>skill_level__c</fullName>
    <formula>text(AccountName__r.skill_level__c)</formula>
    <inlineHelpText>רמת הפלגה</inlineHelpText>
    <label>skill level</label>
    <type>Text</type>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>תאריך התחלה</label>
    <type>DateTime</type>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>סטטוס</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Guide Matching</fullName>
                <label>לתיאום מדריך</label>
            </value>
            <value>
                <fullName>Awaiting for Approval</fullName>
                <label>ממתינה לאישור</label>
            </value>
            <value>
                <fullName>For Payment</fullName>
                <label>ממתין לתשלום</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
                <label>מבוטלת</label>
            </value>
            <value>
                <fullName>Ready</fullName>
                <label>מוכן להזמנה</label>
            </value>
            <value>
                <fullName>Occupied</fullName>
                <label>תפוס</label>
            </value>
            <value>
                <fullName>No Qualification</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cruise__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>נושא</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/fields/Total_Cruise_of_Transaction__c.field-meta.xml
<CustomField>
    <fullName>Total_Cruise_of_Transaction__c</fullName>
    <formula>IF( Transaction__r.RecordType.DeveloperName&lt;&gt;&apos;Points&apos;, Transaction__r.Remaining_hours__c,0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>סה&quot;כ שעות הפלגה מהעסקה</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/fields/Type2__c.field-meta.xml
<CustomField>
    <fullName>Type2__c</fullName>
    <formula>TEXT(  Boat__r.Type__c  )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>סוג</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>מדריך</label>
    <nameField>
        <label>שם המדריך</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>מדריכים</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <label>מדריך פעיל</label>
    <type>Checkbox</type>
    <defaultValue>true</defaultValue>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Employee_Phone__c.field-meta.xml
<CustomField>
    <fullName>Employee_Phone__c</fullName>
    <label>טלפון</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/BoatsSchedulerService.cls
public class BoatsSchedulerService {
    private Boolean isSandbox = [SELECT IsSandbox FROM Organization LIMIT 1].IsSandbox;

    private Map<String, String> headers = ApexPages.currentPage().getHeaders();
    private Map<String, String> param = ApexPages.currentPage().getParameters();
    private String origin = headers.get('Origin');

    public String response { get; set; }

    public BoatsSchedulerService() {}
    public void action() {
        if (isSandbox && origin != null) {
            headers.put('Access-Control-Allow-Origin', origin);
            headers.put('Access-Control-Allow-Credentials', 'true');
        }

        if (param.containsKey('loadResources')) {
            response = JSON.serialize([SELECT Id, Name FROM Boats__c Where Active__c=true ORDER BY BoatsSchedulerOrder__c]);

        } else if (param.containsKey('loadEvents')) {
            // valueOf is required in order to handle timezone
            Date start = Date.valueOf(param.get('start')).addDays(-1);// + ' 00:00:00');
            Date endd = Date.valueOf(param.get('end')).addDays(1);// + ' 00:00:00');
            response = JSON.serialize(
                [SELECT 
                    Id, Name, Start_Date__c, End_Date__c, Status__c, Boat__c,
                    RecordType.Name, Guide__r.Name, Guide__r.Employee_Phone__c,
                    AccountName__r.Name, AccountName__r.Phone,
                    Cruise_Purpose__c,
                    Co_Cruise__c,
                    Type2__c,
                    Subject__c,
                    Additional_Info__c,
                    Payment_Required__c,
                    Decline_Reason__c,
                    AccountName__r.Email__c,
                    Marina__c,
                    pier__c,
                    key_location__c,
                    information__c,
                    Hidden_Total_Hours__c,
                    Hidden_Additional_Hours__c,
                    Total_Cruise_of_Transaction__c,
                    Holiday__c,
                    Extra_Hours_Charge__c,
                    skill_level__c
                FROM Cruise__c WHERE
                    Status__c!='Canceled' AND
                    ((Start_Date__c  > :start AND Start_Date__c  < :endd) OR
                     (End_Date__c    > :start AND End_Date__c    < :endd) OR
                     (Start_Date__c  < :start AND End_Date__c    > :endd))
                ]
            );

        } else if (param.containsKey('updateEvent')) {
            update new Cruise__c(
                Id=param.get('id'),
                Start_Date__c=Datetime.valueOf(param.get('start')),
                End_Date__c=Datetime.valueOf(param.get('end'))
            );
        }
    }
}