force-app-modified/main/default/objects/Boats__c/Boats__c.object-meta.xml
<CustomObject>
    <label>סירה</label>
    <nameField>
        <label>שם סירה</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>סירות</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Boats__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>סטטוס פעיל/לא פעיל</label>
    <type>Checkbox</type>
</CustomField>

force-app-modified/main/default/objects/Boats__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>סוג סירה</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Boat_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Co_Cruise_Members__c/Co_Cruise_Members__c.object-meta.xml
<CustomObject>
    <label>לקוח משנה להפלגה</label>
    <nameField>
        <displayFormat>M-{00000}</displayFormat>
        <label>מספר מפליג משנה</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>לקוחות משנה להפלגה</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app-modified/main/default/objects/Co_Cruise_Members__c/fields/Account_Co__c.field-meta.xml
<CustomField>
    <fullName>Account_Co__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>לקוח</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>לקוחות משנה להפלגה</relationshipLabel>
    <relationshipName>Co_Cruise_Sailres</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app-modified/main/default/objects/Co_Cruise_Members__c/fields/boat_name__c.field-meta.xml
<CustomField>
    <fullName>boat_name__c</fullName>
    <label>שם סירה</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Co_Cruise_Members__c/fields/Cruise__c.field-meta.xml
<CustomField>
    <fullName>Cruise__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>הפלגה</label>
    <referenceTo>Cruise__c</referenceTo>
    <relationshipLabel>לקוחות משנה להפלגה</relationshipLabel>
    <relationshipName>Co_Cruise_Sailres</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Co_Cruise_Members__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <formula>Cruise__r.Start_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>תאריך</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Co_Cruise_Members__c/fields/SailStartMonthYear__c.field-meta.xml
<CustomField>
    <fullName>SailStartMonthYear__c</fullName>
    <formula>TEXT(MONTH(DATEVALUE(Cruise__r.Start_Date__c)))+ &apos;-&apos; + TEXT(YEAR(DATEVALUE(Cruise__r.Start_Date__c)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SailStartMonthYear</label>
    <type>Text</type>
</CustomField>

force-app-modified/main/default/objects/Co_Cruise_Members__c/fields/SailType__c.field-meta.xml
<CustomField>
    <fullName>SailType__c</fullName>
    <formula>Cruise__r.RecordType.DeveloperName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>סוג הפלגה</label>
    <type>Text</type>
</CustomField>

force-app-modified/main/default/objects/Co_Cruise_Members__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>TEXT(Cruise__r.Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>סטטוס הפלגה</label>
    <type>Text</type>
</CustomField>

force-app-modified/main/default/objects/Co_Cruise_Members__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>עסקה</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>לקוחות משנה להפלגה</relationshipLabel>
    <relationshipName>Co_Cruise_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/Cruise__c.object-meta.xml
<CustomObject>
    <label>הפלגה</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>מספר הפלגה</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>הפלגות</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app-modified/main/default/objects/Cruise__c/fields/AccountName__c.field-meta.xml
<CustomField>
    <fullName>AccountName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>שם לקוח</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>הפלגות</relationshipLabel>
    <relationshipName>Cruises</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cruise__c/fields/Additional_Info__c.field-meta.xml
<CustomField>
    <fullName>Additional_Info__c</fullName>
    <label>מידע נוסף למשתתפים</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Cruise__c/fields/Boat__c.field-meta.xml
<CustomField>
    <fullName>Boat__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>סירה</label>
    <referenceTo>Boats__c</referenceTo>
    <relationshipLabel>הפלגות</relationshipLabel>
    <relationshipName>Boat</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/fields/Boat_Name__c.field-meta.xml
<CustomField>
    <fullName>Boat_Name__c</fullName>
    <label>שם הסירה</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>פיץ&apos; (מפרשית)</fullName>
            </value>
            <value>
                <fullName>מיתוס (מפרשית)</fullName>
            </value>
            <value>
                <fullName>גוני (מפרשית)</fullName>
            </value>
            <value>
                <fullName>רוזה (יאכטה)</fullName>
            </value>
            <value>
                <fullName>אופוריה (יאכטה)</fullName>
            </value>
            <value>
                <fullName>אננדה (יאכטה)</fullName>
            </value>
            <value>
                <fullName>חאליסי (יאכטה)</fullName>
            </value>
            <value>
                <fullName>טוייקס (קטמרן)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cruise__c/fields/Course_Type__c.field-meta.xml
<CustomField>
    <fullName>Course_Type__c</fullName>
    <label>Course Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>קורס 7 מטר</fullName>
            </value>
            <value>
                <fullName>30 קורס משיט</fullName>
            </value>
            <value>
                <fullName>IYT קורס</fullName>
            </value>
            <value>
                <fullName>כללי</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cruise__c/fields/DATE__c.field-meta.xml
<CustomField>
    <fullName>DATE__c</fullName>
    <label>DATE</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Cruise__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>תאריך סיום</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Cruise__c/fields/For_Club_Members_Only__c.field-meta.xml
<CustomField>
    <fullName>For_Club_Members_Only__c</fullName>
    <defaultValue>false</defaultValue>
    <label>For Club Members Only</label>
    <type>Checkbox</type>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/fields/Guide__c.field-meta.xml
<CustomField>
    <fullName>Guide__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>מדריך להפלגה</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>הפלגות</relationshipLabel>
    <relationshipName>Guide_to_cruise</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cruise__c/fields/IsPrivateCourse__c.field-meta.xml
<CustomField>
    <fullName>IsPrivateCourse__c</fullName>
    <defaultValue>false</defaultValue>
    <label>האם קורס פרטי</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Cruise__c/fields/RemaingSeatsInBoat__c.field-meta.xml
<CustomField>
    <fullName>RemaingSeatsInBoat__c</fullName>
    <formula>MaxParticipants__c - SCCounts__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>RemaingSeatsInBoat</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cruise__c/fields/SailStartMonthYear__c.field-meta.xml
<CustomField>
    <fullName>SailStartMonthYear__c</fullName>
    <formula>TEXT(MONTH(DATEVALUE(Start_Date__c)))+ &apos;-&apos; + TEXT(YEAR(DATEVALUE(Start_Date__c)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SailStartMonthYear</label>
    <type>Text</type>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>תאריך התחלה</label>
    <type>DateTime</type>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>סטטוס</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Guide Matching</fullName>
                <label>לתיאום מדריך</label>
            </value>
            <value>
                <fullName>Awaiting for Approval</fullName>
                <label>ממתינה לאישור</label>
            </value>
            <value>
                <fullName>For Payment</fullName>
                <label>ממתין לתשלום</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
                <label>מבוטלת</label>
            </value>
            <value>
                <fullName>Ready</fullName>
                <label>מוכן להזמנה</label>
            </value>
            <value>
                <fullName>Occupied</fullName>
                <label>תפוס</label>
            </value>
            <value>
                <fullName>No Qualification</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <label>עסקאות</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>הפלגות</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Cruise__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>סוג הסירה</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>מפרשית</fullName>
            </value>
            <value>
                <fullName>יאכטה</fullName>
            </value>
            <value>
                <fullName>קטמרן</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/recordTypes/Certification.recordType-meta.xml
<RecordType>
    <fullName>Certification</fullName>
    <active>true</active>
    <label>Certification</label>
</RecordType>

force-app-modified/main/default/objects/Cruise__c/recordTypes/Course.recordType-meta.xml
<RecordType>
    <fullName>Course</fullName>
    <active>true</active>
    <label>Course</label>
</RecordType>

force-app-modified/main/default/objects/Cruise__c/recordTypes/Enriching.recordType-meta.xml
<RecordType>
    <fullName>Enriching</fullName>
    <active>true</active>
    <label>Enriching</label>
</RecordType>

force-app-modified/main/default/objects/Cruise__c/recordTypes/Friends.recordType-meta.xml
<RecordType>
    <fullName>Friends</fullName>
    <active>true</active>
    <label>Friends</label>
</RecordType>

force-app-modified/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>עסקה</label>
    <nameField>
        <label>שם עסקה</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>עסקאות</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>שם לקוח</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>עסקאות</relationshipLabel>
    <relationshipName>Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app-modified/main/default/objects/Transaction__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <description>T.A 12-11-2020: it was : IF(TODAY()&gt; End_Date__c , True,False)</description>
    <formula>IF(TODAY()&lt; End_Date__c , True,False)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>פעיל</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <defaultValue>today()+365</defaultValue>
    <label>תאריך סיום</label>
    <type>Date</type>
</CustomField>

force-app-modified/main/default/objects/Transaction__c/fields/Points_Balance__c.field-meta.xml
<CustomField>
    <fullName>Points_Balance__c</fullName>
    <formula>Total_Points__c - Used_Points__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>יתרת ניקוד</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app-modified/main/default/objects/Transaction__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <defaultValue>today()</defaultValue>
    <label>תאריך התחלה</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Transaction__c/recordTypes/RecordType.recordType-meta.xml
<RecordType>
    <fullName>RecordType</fullName>
    <active>false</active>
    <label>מוצרים אחרים</label>
</RecordType>

force-app-modified/main/default/classes/SeatimeSchedulerBookingController.cls
public without sharing class SeatimeSchedulerBookingController {
  @suppresswarnings('pmd.CognitiveComplexity')
  @AuraEnabled
  public static WrapperController seaTimeSchedulerBooking(String accountId) {
    try {
      System.debug('accountId : ' + accountId);
      WrapperController obj = new WrapperController();

      Account acc = [
        SELECT Id, StudentMeshit30__c, Student7Meter__c
        FROM Account
        WHERE Id = :accountId
        WITH SYSTEM_MODE
      ];

      List<Transaction__c> transactions = [
        SELECT Id, Active__c, Points_Balance__c
        FROM Transaction__c
        WHERE
          Account_Name__c = :accountId
          AND Active__c = TRUE
          AND Points_Balance__c > 30
        WITH SYSTEM_MODE
      ];

      Map<Id, Co_Cruise_Members__c> subCustomerMap = new Map<Id, Co_Cruise_Members__c>(
        [
          SELECT id, Account_Co__c, Cruise__c
          FROM Co_Cruise_Members__c
          WHERE Account_Co__c = :accountId AND Cruise__c != NULL
          WITH SYSTEM_MODE
        ]
      );
      Set<Id> saildIds = new Set<Id>();

      for (Co_Cruise_Members__c c : subCustomerMap.values()) {
        saildIds.add(c.Cruise__c);
      }

      String cruiseListQuery = 'SELECT id, Name, Status__c, Additional_Info__c, DATE__c, Guide__c, RemaingSeatsInBoat__c, Start_Date__c, End_Date__c, AccountName__c, recordtype.name, AccountName__r.Name, Boat__c, Boat__r.Name, toLabel(Boat__r.Type__c), SailStartMonthYear__c, Boat_Name__c FROM Cruise__c WHERE';
      if ((transactions.size() > 0) || acc.StudentMeshit30__c == true) {
        cruiseListQuery += ' ((RecordType.name = \'Friends\' OR RecordType.name = \'Enriching\'';
        if ((transactions.size() > 0)) {
          cruiseListQuery += ' OR RecordType.name = \'Certification\'';
          if (acc.Student7Meter__c == true) {
            cruiseListQuery += ' OR (RecordType.name = \'Course\' AND Course_Type__c = \'קורס 7 מטר\'))) AND Start_Date__c >= :todayDate AND End_Date__c >= :todayDate AND Status__c != \'Canceled\' AND IsPrivateCourse__c = FALSE ORDER BY Start_Date__c ASC';
          } else {
            cruiseListQuery += ')) AND Start_Date__c >= :todayDate AND End_Date__c >= :todayDate AND Status__c != \'Canceled\' AND IsPrivateCourse__c = FALSE ORDER BY Start_Date__c ASC';
          }
        } else {
          if (acc.Student7Meter__c == true) {
            cruiseListQuery += ' OR (RecordType.name = \'Course\' AND Course_Type__c = \'קורס 7 מטר\')) AND For_Club_Members_Only__c = FALSE)  AND Start_Date__c >= :todayDate AND End_Date__c >= :todayDate AND Status__c != \'Canceled\' AND IsPrivateCourse__c = FALSE ORDER BY Start_Date__c ASC';
          } else {
            cruiseListQuery += ') AND For_Club_Members_Only__c = FALSE) AND Start_Date__c >= :todayDate AND End_Date__c >= :todayDate AND Status__c != \'Canceled\' AND IsPrivateCourse__c = FALSE ORDER BY Start_Date__c ASC';
          }
        }
      } else if (acc.Student7Meter__c == true) {
        cruiseListQuery += ' ((RecordType.name = \'Course\' AND Course_Type__c = \'קורס 7 מטר\') AND For_Club_Members_Only__c = FALSE) AND Start_Date__c >= :todayDate AND End_Date__c >= :todayDate AND Status__c != \'Canceled\' AND IsPrivateCourse__c = FALSE ORDER BY Start_Date__c ASC';
      } else {
        cruiseListQuery = '';
      }

      System.debug('CruiseListQuery : ' + cruiseListQuery);

      if (cruiseListQuery != '') {
        WrapperController wrappedObj = getWrappedObj(
          cruiseListQuery,
          saildIds,
          obj
        );
        return wrappedObj;
      }
    } catch (exception e) {
      system.debug('seaTimeSchedulerBooking Message::' + e.getMessage());
      system.debug('seaTimeSchedulerBooking Line::' + e.getLineNumber());
    }
    return null;
  }

  private static WrapperController getWrappedObj(
    String cruiseListQuery,
    Set<Id> saildIds,
    WrapperController obj
  ) {
    Date todayDate = Date.today();
    List<Cruise__c> cruiseList = Database.query(cruiseListQuery);
    system.debug(
      ':::::::::::::::::::::::::************************************::::::::::::::::::::::::::: '
    );

    system.debug('sailMap::: ' + cruiseList);

    List<InnerWrapper> wrapList = new List<InnerWrapper>();
    System.debug('saildIds::' + saildIds);
    for (Cruise__c cruise : cruiseList) {
      System.debug('cruside id ' + cruise.Id);
      InnerWrapper wrp = new InnerWrapper();
      wrp.name = cruise.Name;
      wrp.sailId = cruise.Id;
      wrp.status = cruise.Status__c;
      wrp.additionalInfo = cruise.Additional_Info__c;
      wrp.sailStartMonthYear = cruise.SailStartMonthYear__c;
      wrp.remaingSeatsInBoat = Integer.valueOf(cruise.RemaingSeatsInBoat__c);
      String newDate = '';
      String newDate1 = '';
      String strDate = '';
      String strtTime = '';
      String endTime = '';
      if (cruise.Start_Date__c != null) {
        newDate = String.valueOf(cruise.Start_Date__c);
        strDate = newDate.split(' ')[0];
        System.debug('strDate::' + strDate);
        strtTime = newDate.split(' ')[1];
        System.debug('dstrtTime-->?' + strtTime);
      }
      if (cruise.End_Date__c != null) {
        newDate1 = String.valueOf(cruise.End_Date__c);
        System.debug('newDate::' + newDate1);
        endTime = newDate1.split(' ')[1];
        System.debug('dstrtTime-->?' + endTime);
      }
      String dateFormatString = 'dd-MM-yyyy';
      Date d2 = Date.valueOf(strDate);
      Datetime dt = Datetime.newInstance(d2.year(), d2.month(), d2.day());
      String stDt = dt.format(dateFormatString);
      wrp.startDate = stDt;
      wrp.startTime = strtTime.split(':')[0] + ':' + strtTime.split(':')[1];
      wrp.endTime = endTime.split(':')[0] + ':' + endTime.split(':')[1];
      wrp.recordTypeId = cruise.RecordTypeId;
      wrp.boat = cruise.Boat__c;
      wrp.boatName = cruise.Boat__r.Name;
      wrp.boatType = cruise.Boat__r.Type__c;
      wrp.recordType = cruise.recordtype.name;
      if (saildIds.contains(cruise.Id)) {
        wrp.bookingStatus = true;
      } else {
        wrp.bookingStatus = false;
      }
      System.debug('wrp::' + wrp);
      wrapList.add(wrp);
    }
    obj.innerWrp = wrapList;
    System.debug('obj::' + obj);
    return obj;
  }

  public class WrapperController {
    @AuraEnabled
    public List<InnerWrapper> innerWrp { get; set; }
  }

  public class InnerWrapper {
    @auraEnabled
    public Id sailId { get; set; }
    @auraEnabled
    public String name { get; set; }
    @auraEnabled
    public String sailStartMonthYear { get; set; }
    @auraEnabled
    public String status { get; set; }
    @auraEnabled
    public String additionalInfo { get; set; }
    @auraEnabled
    public Integer remaingSeatsInBoat { get; set; }
    @auraEnabled
    public String startDate { get; set; }
    @auraEnabled
    public String startTime { get; set; }
    @auraEnabled
    public String endTime { get; set; }
    @auraEnabled
    public Id recordTypeId { get; set; }
    @auraEnabled
    public Id boat { get; set; }
    @auraEnabled
    public String boatName { get; set; }
    @auraEnabled
    public String boatType { get; set; }
    @AuraEnabled
    public Boolean bookingStatus { get; set; }
    @AuraEnabled
    public String recordType { get; set; }
  }

  @AuraEnabled
  public static String insertSubCustomers(
    String sailId,
    String sailStartMonthYear,
    String accountId
  ) {
    try {
      system.debug('sailId:: ' + sailId);
      System.debug('AccountId-->' + accountId);
      System.debug('sailStartMonthYear-->' + sailStartMonthYear);

      AggregateResult[] groupedResults = [
        SELECT Count(Id) counts
        FROM Co_Cruise_Members__c
        WHERE
          Account_Co__c = :accountId
          AND (SailType__c = 'Friends'
          OR SailType__c = 'Enriching'
          OR SailType__c = 'Course'
          OR SailType__c = 'Certification')
          AND Status__c != 'Canceled'
          AND SailStartMonthYear__c = :sailStartMonthYear
        WITH SYSTEM_MODE
      ];
      Integer noOfSCCountsForSelectedMonth = 0;
      for (AggregateResult ar : groupedResults) {
        System.debug('noOfSCCountsForSelectedMonth' + ar.get('counts'));
        noOfSCCountsForSelectedMonth = Integer.valueOf(ar.get('counts'));
      }

      if (noOfSCCountsForSelectedMonth >= 6) {
        System.debug('Inside::::');
        return 'לא ניתן להצטרף להפלגה נוספת, מאחר ונרשמת כבר ל-6 הפלגות החודש. לשאלות נא להתקשר למשרד 037260500';
      } else {
        Co_Cruise_Members__c obj = new Co_Cruise_Members__c();
        obj.Cruise__c = sailId;
        obj.Account_Co__c = AccountId;

        insert as system obj;
        System.debug('obj' + obj);
        return '! נרשמת בהצלחה להפלגה';
      }
    } catch (exception e) {
      system.debug('insertSubCustomer Message::' + e.getMessage());
      system.debug('insertSubCustomer Line::' + e.getLineNumber());
      return null;
    }
  }
}