force-app-modified/main/default/objects/Boats__c/Boats__c.object-meta.xml
<CustomObject>
    <label>סירה</label>
    <nameField>
        <label>שם סירה</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>סירות</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Boats__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>סטטוס פעיל/לא פעיל</label>
    <type>Checkbox</type>
</CustomField>

force-app-modified/main/default/objects/Boats__c/fields/License_Number__c.field-meta.xml
<CustomField>
    <fullName>License_Number__c</fullName>
    <label>ישן</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app-modified/main/default/objects/Boats__c/fields/Max_Passenger__c.field-meta.xml
<CustomField>
    <fullName>Max_Passenger__c</fullName>
    <label>כמות נוסעים מקסימלית</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app-modified/main/default/objects/Boats__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>סוג סירה</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Boat_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Co_Cruise_Members__c/Co_Cruise_Members__c.object-meta.xml
<CustomObject>
    <label>לקוח משנה להפלגה</label>
    <nameField>
        <displayFormat>M-{00000}</displayFormat>
        <label>מספר מפליג משנה</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>לקוחות משנה להפלגה</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app-modified/main/default/objects/Co_Cruise_Members__c/fields/Account_Co__c.field-meta.xml
<CustomField>
    <fullName>Account_Co__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>לקוח</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>לקוחות משנה להפלגה</relationshipLabel>
    <relationshipName>Co_Cruise_Sailres</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Co_Cruise_Members__c/fields/Cruise__c.field-meta.xml
<CustomField>
    <fullName>Cruise__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>הפלגה</label>
    <referenceTo>Cruise__c</referenceTo>
    <relationshipLabel>לקוחות משנה להפלגה</relationshipLabel>
    <relationshipName>Co_Cruise_Sailres</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app-modified/main/default/objects/Co_Cruise_Members__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <formula>Account_Co__r.Email__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Email</label>
    <type>Text</type>
</CustomField>

force-app-modified/main/default/objects/Co_Cruise_Members__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>TEXT(Cruise__r.Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>סטטוס הפלגה</label>
    <type>Text</type>
</CustomField>

force-app-modified/main/default/objects/Co_Cruise_Members__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>עסקה</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>לקוחות משנה להפלגה</relationshipLabel>
    <relationshipName>Co_Cruise_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/Cruise__c.object-meta.xml
<CustomObject>
    <label>הפלגה</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>מספר הפלגה</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>הפלגות</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cruise__c/fields/Boat__c.field-meta.xml
<CustomField>
    <fullName>Boat__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>סירה</label>
    <referenceTo>Boats__c</referenceTo>
    <relationshipLabel>הפלגות</relationshipLabel>
    <relationshipName>Boat</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cruise__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>תאריך סיום</label>
    <type>DateTime</type>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/fields/SCCount__c.field-meta.xml
<CustomField>
    <fullName>SCCount__c</fullName>
    <label>SCCount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>תאריך התחלה</label>
    <type>DateTime</type>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>סטטוס</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Guide Matching</fullName>
                <label>לתיאום מדריך</label>
            </value>
            <value>
                <fullName>Awaiting for Approval</fullName>
                <label>ממתינה לאישור</label>
            </value>
            <value>
                <fullName>For Payment</fullName>
                <label>ממתין לתשלום</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
                <label>מבוטלת</label>
            </value>
            <value>
                <fullName>Ready</fullName>
                <label>מוכן להזמנה</label>
            </value>
            <value>
                <fullName>Occupied</fullName>
                <label>תפוס</label>
            </value>
            <value>
                <fullName>No Qualification</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <label>עסקאות</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>הפלגות</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Cruise__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>סוג הסירה</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>מפרשית</fullName>
            </value>
            <value>
                <fullName>יאכטה</fullName>
            </value>
            <value>
                <fullName>קטמרן</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/recordTypes/Enriching.recordType-meta.xml
<RecordType>
    <fullName>Enriching</fullName>
    <active>true</active>
    <label>Enriching</label>
</RecordType>

force-app-modified/main/default/objects/Cruise__c/recordTypes/Friends.recordType-meta.xml
<RecordType>
    <fullName>Friends</fullName>
    <active>true</active>
    <label>Friends</label>
</RecordType>

force-app-modified/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>עסקה</label>
    <nameField>
        <label>שם עסקה</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>עסקאות</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>שם לקוח</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>עסקאות</relationshipLabel>
    <relationshipName>Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app-modified/main/default/objects/Transaction__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <description>T.A 12-11-2020: it was : IF(TODAY()&gt; End_Date__c , True,False)</description>
    <formula>IF(TODAY()&lt; End_Date__c , True,False)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>פעיל</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Date_of_Transaction__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Transaction__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>תאריך העסקה</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <defaultValue>today()+365</defaultValue>
    <label>תאריך סיום</label>
    <type>Date</type>
</CustomField>

force-app-modified/main/default/objects/Transaction__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <defaultValue>today()</defaultValue>
    <label>תאריך התחלה</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/SubCustomerSailingTest.cls
@isTest
public class SubCustomerSailingTest {

    public static testMethod void insertMethod(){
        try{
        Account ac=new Account();
        ac.Name='Test Account';
        ac.Phone='1234567890';
        ac.Email__c='abc@gmail.com';
      
      
        insert ac;
        system.debug('accountid:::'+ac.id);
        Transaction__c transactionInstance=new Transaction__c();
        transactionInstance.Name='Test Transatcion';
        transactionInstance.Start_Date__c=Date.today();
        transactionInstance.End_Date__c=Date.today()+1;
        transactionInstance.Account_Name__c=ac.Id;
        transactionInstance.Date_of_Transaction__c=Date.today();
        insert transactionInstance;
        system.debug('Transaction:::'+transactionInstance.Id);
            
         Boats__c boatInstance=new Boats__c();
         boatInstance.Name='Test Boat';
         boatInstance.Active__c=true;
         boatInstance.License_Number__c=234;
         boatInstance.Type__c='sailboat';
         boatInstance.Max_Passenger__c=40;
            insert boatInstance;
         
            Id RecordTypeIdSail = Schema.SObjectType.Cruise__c.getRecordTypeInfosByDeveloperName().get('Enriching').getRecordTypeId();
            system.debug('RecordTypeIdSail:::: '+RecordTypeIdSail);
        Cruise__c sailInstance=new Cruise__c();
        sailInstance.RecordTypeId=RecordTypeIdSail;   
        sailInstance.Transaction__c=transactionInstance.Id;
        sailInstance.Boat__c=boatInstance.Id;  
        sailInstance.Start_Date__c=date.today();
        sailInstance.End_Date__c=Date.today()+1;
        sailInstance.Status__c='Approved'; 
        sailInstance.SCCount__c=5;  
        insert sailInstance;
                    Id RecordTypeIdSailFriend = Schema.SObjectType.Cruise__c.getRecordTypeInfosByDeveloperName().get('Friends').getRecordTypeId();
        Cruise__c sailInstance2=new Cruise__c();
        sailInstance2.RecordTypeId=RecordTypeIdSailFriend;   
        sailInstance2.Transaction__c=transactionInstance.Id;
        sailInstance2.Boat__c=boatInstance.Id;  
        sailInstance2.Start_Date__c=date.today();
        sailInstance2.End_Date__c=Date.today()+1;
        sailInstance2.Status__c='Approved'; 
        sailInstance2.SCCount__c=5;  
        insert sailInstance2;
         system.debug('sailInstance2:::'+sailInstance2.Id);
        
         Cruise__c sailInstance3=new Cruise__c();
        sailInstance3.RecordTypeId=RecordTypeIdSailFriend;   
        sailInstance3.Transaction__c=transactionInstance.Id;
        sailInstance3.Boat__c=boatInstance.Id;  
        sailInstance3.Start_Date__c=date.today();
        sailInstance3.End_Date__c=Date.today()+1;
        sailInstance3.Status__c='Approved'; 
        sailInstance3.SCCount__c=5;  
        insert sailInstance3;
            system.debug('sailInstance3:::'+sailInstance3);
        
        List<Co_Cruise_Members__c> newSubCustomerList=new List<Co_Cruise_Members__c>();
        Co_Cruise_Members__c subCustomerInstance=new Co_Cruise_Members__c();
        subCustomerInstance.Account_Co__c=ac.Id;
        subCustomerInstance.Cruise__c=sailInstance.Id;
         newSubCustomerList.add(subCustomerInstance);    
            
             Co_Cruise_Members__c subCustomerInstance2=new Co_Cruise_Members__c();
        subCustomerInstance2.Account_Co__c=ac.Id;
        subCustomerInstance2.Cruise__c=sailInstance2.Id;
        newSubCustomerList.add(subCustomerInstance2);
        insert newSubCustomerList;
            subCustomerInstance2.Cruise__c=sailInstance3.Id;
            Update subCustomerInstance2;
            delete subCustomerInstance2;
            
        }catch(Exception e){
            system.debug('Message in Test Class::'+e.getMessage());
             system.debug('Line Number in Test Class::'+e.getLineNumber());
        }
    }
    
    public static testMethod void findProfileTest(){
        /*List<Profile> profiles = [SELECT Id FROM Profile WHERE Name='מנהל מערכת']; 
        User u = new User(Alias = 'Data', Email='Data@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = profiles.size() > 0 ? profiles[0].Id : null, 
            TimeZoneSidKey='America/Los_Angeles', UserName='Data@testorg.com');
        insert u;
        test.startTest();
        SubCustomerSailing.findProfile(u.id);
        test.stopTest();*/
    }
   
}