force-app-modified/main/default/objects/Boats__c/Boats__c.object-meta.xml
<CustomObject>
    <label>סירה</label>
    <nameField>
        <label>שם סירה</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>סירות</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app-modified/main/default/objects/Cruise__c/Cruise__c.object-meta.xml
<CustomObject>
    <label>הפלגה</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>מספר הפלגה</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>הפלגות</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app-modified/main/default/objects/Cruise__c/fields/AccountName__c.field-meta.xml
<CustomField>
    <fullName>AccountName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>שם לקוח</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>הפלגות</relationshipLabel>
    <relationshipName>Cruises</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cruise__c/fields/Boat__c.field-meta.xml
<CustomField>
    <fullName>Boat__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>סירה</label>
    <referenceTo>Boats__c</referenceTo>
    <relationshipLabel>הפלגות</relationshipLabel>
    <relationshipName>Boat</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cruise__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>תאריך סיום</label>
    <type>DateTime</type>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>תאריך התחלה</label>
    <type>DateTime</type>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <label>עסקאות</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>הפלגות</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app-modified/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>עסקה</label>
    <nameField>
        <label>שם עסקה</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>עסקאות</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>שם לקוח</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>עסקאות</relationshipLabel>
    <relationshipName>Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Date_of_Transaction__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Transaction__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>תאריך העסקה</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <defaultValue>today()+365</defaultValue>
    <label>תאריך סיום</label>
    <type>Date</type>
</CustomField>

force-app-modified/main/default/objects/Transaction__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <defaultValue>today()</defaultValue>
    <label>תאריך התחלה</label>
    <type>Date</type>
</CustomField>

force-app-modified/main/default/objects/Transaction__c/fields/type_of_membership__c.field-meta.xml
<CustomField>
    <fullName>type_of_membership__c</fullName>
    <label>סוג מנוי</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>חבר מועדון כולל פרטיות</fullName>
            </value>
            <value>
                <fullName>מודרכות בלבד</fullName>
            </value>
            <value>
                <fullName>תלמיד</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BoatsSchedulerTest.cls
@isTest
private class BoatsSchedulerTest {

    @isTest static void test_BoatsSchedulerService_1() {
        Test.startTest();
        PageReference pRef;
        pRef = Page.BoatsSchedulerService;
        Map<String, String> param = pRef.getParameters();
        param.put('loadResources', '');
        Test.setCurrentPage(pRef);
        BoatsSchedulerService ctrl = new BoatsSchedulerService();
        ctrl.action();
        Test.stopTest();
    }

    @isTest static void test_BoatsSchedulerService_2() {
        Test.startTest();
        PageReference pRef;
        pRef = Page.BoatsSchedulerService;
        Map<String, String> param = pRef.getParameters();
        param.put('loadEvents', '');
        param.put('start', '2018-03-22');
        param.put('end', '2018-03-23');
        Test.setCurrentPage(pRef);
        BoatsSchedulerService ctrl = new BoatsSchedulerService();
        ctrl.action();
        Test.stopTest();
    }

    @isTest static void test_BoatsSchedulerService_3() {
        Boats__c boat = new Boats__c(Name='TestBoat');
        insert boat;
        Account account = new Account(Name='TestAccount');
        insert account;
        Transaction__c trans = new Transaction__c(Account_Name__c=account.Id, Date_of_Transaction__c = Date.newInstance(2023, 9, 4), type_of_membership__c = 'חבר מועדון כולל פרטיות');
        insert trans;
        Cruise__c cruise = new Cruise__c(Boat__c=boat.Id, AccountName__c=account.Id, Transaction__c=trans.Id, Start_Date__c=Datetime.now(), End_Date__c=Datetime.now());
        insert cruise;

        Test.startTest();
        PageReference pRef;
        pRef = Page.BoatsSchedulerService;
        Map<String, String> param = pRef.getParameters();
        param.put('updateEvent', '');
        param.put('id', cruise.Id);
        param.put('start', '2018-03-22 14:00:00');
        param.put('end', '2018-03-23 16:00:00');
        Test.setCurrentPage(pRef);
        BoatsSchedulerService ctrl = new BoatsSchedulerService();
        ctrl.action();
        Test.stopTest();
    }

}