force-app-modified/main/default/objects/Boats__c/Boats__c.object-meta.xml
<CustomObject>
    <label>סירה</label>
    <nameField>
        <label>שם סירה</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>סירות</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Boats__c/fields/Docking__c.field-meta.xml
<CustomField>
    <fullName>Docking__c</fullName>
    <label>מרינה</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Wharf</fullName>
                <label>רציף</label>
            </value>
            <value>
                <fullName>Marina</fullName>
                <label>מרינה</label>
            </value>
            <value>
                <fullName>Herz</fullName>
                <label>הרצליה</label>
            </value>
            <value>
                <fullName>תל אביב</fullName>
            </value>
            <value>
                <fullName>חיפה</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app-modified/main/default/objects/Boats__c/fields/License_Number__c.field-meta.xml
<CustomField>
    <fullName>License_Number__c</fullName>
    <label>ישן</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app-modified/main/default/objects/Boats__c/fields/Max_Passenger__c.field-meta.xml
<CustomField>
    <fullName>Max_Passenger__c</fullName>
    <label>כמות נוסעים מקסימלית</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app-modified/main/default/objects/Boats__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>סוג סירה</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Boat_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Certification__c/Certification__c.object-meta.xml
<CustomObject>
    <label>הסמכה</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>שם הסמכה</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>הסמכות</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Certification__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>שם הלקוח</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>הסמכות</relationshipLabel>
    <relationshipName>Account_Name</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app-modified/main/default/objects/Certification__c/fields/Boat__c.field-meta.xml
<CustomField>
    <fullName>Boat__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>סירה</label>
    <referenceTo>Boats__c</referenceTo>
    <relationshipLabel>הסמכות</relationshipLabel>
    <relationshipName>Certified_boat</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/Cruise__c.object-meta.xml
<CustomObject>
    <label>הפלגה</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>מספר הפלגה</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>הפלגות</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app-modified/main/default/objects/Cruise__c/fields/AccountName__c.field-meta.xml
<CustomField>
    <fullName>AccountName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>שם לקוח</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>הפלגות</relationshipLabel>
    <relationshipName>Cruises</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cruise__c/fields/Boat__c.field-meta.xml
<CustomField>
    <fullName>Boat__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>סירה</label>
    <referenceTo>Boats__c</referenceTo>
    <relationshipLabel>הפלגות</relationshipLabel>
    <relationshipName>Boat</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cruise__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>תאריך סיום</label>
    <type>DateTime</type>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>תאריך התחלה</label>
    <type>DateTime</type>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>סטטוס</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Guide Matching</fullName>
                <label>לתיאום מדריך</label>
            </value>
            <value>
                <fullName>Awaiting for Approval</fullName>
                <label>ממתינה לאישור</label>
            </value>
            <value>
                <fullName>For Payment</fullName>
                <label>ממתין לתשלום</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
                <label>מבוטלת</label>
            </value>
            <value>
                <fullName>Ready</fullName>
                <label>מוכן להזמנה</label>
            </value>
            <value>
                <fullName>Occupied</fullName>
                <label>תפוס</label>
            </value>
            <value>
                <fullName>No Qualification</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <label>עסקאות</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>הפלגות</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Cruise__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>סוג הסירה</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>מפרשית</fullName>
            </value>
            <value>
                <fullName>יאכטה</fullName>
            </value>
            <value>
                <fullName>קטמרן</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/recordTypes/Club.recordType-meta.xml
<RecordType>
    <fullName>Club</fullName>
    <active>true</active>
    <label>Club</label>
</RecordType>

force-app-modified/main/default/objects/Cruise__c/recordTypes/Course.recordType-meta.xml
<RecordType>
    <fullName>Course</fullName>
    <active>true</active>
    <label>Course</label>
</RecordType>

force-app-modified/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>עסקה</label>
    <nameField>
        <label>שם עסקה</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>עסקאות</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>שם לקוח</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>עסקאות</relationshipLabel>
    <relationshipName>Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Date_of_Transaction__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Transaction__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>תאריך העסקה</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <defaultValue>today()+365</defaultValue>
    <label>תאריך סיום</label>
    <type>Date</type>
</CustomField>

force-app-modified/main/default/objects/Transaction__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <defaultValue>today()</defaultValue>
    <label>תאריך התחלה</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Subscripption_Type__c.field-meta.xml
<CustomField>
    <fullName>Subscripption_Type__c</fullName>
    <label>סוג  מנוי</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bank Hours</fullName>
                <label>בנק שעות</label>
            </value>
            <value>
                <fullName>Enrichment Ticket</fullName>
                <label>כרטיסיית העשרה</label>
            </value>
            <value>
                <fullName>No Deal</fullName>
                <isActive>false</isActive>
                <label>No Deal</label>
            </value>
            <value>
                <fullName>One Time</fullName>
                <isActive>false</isActive>
                <label>חד פעמי</label>
            </value>
            <value>
                <fullName>Potential Deal</fullName>
                <isActive>false</isActive>
                <label>עסקה פוטנציאלית</label>
            </value>
            <value>
                <fullName>Periodic</fullName>
                <isActive>false</isActive>
                <label>תקופתי</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app-modified/main/default/objects/Transaction__c/fields/Total_Hours__c.field-meta.xml
<CustomField>
    <fullName>Total_Hours__c</fullName>
    <label>סה&quot;כ שעות</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app-modified/main/default/objects/Transaction__c/fields/type_of_membership__c.field-meta.xml
<CustomField>
    <fullName>type_of_membership__c</fullName>
    <label>סוג מנוי</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>חבר מועדון כולל פרטיות</fullName>
            </value>
            <value>
                <fullName>מודרכות בלבד</fullName>
            </value>
            <value>
                <fullName>תלמיד</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app-modified/main/default/objects/Transaction__c/fields/weekday__c.field-meta.xml
<CustomField>
    <fullName>weekday__c</fullName>
    <label>מספר הפלגות אמצ&quot;ש בחודש</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app-modified/main/default/objects/Transaction__c/fields/weekend__c.field-meta.xml
<CustomField>
    <fullName>weekend__c</fullName>
    <label>מספר הפלגות סופ&quot;ש בחודש</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Transaction__c/recordTypes/RecordType.recordType-meta.xml
<RecordType>
    <fullName>RecordType</fullName>
    <active>false</active>
    <label>מוצרים אחרים</label>
</RecordType>

force-app-modified/main/default/classes/SeatimeSchedulerWebappControllerTest.cls
@IsTest 
public with sharing class SeatimeSchedulerWebappControllerTest {
	
	static testMethod void testController() {
		//PREPARE DATA
		Account acc = new Account();
		acc.Name = 'hadar test';
		acc.First_Name__c = 'hadar';
		acc.Last_Name__c = 'test';
		acc.Phone = '0549234443';
		acc.Email__c = 'hadartest@gmail.com';
		acc.Account_Status__c = 'Club Member';
		acc.Interest__c = 'Basic Course';	
        acc.Login_Token__c = '123456789';
		insert acc;
		
		Boats__c boat1 = new Boats__c();
		boat1.Name = 'מיתוס';
		boat1.License_Number__c = 222222; 
		boat1.Type__c = 'Sailboat'; 
		boat1.Max_Passenger__c = 12; 
		boat1.Docking__c = 'Wharf'; 
		insert boat1;
		  
		Certification__c cer = new Certification__c();
		cer.Boat__c = boat1.Id;
		cer.Account_Name__c = acc.Id;
		insert cer;
		  
		Transaction__c tran = new Transaction__c();
		tran.Name = 'Alon';
		tran.Account_Name__c = acc.Id;
		tran.Type__c = 'Sailboat';
		Date today = System.today();
		tran.Date_of_Transaction__c = today.addDays(-30);
		tran.Start_Date__c = today.addDays(-20);
		tran.End_Date__c = today.addDays(10);
		tran.Subscripption_Type__c = 'Bank Hours';
		tran.Total_Hours__c = 20;
		tran.weekday__c = 2;
		tran.weekend__c = 3;
		tran.type_of_membership__c = 'חבר מועדון כולל פרטיות';
		insert tran;
		
		Transaction__c tran2 = new Transaction__c();
		tran2.Name = 'Alon'; //
		tran2.Account_Name__c = acc.Id;
		tran2.Type__c = 'Sailboat'; //
		Date todaytran2 = System.today();
		tran2.Date_of_Transaction__c = today.addDays(-30);
		tran2.Start_Date__c = today.addDays(-20);
		tran2.End_Date__c = today.addDays(10);
		tran2.Subscripption_Type__c = 'Bank Hours';
		tran2.Total_Hours__c = 20;
		tran2.weekday__c = 2;
		tran2.weekend__c = 3;
		//insert tran2;
		
		Event event = new Event();
		event.Is_Locked__c = true;
		event.Origin__c = 'Employee';
		event.DurationInMinutes = 30;
		event.ActivityDateTime = System.now();
		insert event;
		
		Event event2 = new Event();
		event2.Is_Locked__c = true;
		event2.Origin__c = 'Classroom';
		event2.DurationInMinutes = 30;
		event2.ActivityDateTime = System.now();
		insert event2;
		

		Cruise__c cruise1 = new Cruise__c();
		cruise1.AccountName__c = acc.Id;
		cruise1.Transaction__c = tran.Id;
		cruise1.Boat__c = boat1.Id; 
		RecordType recordTypeClub = [SELECT Id,Name,DeveloperName FROM RecordType WHERE Name = 'Club'];
		cruise1.RecordTypeId = recordTypeClub.Id; 
		cruise1.Status__c = 'Awaiting for Approval'; 
		Date crDate = System.today().addDays(1);
		cruise1.Start_Date__c = Datetime.newInstance(crDate.year(), crDate.month(), crDate.day(), 13, 00, 00);
		cruise1.End_Date__c = Datetime.newInstance(crDate.year(), crDate.month(), crDate.day(), 17, 00, 00);
		
		Cruise__c cruise2 = new Cruise__c();
		cruise2.AccountName__c = acc.Id;
		cruise2.Transaction__c = tran.Id;
		cruise2.Boat__c = boat1.Id; 
		cruise2.Status__c = 'Approved';
		crDate = System.today().addDays(1);
		cruise2.Start_Date__c = Datetime.newInstance(crDate.year(), crDate.month(), crDate.day(), 11, 00, 00);
		cruise2.End_Date__c = Datetime.newInstance(crDate.year(), crDate.month(), crDate.day(), 12, 00, 00);
		
		List<Cruise__c> crList = new List<Cruise__c>{cruise1, cruise2};
		
		try{
			insert crList;	  
			}catch(DmlException e) {
				 System.debug('An unexpected error has occurred: ' + e.getMessage());
			}	   
	
		//TEST	
		System.debug('crList: '+crList);
		SeatimeSchedulerWebappController ctrl = new SeatimeSchedulerWebappController();
        ctrl.getSchedulerMdtStatusSetting();
        Boolean isSandbox = ctrl.isSandbox;
        String currentUserLocale = ctrl.currentUserLocale;
        String currentUserType = ctrl.currentUserType;
        String orgBoats = ctrl.orgBoats;
        String orgCruiseRecordTypes = ctrl.orgCruiseRecordTypes;
        String orgAccounts = ctrl.orgAccounts;
        SeatimeSchedulerWebappController.getOrgBoats();
        SeatimeSchedulerWebappController.getOrgAccounts();
        SeatimeSchedulerWebappController.SecureAccount securAcc = SeatimeSchedulerWebappController.getSecureAccount(acc.Login_Token__c);
        SeatimeSchedulerWebappController.getAccountBoats(securAcc);
        SeatimeSchedulerWebappController.getCruisesForScheduler(securAcc, System.today().addDays(1));
        SeatimeSchedulerWebappController.getOrgCruises();
        SeatimeSchedulerWebappController.getEmployeeClassroomEvents();
        SeatimeSchedulerWebappController.getCruiseHistory(securAcc);
        SeatimeSchedulerWebappController.getPersonalDetails(securAcc);
        
        String cruise1Json = JSON.serialize(cruise1);
		SeatimeSchedulerWebappController.saveCruiseEvent(cruise1Json);
        String cruiseErrorJson = '{"attributes":{"type":"Cruise__c"},"AccountName__c":"'+acc.Id+'","Status__c":"Awaiting for Approval","Start_Date__c":"2017-10-24T10:00:00.000+0000","End_Date__c":"2017-10-24T14:00:00.000+0000","Start_Time":"19:00:00.000","End_time":"20:00:00.000"}';
		SeatimeSchedulerWebappController.saveCruiseEvent(cruiseErrorJson);
		String cruiseExceptionJson = '{"attributes":{"type":"Cruise__c"},"Start_Date__c":"+cruise2.Start_Date__c+","End_Date__c":"+cruise2.End_Date__c+","Start_Time":"19:00:00.000","End_time":"20:00:00.000"}';
		SeatimeSchedulerWebappController.saveCruiseEvent(cruiseExceptionJson);
		cruise2.Start_Date__c = cruise2.Start_Date__c.addMinutes(20);
		cruise2.End_Date__c = cruise2.End_Date__c.addMinutes(20);
		String cruiseExceptionJson3 = JSON.serialize(cruise2);
		SeatimeSchedulerWebappController.saveCruiseEvent(cruiseExceptionJson3);
		
		String accountJson = JSON.serialize(acc);
		SeatimeSchedulerWebappController.updatePersonalDetails(accountJson, securAcc);
		SeatimeSchedulerWebappController.updatePersonalDetails('{"attributes":{"type":"Account"},"Name":"hadar error"}', securAcc);
    
	}
}