force-app-modified/main/default/objects/Boats__c/Boats__c.object-meta.xml
<CustomObject>
    <label>סירה</label>
    <nameField>
        <label>שם סירה</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>סירות</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app-modified/main/default/objects/Cruise__c/Cruise__c.object-meta.xml
<CustomObject>
    <label>הפלגה</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>מספר הפלגה</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>הפלגות</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app-modified/main/default/objects/Cruise__c/fields/AccountName__c.field-meta.xml
<CustomField>
    <fullName>AccountName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>שם לקוח</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>הפלגות</relationshipLabel>
    <relationshipName>Cruises</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/recordTypes/Club.recordType-meta.xml
<RecordType>
    <fullName>Club</fullName>
    <active>true</active>
    <label>Club</label>
</RecordType>

force-app-modified/main/default/classes/CreateCruiseTest.cls
@isTest
private class CreateCruiseTest {

    @isTest static void test_CreateCruise_1() {
        Boats__c boat = new Boats__c(Name='TestBoat');
        insert boat;
        String start = '14:00 22/03/2018';
        String endd = '16:00 22/03/2018';
        RecordType rt = [SELECT Id FROM RecordType WHERE SObjectType='Cruise__c' AND Name='Club'];
        Account account = new Account(Name='TestAccount');
        insert account;

        Test.startTest();
        PageReference pRef;
        pRef = Page.CreateCruise;
        Map<String, String> param = pRef.getParameters();
        param.put('boatId', boat.Id);
        param.put('start', start);
        param.put('end', endd);
        Test.setCurrentPage(pRef);
        CreateCruise ctrl = new CreateCruise();
        ctrl.cruise.RecordTypeId = rt.Id;
        ctrl.cruise.AccountName__c = account.Id;
        ctrl.isClassic = true;
        ctrl.save();
        Test.stopTest();
    }

    @isTest static void test_CreateCruise_2() {
        Boats__c boat = new Boats__c(Name='TestBoat');
        insert boat;
        String start = '14:00 22/03/2018';
		String endd  = '16:00 22/03/2018';
        RecordType rt = [SELECT Id FROM RecordType WHERE SObjectType='Cruise__c' AND Name='Club'];
        Account account = new Account(Name='TestAccount');
        insert account;

        Test.startTest();
        PageReference pRef;
        pRef = Page.CreateCruise;
        Map<String, String> param = pRef.getParameters();
        param.put('boatId', boat.Id);
        param.put('start', start);
        param.put('end', endd);
        Test.setCurrentPage(pRef);
        CreateCruise ctrl = new CreateCruise();
        ctrl.cruise.RecordTypeId = rt.Id;
        ctrl.cruise.AccountName__c = account.Id;
        ctrl.isClassic = false;
        ctrl.save();
        Test.stopTest();
    }

}