force-app-modified/main/default/objects/Boats__c/Boats__c.object-meta.xml
<CustomObject>
    <label>סירה</label>
    <nameField>
        <label>שם סירה</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>סירות</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Boats__c/fields/Docking__c.field-meta.xml
<CustomField>
    <fullName>Docking__c</fullName>
    <label>מרינה</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Wharf</fullName>
                <label>רציף</label>
            </value>
            <value>
                <fullName>Marina</fullName>
                <label>מרינה</label>
            </value>
            <value>
                <fullName>Herz</fullName>
                <label>הרצליה</label>
            </value>
            <value>
                <fullName>תל אביב</fullName>
            </value>
            <value>
                <fullName>חיפה</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app-modified/main/default/objects/Boats__c/fields/License_Number__c.field-meta.xml
<CustomField>
    <fullName>License_Number__c</fullName>
    <label>ישן</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app-modified/main/default/objects/Boats__c/fields/Max_Passenger__c.field-meta.xml
<CustomField>
    <fullName>Max_Passenger__c</fullName>
    <label>כמות נוסעים מקסימלית</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app-modified/main/default/objects/Boats__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>סוג סירה</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Boat_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Certification__c/Certification__c.object-meta.xml
<CustomObject>
    <label>הסמכה</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>שם הסמכה</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>הסמכות</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Certification__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>שם הלקוח</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>הסמכות</relationshipLabel>
    <relationshipName>Account_Name</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app-modified/main/default/objects/Certification__c/fields/Boat__c.field-meta.xml
<CustomField>
    <fullName>Boat__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>סירה</label>
    <referenceTo>Boats__c</referenceTo>
    <relationshipLabel>הסמכות</relationshipLabel>
    <relationshipName>Certified_boat</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/Cruise__c.object-meta.xml
<CustomObject>
    <label>הפלגה</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>מספר הפלגה</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>הפלגות</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app-modified/main/default/objects/Cruise__c/fields/AccountName__c.field-meta.xml
<CustomField>
    <fullName>AccountName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>שם לקוח</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>הפלגות</relationshipLabel>
    <relationshipName>Cruises</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cruise__c/fields/Boat__c.field-meta.xml
<CustomField>
    <fullName>Boat__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>סירה</label>
    <referenceTo>Boats__c</referenceTo>
    <relationshipLabel>הפלגות</relationshipLabel>
    <relationshipName>Boat</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cruise__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>תאריך סיום</label>
    <type>DateTime</type>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>תאריך התחלה</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Cruise__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <formula>DATETIMEVALUE(Start_Date__c + ( fitting_time_to_daylight__c /24))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Start Time</label>
    <type>DateTime</type>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>סטטוס</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Guide Matching</fullName>
                <label>לתיאום מדריך</label>
            </value>
            <value>
                <fullName>Awaiting for Approval</fullName>
                <label>ממתינה לאישור</label>
            </value>
            <value>
                <fullName>For Payment</fullName>
                <label>ממתין לתשלום</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
                <label>מבוטלת</label>
            </value>
            <value>
                <fullName>Ready</fullName>
                <label>מוכן להזמנה</label>
            </value>
            <value>
                <fullName>Occupied</fullName>
                <label>תפוס</label>
            </value>
            <value>
                <fullName>No Qualification</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <label>עסקאות</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>הפלגות</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Cruise__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>סוג הסירה</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>מפרשית</fullName>
            </value>
            <value>
                <fullName>יאכטה</fullName>
            </value>
            <value>
                <fullName>קטמרן</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/recordTypes/Club.recordType-meta.xml
<RecordType>
    <fullName>Club</fullName>
    <active>true</active>
    <label>Club</label>
</RecordType>

force-app/main/default/objects/Customer_Setting__mdt/Customer_Setting__mdt.object-meta.xml
<CustomObject>
    <description>includes the time windows for each boat type.</description>
    <label>Customer Setting</label>
    <pluralLabel>Customer Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Customer_Setting__mdt/fields/End_time__c.field-meta.xml
<CustomField>
    <fullName>End_time__c</fullName>
    <label>End time</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app-modified/main/default/objects/Customer_Setting__mdt/fields/Start_time__c.field-meta.xml
<CustomField>
    <fullName>Start_time__c</fullName>
    <label>Start time</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app-modified/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>עסקה</label>
    <nameField>
        <label>שם עסקה</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>עסקאות</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>שם לקוח</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>עסקאות</relationshipLabel>
    <relationshipName>Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Date_of_Transaction__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Transaction__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>תאריך העסקה</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <defaultValue>today()+365</defaultValue>
    <label>תאריך סיום</label>
    <type>Date</type>
</CustomField>

force-app-modified/main/default/objects/Transaction__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <defaultValue>today()</defaultValue>
    <label>תאריך התחלה</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Subscripption_Type__c.field-meta.xml
<CustomField>
    <fullName>Subscripption_Type__c</fullName>
    <label>סוג  מנוי</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bank Hours</fullName>
                <label>בנק שעות</label>
            </value>
            <value>
                <fullName>Enrichment Ticket</fullName>
                <label>כרטיסיית העשרה</label>
            </value>
            <value>
                <fullName>No Deal</fullName>
                <isActive>false</isActive>
                <label>No Deal</label>
            </value>
            <value>
                <fullName>One Time</fullName>
                <isActive>false</isActive>
                <label>חד פעמי</label>
            </value>
            <value>
                <fullName>Potential Deal</fullName>
                <isActive>false</isActive>
                <label>עסקה פוטנציאלית</label>
            </value>
            <value>
                <fullName>Periodic</fullName>
                <isActive>false</isActive>
                <label>תקופתי</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app-modified/main/default/objects/Transaction__c/fields/Total_Hours__c.field-meta.xml
<CustomField>
    <fullName>Total_Hours__c</fullName>
    <label>סה&quot;כ שעות</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app-modified/main/default/objects/Transaction__c/fields/type_of_membership__c.field-meta.xml
<CustomField>
    <fullName>type_of_membership__c</fullName>
    <label>סוג מנוי</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>חבר מועדון כולל פרטיות</fullName>
            </value>
            <value>
                <fullName>מודרכות בלבד</fullName>
            </value>
            <value>
                <fullName>תלמיד</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app-modified/main/default/objects/Transaction__c/fields/weekday__c.field-meta.xml
<CustomField>
    <fullName>weekday__c</fullName>
    <label>מספר הפלגות אמצ&quot;ש בחודש</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app-modified/main/default/objects/Transaction__c/fields/weekend__c.field-meta.xml
<CustomField>
    <fullName>weekend__c</fullName>
    <label>מספר הפלגות סופ&quot;ש בחודש</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Transaction__c/recordTypes/RecordType.recordType-meta.xml
<RecordType>
    <fullName>RecordType</fullName>
    <active>false</active>
    <label>מוצרים אחרים</label>
</RecordType>

force-app-modified/main/default/classes/SchedulerServiceTest.cls
@isTest(seealldata=true)
private class SchedulerServiceTest {
	static testMethod void createSchedulerTest() {
        
        Account acc = new Account();
        acc.Name = 'hadar test';
        acc.Login_Token__c = '123456789';
        insert acc;
        
        SchedulerService ss = new SchedulerService();
        Transaction__c tran = ss.createTransaction(null, acc.Id);
        
        List<Cruise__c> existingCruiseList = new List<Cruise__c>();
        List<Cruise__c> cList = new List<Cruise__c>();
        
        Cruise__c cruiseItem = new Cruise__c();
        cruiseItem.Start_Date__c = Datetime.newInstance(2017, 10, 16, 08, 00, 00);
        cruiseItem.End_Date__c = Datetime.newInstance(2017, 10, 16, 11, 00, 00);
        
        Cruise__c cruiseItem2 = new Cruise__c();
        cruiseItem2.Start_Date__c = Datetime.newInstance(2017, 10, 16, 13, 00, 00);
        cruiseItem2.End_Date__c = Datetime.newInstance(2017, 10, 16, 18, 00, 00);
        
        Cruise__c cruiseItem3 = new Cruise__c();
        cruiseItem3.Start_Date__c = Datetime.newInstance(2017, 10, 16, 19, 00, 00);
        cruiseItem3.End_Date__c = Datetime.newInstance(2017, 10, 16, 20, 00, 00);
        
        Cruise__c cruiseItem4 = new Cruise__c();
        cruiseItem4.Start_Date__c = Datetime.newInstance(2017, 10, 16, 21, 00, 00);
        cruiseItem4.End_Date__c = Datetime.newInstance(2017, 10, 16, 23, 00, 00);
        
        existingCruiseList.add(cruiseItem);
        existingCruiseList.add(cruiseItem2);
        existingCruiseList.add(cruiseItem3);
        existingCruiseList.add(cruiseItem4);
        
        SeatimeSchedulerWebappController.SecureAccount securAcc = SeatimeSchedulerWebappController.getSecureAccount(acc.Login_Token__c);
        Map<Id,Boats__c> idBoatsObjMap = SeatimeSchedulerWebappController.getAccountBoats(securAcc);
        Test.startTest();
 /* -----------------------------------------------------------------------------*/
        Boats__c boat1 = new Boats__c();
		boat1.Name = 'מיתוס';
		boat1.License_Number__c = 222222; 
		boat1.Type__c = 'Sailboat'; 
		boat1.Max_Passenger__c = 12; 
		boat1.Docking__c = 'Wharf'; 
		insert boat1;
        Certification__c cer = new Certification__c();
		cer.Boat__c = boat1.Id;
		cer.Account_Name__c = acc.Id;
		insert cer;
		  
				Date today = System.today();
		
		Transaction__c tran2 = new Transaction__c();
		tran2.Name = 'Alon'; //
		tran2.Account_Name__c = acc.Id;
		tran2.Type__c = 'Sailboat'; //
		Date todaytran2 = System.today();
		tran2.Date_of_Transaction__c = today.addDays(-30);
		tran2.Start_Date__c = today.addDays(-20);
		tran2.End_Date__c = today.addDays(10);
		tran2.Subscripption_Type__c = 'Bank Hours';
		tran2.Total_Hours__c = 20;
		tran2.weekday__c = 2;
		tran2.weekend__c = 3;
		tran2.type_of_membership__c = 'חבר מועדון כולל פרטיות';
		insert tran2;
		
		Event event = new Event();
		event.Is_Locked__c = true;
		event.Origin__c = 'Employee';
		event.DurationInMinutes = 30;
		event.ActivityDateTime = System.now();
		insert event;
		
		Event event2 = new Event();
		event2.Is_Locked__c = true;
		event2.Origin__c = 'Classroom';
		event2.DurationInMinutes = 30;
		event2.ActivityDateTime = System.now();
		insert event2;
        		Cruise__c cruise1 = new Cruise__c();
		cruise1.AccountName__c = acc.Id;
		cruise1.Transaction__c = tran.Id;
		cruise1.Boat__c = boat1.Id; 
		RecordType recordTypeClub = [SELECT Id,Name,DeveloperName FROM RecordType WHERE Name = 'Club'];
		cruise1.RecordTypeId = recordTypeClub.Id; 
		cruise1.Status__c = 'Awaiting for Approval'; 
		Date crDate = System.today().addDays(1);
		cruise1.Start_Date__c = Datetime.newInstance(crDate.year(), crDate.month(), crDate.day(), 13, 00, 00);
		cruise1.End_Date__c = Datetime.newInstance(crDate.year(), crDate.month(), crDate.day(), 17, 00, 00);
		
		Cruise__c cruise2 = new Cruise__c();
		cruise2.AccountName__c = acc.Id;
		cruise2.Transaction__c = tran.Id;
		cruise2.Boat__c = boat1.Id; 
		cruise2.Status__c = 'Approved';
		crDate = System.today().addDays(1);
		cruise2.Start_Date__c = Datetime.newInstance(crDate.year(), crDate.month(), crDate.day(), 11, 00, 00);
		cruise2.End_Date__c = Datetime.newInstance(crDate.year(), crDate.month(), crDate.day(), 12, 00, 00);

        List<Cruise__c> crList = new List<Cruise__c>{cruise1, cruise2};
            try{
			insert crList;	  
			}catch(DmlException e) {
				 System.debug('An unexpected error has occurred: ' + e.getMessage());
			}	 
            /*--------------------------------------------------*/
       //t.a Test.startTest();
        SchedulerService service = new SchedulerService(acc.Id, 2, idBoatsObjMap, System.today());
		List<Customer_Setting__mdt> settingsList = [SELECT Id, 
                                                           Label, 
                                                           Start_time__c, 
                                                           End_time__c
                                            		FROM Customer_Setting__mdt];
        Set <SchedulerService.Slot> slts = new Set <SchedulerService.Slot>();
        for(Customer_Setting__mdt s:settingsList)   slts.add(service.stringToSlot(s));
        service.setTimeSlots(slts,existingCruiseList, null, Datetime.newInstance(2017, 10, 16, 00, 00, 00));
        service.prepareScheduler();
        service.getEmployeeClassroomEvents();
        Test.stopTest();
		
    }
}