force-app-modified/main/default/objects/Boats__c/Boats__c.object-meta.xml
<CustomObject>
    <label>סירה</label>
    <nameField>
        <label>שם סירה</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>סירות</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Boats__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>סטטוס פעיל/לא פעיל</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Boats__c/fields/BoatsSchedulerOrder__c.field-meta.xml
<CustomField>
    <fullName>BoatsSchedulerOrder__c</fullName>
    <label>סדר במתזמן</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/Cruise__c.object-meta.xml
<CustomObject>
    <label>הפלגה</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>מספר הפלגה</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>הפלגות</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app-modified/main/default/objects/Cruise__c/fields/AccountName__c.field-meta.xml
<CustomField>
    <fullName>AccountName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>שם לקוח</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>הפלגות</relationshipLabel>
    <relationshipName>Cruises</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cruise__c/fields/Boat__c.field-meta.xml
<CustomField>
    <fullName>Boat__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>סירה</label>
    <referenceTo>Boats__c</referenceTo>
    <relationshipLabel>הפלגות</relationshipLabel>
    <relationshipName>Boat</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cruise__c/fields/Dock_Duty__c.field-meta.xml
<CustomField>
    <fullName>Dock_Duty__c</fullName>
    <label>תורנות רציף</label>
    <type>Checkbox</type>
    <defaultValue>false</defaultValue>
</CustomField>

force-app/main/default/objects/Cruise__c/fields/Employee_Email__c.field-meta.xml
<CustomField>
    <fullName>Employee_Email__c</fullName>
    <label>אימייל מדריך</label>
    <type>Email</type>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/fields/Employee_Phone__c.field-meta.xml
<CustomField>
    <fullName>Employee_Phone__c</fullName>
    <label>טלפון מדריך</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cruise__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>תאריך סיום</label>
    <type>DateTime</type>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/fields/Guide__c.field-meta.xml
<CustomField>
    <fullName>Guide__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>מדריך להפלגה</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>הפלגות</relationshipLabel>
    <relationshipName>Guide_to_cruise</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>תאריך התחלה</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Cruise__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <formula>DATETIMEVALUE(Start_Date__c + ( fitting_time_to_daylight__c /24))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Start Time</label>
    <type>DateTime</type>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>סטטוס</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Guide Matching</fullName>
                <label>לתיאום מדריך</label>
            </value>
            <value>
                <fullName>Awaiting for Approval</fullName>
                <label>ממתינה לאישור</label>
            </value>
            <value>
                <fullName>For Payment</fullName>
                <label>ממתין לתשלום</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
                <label>מבוטלת</label>
            </value>
            <value>
                <fullName>Ready</fullName>
                <label>מוכן להזמנה</label>
            </value>
            <value>
                <fullName>Occupied</fullName>
                <label>תפוס</label>
            </value>
            <value>
                <fullName>No Qualification</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <label>עסקאות</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>הפלגות</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/recordTypes/Club.recordType-meta.xml
<RecordType>
    <fullName>Club</fullName>
    <active>true</active>
    <label>Club</label>
</RecordType>

force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>מדריך</label>
    <nameField>
        <label>שם המדריך</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>מדריכים</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <label>מדריך פעיל</label>
    <type>Checkbox</type>
    <defaultValue>true</defaultValue>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Employee_Email__c.field-meta.xml
<CustomField>
    <fullName>Employee_Email__c</fullName>
    <label>מייל מדריך</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Employee_Phone__c.field-meta.xml
<CustomField>
    <fullName>Employee_Phone__c</fullName>
    <label>טלפון</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Employee_Type__c.field-meta.xml
<CustomField>
    <fullName>Employee_Type__c</fullName>
    <label>סוג שכר</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>שעתי</fullName>
                <default>true</default>
                <label>שעתי</label>
            </value>
            <value>
                <fullName>חודשי</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Rate_Dock_Duty__c.field-meta.xml
<CustomField>
    <fullName>Rate_Dock_Duty__c</fullName>
    <label>תעריף שעתי - תורנות רציף</label>
    <type>Currency</type>
    <precision>18</precision>
    <scale>2</scale>
    <defaultValue>50</defaultValue>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Rate_General__c.field-meta.xml
<CustomField>
    <fullName>Rate_General__c</fullName>
    <label>תעריף שעתי - כללי</label>
    <type>Currency</type>
    <precision>18</precision>
    <scale>2</scale>
    <defaultValue>70</defaultValue>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Rate_Instruction__c.field-meta.xml
<CustomField>
    <fullName>Rate_Instruction__c</fullName>
    <label>הדרכה בים</label>
    <type>Number</type>
    <precision>18</precision>
    <scale>0</scale>
    <defaultValue>70</defaultValue>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Rate_Maintenance__c.field-meta.xml
<CustomField>
    <fullName>Rate_Maintenance__c</fullName>
    <label>אחזקה/תיקונים/ניקיון</label>
    <type>Number</type>
    <precision>18</precision>
    <scale>0</scale>
    <defaultValue>50</defaultValue>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Travel_Cost__c.field-meta.xml
<CustomField>
    <fullName>Travel_Cost__c</fullName>
    <label>עלות נסיעה ליום עבודה</label>
    <type>Number</type>
    <precision>18</precision>
    <scale>0</scale>
    <defaultValue>25</defaultValue>
</CustomField>

force-app/main/default/objects/Time_Entry__c/Time_Entry__c.object-meta.xml
<CustomObject>
    <description>רישום ודיווחי שעות עבודה לעובדים ומדריכים</description>
    <label>דיווח שעות</label>
    <nameField>
        <displayFormat>TE-{000000}</displayFormat>
        <label>מספר דיווח</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>דיווחי שעות</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Time_Entry__c/fields/Cruise__c.field-meta.xml
<CustomField>
    <fullName>Cruise__c</fullName>
    <label>הפלגה מקושרת</label>
    <referenceTo>Cruise__c</referenceTo>
    <relationshipLabel>דיווחי שעות</relationshipLabel>
    <relationshipName>Time_Entries</relationshipName>
    <deleteConstraint>SetNull</deleteConstraint>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Time_Entry__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>תיאור / הערות</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Time_Entry__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <label>מדריך / עובד</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>דיווחי שעות</relationshipLabel>
    <relationshipName>Time_Entries</relationshipName>
    <deleteConstraint>SetNull</deleteConstraint>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Time_Entry__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <label>שעת סיום</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Time_Entry__c/fields/Entry_Type__c.field-meta.xml
<CustomField>
    <fullName>Entry_Type__c</fullName>
    <label>סוג פעילות</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>הפלגה</fullName>
                <default>true</default>
                <label>הפלגה</label>
            </value>
            <value>
                <fullName>תורנות רציף</fullName>
            </value>
            <value>
                <fullName>תחזוקה</fullName>
            </value>
            <value>
                <fullName>חו״ל / יום מלא</fullName>
            </value>
            <value>
                <fullName>קורס</fullName>
            </value>
            <value>
                <fullName>החזר הוצאות</fullName>
            </value>
            <value>
                <fullName>בונוס</fullName>
            </value>
            <value>
                <fullName>מחלה</fullName>
            </value>
            <value>
                <fullName>חופשה</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Time_Entry__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <label>שעת התחלה</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Time_Entry__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>סטטוס דיווח</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>אושר</fullName>
                <default>true</default>
                <label>אושר</label>
            </value>
            <value>
                <fullName>ממתין לאישור</fullName>
            </value>
            <value>
                <fullName>נדחה</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Time_Entry__c/fields/Work_Date__c.field-meta.xml
<CustomField>
    <fullName>Work_Date__c</fullName>
    <label>תאריך פעילות</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app-modified/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>עסקה</label>
    <nameField>
        <label>שם עסקה</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>עסקאות</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>שם לקוח</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>עסקאות</relationshipLabel>
    <relationshipName>Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app-modified/main/default/objects/Transaction__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <description>T.A 12-11-2020: it was : IF(TODAY()&gt; End_Date__c , True,False)</description>
    <formula>IF(TODAY()&lt; End_Date__c , True,False)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>פעיל</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Date_of_Transaction__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Transaction__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>תאריך העסקה</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <defaultValue>today()+365</defaultValue>
    <label>תאריך סיום</label>
    <type>Date</type>
</CustomField>

force-app-modified/main/default/objects/Transaction__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <defaultValue>today()</defaultValue>
    <label>תאריך התחלה</label>
    <type>Date</type>
</CustomField>

force-app-modified/main/default/objects/Transaction__c/fields/type_of_membership__c.field-meta.xml
<CustomField>
    <fullName>type_of_membership__c</fullName>
    <label>סוג מנוי</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>חבר מועדון כולל פרטיות</fullName>
            </value>
            <value>
                <fullName>מודרכות בלבד</fullName>
            </value>
            <value>
                <fullName>תלמיד</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/recordTypes/RecordType.recordType-meta.xml
<RecordType>
    <fullName>RecordType</fullName>
    <active>false</active>
    <label>מוצרים אחרים</label>
</RecordType>

force-app/main/default/classes/StaffTimeTrackingControllerTest.cls
@isTest
private class StaffTimeTrackingControllerTest {

    @testSetup
    static void setupCommonData() {
        Boats__c boat = new Boats__c(Name = 'ספינת מבחן', Active__c = true, BoatsSchedulerOrder__c = 1);
        insert boat;

        Account acc = new Account(Name = 'Test Account', Phone = '1234', Email__c = 'testacc@test.com');
        insert acc;
        
        Transaction__c sub = new Transaction__c(
            Name = 'Test Transaction',
            Account_Name__c = acc.Id,
            Date_of_Transaction__c = System.today(),
            Start_Date__c = System.today(),
            End_Date__c = System.today().addDays(30),
            type_of_membership__c = 'חבר מועדון כולל פרטיות'
        );
        insert sub;
    }

    @isTest
    static void testMonthlyReportAndEntries() {
        Boats__c boat = [SELECT Id FROM Boats__c LIMIT 1];
        Account acc = [SELECT Id FROM Account LIMIT 1];
        Transaction__c sub = [SELECT Id FROM Transaction__c LIMIT 1];

        // Create test Employee
        Employee__c emp = new Employee__c(
            Name = 'מדריך בדיקה',
            Employee_Phone__c = '0501234567',
            Employee_Email__c = 'instructor@example.com',
            Employee_Type__c = 'שעתי',
            Travel_Cost__c = 25,
            Rate_Instruction__c = 70,
            Rate_Dock_Duty__c = 50,
            Rate_Maintenance__c = 50,
            Rate_General__c = 70
        );
        insert emp;

        RecordType rt = [SELECT Id FROM RecordType WHERE SObjectType = 'Cruise__c' LIMIT 1];

        // Create test Cruises for a past month so they have already occurred
        Integer testYear = 2025;
        Integer testMonth = 6;
        Date testDate = Date.newInstance(testYear, testMonth, 10);
        DateTime dtStart = DateTime.newInstance(testDate, Time.newInstance(9, 0, 0, 0));
        DateTime dtEnd = DateTime.newInstance(testDate, Time.newInstance(13, 0, 0, 0));

        Cruise__c c1 = new Cruise__c(
            RecordTypeId = rt.Id,
            Boat__c = boat.Id,
            Guide__c = emp.Id,
            AccountName__c = acc.Id,
            Transaction__c = sub.Id,
            Start_Date__c = dtStart,
            End_Date__c = dtEnd,
            Status__c = 'Approved'
        );
        insert c1;

        // Test Dock Duty cruise
        Cruise__c c2 = new Cruise__c(
            RecordTypeId = rt.Id,
            Boat__c = boat.Id,
            Guide__c = emp.Id,
            AccountName__c = acc.Id,
            Transaction__c = sub.Id,
            Start_Date__c = dtStart.addDays(1),
            End_Date__c = dtEnd.addDays(1),
            Status__c = 'Approved',
            Dock_Duty__c = true
        );
        insert c2;

        // Also create a FUTURE cruise in current month to verify it is NOT included
        Cruise__c cFuture = new Cruise__c(
            RecordTypeId = rt.Id,
            Boat__c = boat.Id,
            Guide__c = emp.Id,
            AccountName__c = acc.Id,
            Transaction__c = sub.Id,
            Start_Date__c = DateTime.now().addDays(10),
            End_Date__c = DateTime.now().addDays(10).addHours(3),
            Status__c = 'Approved'
        );
        insert cFuture;

        Test.startTest();
        StaffTimeTrackingController.MonthlySummary summary = StaffTimeTrackingController.getMonthlyReport(
            emp.Id, testYear, testMonth
        );
        System.assertNotEquals(null, summary, 'Summary should not be null');
        System.assertEquals(2, summary.entries.size(), 'Should only include the 2 performed cruises');

        // Test accountant report
        List<StaffTimeTrackingController.AccountantReportRow> accountantRows = StaffTimeTrackingController.getAccountantMonthlyReport(testYear, testMonth);
        System.assertNotEquals(0, accountantRows.size(), 'Should have accountant rows for test month');

        // Test Save manual entry
        Time_Entry__c manualEntry = new Time_Entry__c(
            Employee__c = emp.Id,
            Work_Date__c = testDate,
            Start_Time__c = '14:00',
            End_Time__c = '18:00',
            Entry_Type__c = 'תחזוקה',
            Description__c = 'תחזוקת ציוד'
        );
        Time_Entry__c saved = StaffTimeTrackingController.saveTimeEntry(manualEntry);
        System.assertNotEquals(null, saved.Id, 'Saved entry should have Id');

        // Test Delete entry
        Boolean deleted = StaffTimeTrackingController.deleteTimeEntry(saved.Id);
        System.assertEquals(true, deleted, 'Entry should be deleted');
        Test.stopTest();
    }

    @isTest
    static void testMonthlySalaryEmployee() {
        Boats__c boat = [SELECT Id FROM Boats__c LIMIT 1];
        Account acc = [SELECT Id FROM Account LIMIT 1];
        Transaction__c sub = [SELECT Id FROM Transaction__c LIMIT 1];
        RecordType rt = [SELECT Id FROM RecordType WHERE SObjectType = 'Cruise__c' LIMIT 1];

        Employee__c emp = new Employee__c(
            Name = 'עובד חודשי',
            Employee_Phone__c = '0507654321',
            Employee_Email__c = 'monthly@example.com',
            Employee_Type__c = 'חודשי',
            Monthly_Salary__c = 8500,
            Travel_Cost__c = 25
        );
        insert emp;

        // Create a cruise assigned to this monthly employee
        Date testDate = Date.newInstance(2025, 6, 12);
        Cruise__c cMonthly = new Cruise__c(
            RecordTypeId = rt.Id,
            Boat__c = boat.Id,
            Guide__c = emp.Id,
            AccountName__c = acc.Id,
            Transaction__c = sub.Id,
            Start_Date__c = DateTime.newInstance(testDate, Time.newInstance(10, 0, 0, 0)),
            End_Date__c = DateTime.newInstance(testDate, Time.newInstance(14, 0, 0, 0)),
            Status__c = 'Approved'
        );
        insert cMonthly;

        // Add a manual bonus entry for this monthly employee
        Time_Entry__c bonusEntry = new Time_Entry__c(
            Employee__c = emp.Id,
            Work_Date__c = testDate,
            Entry_Type__c = 'בונוס',
            Total_Payment__c = 500,
            Description__c = 'בונוס חודשי מיוחד',
            Is_Auto_Generated__c = false
        );
        insert bonusEntry;

        Test.startTest();
        StaffTimeTrackingController.MonthlySummary summary = StaffTimeTrackingController.getMonthlyReport(
            emp.Id, 2025, 6
        );
        System.assertNotEquals(null, summary);
        // Cruise should NOT be auto-generated, only the manual bonus entry should be present!
        System.assertEquals(1, summary.entries.size(), 'Monthly employee should only have manual entries, no auto cruises');
        System.assertEquals('בונוס', summary.entries[0].Entry_Type__c);

        // Test Accountant Report
        List<StaffTimeTrackingController.AccountantReportRow> reportRows = StaffTimeTrackingController.getAccountantMonthlyReport(
            2025, 6
        );
        System.assertNotEquals(null, reportRows);
        Test.stopTest();
    }

    @isTest
    static void testClubMemberVolunteer() {
        Employee__c empClub = new Employee__c(
            Name = 'מדריך חבר מועדון',
            Employee_Phone__c = '0509998877',
            Employee_Email__c = 'clubmember@example.com',
            Employee_Type__c = 'חבר מועדון'
        );
        insert empClub;

        Test.startTest();
        StaffTimeTrackingController.MonthlySummary summary = StaffTimeTrackingController.getMonthlyReport(
            empClub.Id, 2025, 6
        );
        System.assertNotEquals(null, summary);
        System.assertEquals(0, summary.entries.size(), 'Club members should have no time entries');

        List<StaffTimeTrackingController.AccountantReportRow> reportRows = StaffTimeTrackingController.getAccountantMonthlyReport(
            2025, 6
        );
        for (StaffTimeTrackingController.AccountantReportRow r : reportRows) {
            System.assertNotEquals(empClub.Id, r.employeeId, 'Club member should not appear in accountant report');
        }
        Test.stopTest();
    }
}