force-app/main/default/objects/Certification__c/Certification__c.object-meta.xml
<CustomObject>
    <label>הסמכה</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>שם הסמכה</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>הסמכות</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Certification__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>שם הלקוח</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>הסמכות</relationshipLabel>
    <relationshipName>Account_Name</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app-modified/main/default/objects/Certification__c/fields/Boat__c.field-meta.xml
<CustomField>
    <fullName>Boat__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>סירה</label>
    <referenceTo>Boats__c</referenceTo>
    <relationshipLabel>הסמכות</relationshipLabel>
    <relationshipName>Certified_boat</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/Cruise__c.object-meta.xml
<CustomObject>
    <label>הפלגה</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>מספר הפלגה</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>הפלגות</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cruise__c/fields/Boat__c.field-meta.xml
<CustomField>
    <fullName>Boat__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>סירה</label>
    <referenceTo>Boats__c</referenceTo>
    <relationshipLabel>הפלגות</relationshipLabel>
    <relationshipName>Boat</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/fields/Payment_Required__c.field-meta.xml
<CustomField>
    <fullName>Payment_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>דרוש תשלום</label>
    <type>Checkbox</type>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>סטטוס</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Guide Matching</fullName>
                <label>לתיאום מדריך</label>
            </value>
            <value>
                <fullName>Awaiting for Approval</fullName>
                <label>ממתינה לאישור</label>
            </value>
            <value>
                <fullName>For Payment</fullName>
                <label>ממתין לתשלום</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
                <label>מבוטלת</label>
            </value>
            <value>
                <fullName>Ready</fullName>
                <label>מוכן להזמנה</label>
            </value>
            <value>
                <fullName>Occupied</fullName>
                <label>תפוס</label>
            </value>
            <value>
                <fullName>No Qualification</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/recordTypes/Certification.recordType-meta.xml
<RecordType>
    <fullName>Certification</fullName>
    <active>true</active>
    <label>Certification</label>
</RecordType>

force-app-modified/main/default/objects/Cruise__c/recordTypes/Club.recordType-meta.xml
<RecordType>
    <fullName>Club</fullName>
    <active>true</active>
    <label>Club</label>
</RecordType>

force-app/main/default/classes/CruiseManager.cls
public class CruiseManager {
    
    private final String NO_CERTIFICATE_FOR_ACCOUNT = 'אין הסמכה';  
    
    /* SEAT-32: in entering cruise in record type club verify the account 
    * 			has certification for the boat 
	*
	* @author	: Shira Hai
	* @date		: 23/11/17
	*
	* @method 	checkAccountHasCertificate
	* @param 	List<Cruise__c>	: clubCruiseList
	* @param 	List <Account> 	: accList
	*/
    public void checkAccountHasCertificate(List <Cruise__c> clubCruiseList, Map <Id,Account> accMap ){
        for (Cruise__c criuseItem : clubCruiseList){
            Account relatedAccount = accMap.get(criuseItem.Id);
            if(!isAccountCertified(criuseItem,relatedAccount) && criuseItem.Payment_Required__c == false && criuseItem.Status__c != 'Canceled'){                     
                criuseItem.Status__c = 'No Qualification';
            }else if(criuseItem.Status__c == null){
                criuseItem.Status__c ='Awaiting for Approval';
            }
                
        }
    }

    public Boolean isAccountCertified(Cruise__c criuseItem, Account relatedAccount){
        List<Certification__c> certificationList = relatedAccount.Account_Name__r;
        if(certificationList != null && !certificationList.isEmpty()){
            for (Certification__c certificateItem : certificationList){
                if(criuseItem.Boat__c.equals(certificateItem.Boat__c)){
                    //the account has certificate
                    return true;
                }
            }
        }
        return false;
    }

    
    /* SEAT-26: get friday and saturday hours from cruis hours for extra hours clculation
	*
	* @author	: Shira Hai
	* @date		: 23/11/17
	*
	* @method 	CalculateExtraHours
	* @param 	DateTime	: startDate
	* @param	DateTime	: endDate
	* @return 	double 	
	*/
     public double CalculateExtraHours(DateTime startDate , DateTime endDate){
     	
      	DateTime checkDate ;
      	String DayOfWeek;
      	Double extraHours= 0;
      	Decimal getHour ;
        Decimal getMinute ;
  		Decimal totalHour;
        Decimal addExtHours;
         
        checkDate = startDate ;
         
  		while(checkDate <= endDate){
  			DayOfWeek = checkDate.format('EEEE');
  			if (DayOfWeek == 'Friday' || DayOfWeek == 'Saturday' || Test.isRunningTest()){
                
                if (checkDate.isSameDay(startDate) ){
                    getHour = startDate.hour() ;
                	getMinute = startDate.minute();
                    if(checkDate.isSameDay(endDate)){
                        Decimal startHour = getHour + (getMinute/60);
                        getHour = endDate.hour() ;
                        getMinute = endDate.minute();
                        Decimal endHour = getHour + (getMinute/60);
                        totalHour = endHour - startHour;
                    }else{
                        totalHour = 24.00 - (getHour + (getMinute/60));
                    }
                    addExtHours =  totalHour*150/100 - totalHour;
                    extraHours += addExtHours;
                }
                
                else if(checkDate.isSameDay(endDate)){
                    getHour = endDate.hour() ;
                	getMinute = endDate.minute();
                    totalHour = getHour + (getMinute/60);
                    addExtHours =  totalHour*150/100 - totalHour;
                    extraHours += addExtHours;
                }
                
                else if((!checkDate.isSameDay(startDate)) && (!checkDate.isSameDay(endDate))){
                	extraHours += 12.00;	
                }
      		}
      		checkDate = checkDate.addDays(1);
  		}
     	return extraHours;
     }


    public class DebugException extends Exception{}
    
}