force-app/main/default/objects/Welcome_Overlay_Config__mdt/Welcome_Overlay_Config__mdt.object-meta.xml
<CustomObject>
    <description>Manage site url and overlay background</description>
    <label>Welcome Overlay Config</label>
    <pluralLabel>Welcome Overlay Configs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Welcome_Overlay_Config__mdt/fields/Block_Page__c.field-meta.xml
<CustomField>
    <fullName>Block_Page__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Block Page</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Welcome_Overlay_Config__mdt/fields/Overlay_BG__c.field-meta.xml
<CustomField>
    <fullName>Overlay_BG__c</fullName>
    <label>Overlay BG</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Welcome_Overlay_Config__mdt/fields/Overlay_URL__c.field-meta.xml
<CustomField>
    <fullName>Overlay_URL__c</fullName>
    <label>Overlay URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app-modified/main/default/classes/WelcomeOverlayConfigService.cls
// created apex for CMDT value 1738
public without sharing class WelcomeOverlayConfigService {
    public static Welcome_Overlay_Config__mdt getConfig() {
        return [
            SELECT Overlay_URL__c,
                   Overlay_BG__c,
                   Block_Page__c
            FROM Welcome_Overlay_Config__mdt
            WHERE DeveloperName = 'Default'
            LIMIT 1
        ];
    }
}