force-app-modified/main/default/objects/Current_Scheduled_ID__c/Current_Scheduled_ID__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Portal Settings</label>
</CustomObject>

force-app/main/default/objects/Current_Scheduled_ID__c/fields/Scheduled_Job_ID__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Job_ID__c</fullName>
    <label>Scheduled Job ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PortalSettingsPageControllerTest.cls
/**
 *	SEAT-25 Create vf with button to start the scheduled job "ResetBatchScheduler" in the first time
 *	author Hadar Berman
 *
 *	@class PortalSettingsPageControllerTest
 *	@async
 */
@IsTest 
public with sharing class PortalSettingsPageControllerTest {
	
	static testmethod void executeSchedulerTest() {
		
		PortalSettingsPageController ctrlWithNullCustomSetting = new PortalSettingsPageController();
		ctrlWithNullCustomSetting.executeScheduler();
		
		//prepare data
		Current_Scheduled_ID__c custSetting = new Current_Scheduled_ID__c();
		custSetting.Scheduled_Job_ID__c = '08e2600000Cljpr';
		insert custSetting;
		
		PortalSettingsPageController PSController = new PortalSettingsPageController();
		PSController.executeScheduler();
		
	}
    
}