force-app-modified/main/default/objects/Current_Scheduled_ID__c/Current_Scheduled_ID__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Portal Settings</label>
</CustomObject>

force-app/main/default/objects/Current_Scheduled_ID__c/fields/Scheduled_Job_ID__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Job_ID__c</fullName>
    <label>Scheduled Job ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Portal_Setting__mdt/Portal_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Portal Setting</label>
    <pluralLabel>Portal Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Portal_Setting__mdt/fields/Scheduled_Job_ID__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Job_ID__c</fullName>
    <label>Scheduled Job ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Portal_Setting__mdt/fields/TimeToResetBatchScheduler__c.field-meta.xml
<CustomField>
    <fullName>TimeToResetBatchScheduler__c</fullName>
    <description>set the time (minutes) of next scheduler that execute ResetBatch.</description>
    <label>TimeToResetBatchScheduler</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ResetBatchScheduler.cls
/**
 *	SEAT-23: Create scheduler
 *	start a scheduled job every some minutes (mdt: TimeToResetBatchScheduler__c) to execure the batch (ResetBatch) who`s reset attempts & token
 *	author Hadar Berman
 *
 *	@class ResetBatchScheduler
 * 	@module ???
 *	@constructor
 */
public with sharing class ResetBatchScheduler {
	
	private static final String LABEL_NAME = 'LOGIN_SETTINGS';
	private static Integer MINUTES_TO_SCHEDULE;
	
	private Current_Scheduled_ID__c prtSettings;
	
	public ResetBatchScheduler(){ //constractor
		prepareMetadata();
	} 
	
    /**
     *	SEAT-23 Create scheduler
     *	author Hadar Berman
     *
     *	@method	 scheduleBatch
     */
	public void scheduleBatch(){
		if(MINUTES_TO_SCHEDULE != null){
				String jobId = System.scheduleBatch(new ResetBatch(), 'Start ResetBatch', MINUTES_TO_SCHEDULE);
				prtSettings.Scheduled_Job_ID__c = jobId;
				update prtSettings;
		}
	}
	
	/**
     *	SEAT-23 Create scheduler
     *	author Hadar Berman
     *
     *	@method	 prepareMetadata
     */
	private void prepareMetadata(){
		List<Portal_Setting__mdt> portalSettingList = [SELECT TimeToResetBatchScheduler__c
    												   FROM Portal_Setting__mdt
    												   WHERE Label LIKE :LABEL_NAME LIMIT 1];
    	if(!portalSettingList.isEmpty()){
    		MINUTES_TO_SCHEDULE = Integer.valueOf(portalSettingList[0].TimeToResetBatchScheduler__c);
    	}
		List<Current_Scheduled_ID__c> customSettingList = [SELECT Id FROM Current_Scheduled_ID__c];
    	if(!customSettingList.isEmpty()){
    		this.prtSettings = customSettingList[0];
    	}
	}
    
}