force-app/main/default/objects/Co_Cruise_Members__c/Co_Cruise_Members__c.object-meta.xml
<CustomObject>
    <label>לקוח משנה להפלגה</label>
    <nameField>
        <displayFormat>M-{00000}</displayFormat>
        <label>מספר מפליג משנה</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>לקוחות משנה להפלגה</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app-modified/main/default/objects/Co_Cruise_Members__c/fields/Account_Co__c.field-meta.xml
<CustomField>
    <fullName>Account_Co__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>לקוח</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>לקוחות משנה להפלגה</relationshipLabel>
    <relationshipName>Co_Cruise_Sailres</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Co_Cruise_Members__c/fields/Cruise__c.field-meta.xml
<CustomField>
    <fullName>Cruise__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>הפלגה</label>
    <referenceTo>Cruise__c</referenceTo>
    <relationshipLabel>לקוחות משנה להפלגה</relationshipLabel>
    <relationshipName>Co_Cruise_Sailres</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app-modified/main/default/objects/courses__c/courses__c.object-meta.xml
<CustomObject>
    <label>קורס</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>מספר קורס</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>קורסים</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/courses__c/fields/SMS_Message__c.field-meta.xml
<CustomField>
    <fullName>SMS_Message__c</fullName>
    <label>SMS Message</label>
    <type>TextArea</type>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/Cruise__c.object-meta.xml
<CustomObject>
    <label>הפלגה</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>מספר הפלגה</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>הפלגות</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app-modified/main/default/objects/Cruise__c/fields/course__c.field-meta.xml
<CustomField>
    <fullName>course__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>קורס</label>
    <referenceTo>courses__c</referenceTo>
    <relationshipLabel>הפלגות</relationshipLabel>
    <relationshipName>course</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partecipant__c/Partecipant__c.object-meta.xml
<CustomObject>
    <label>השתתפות בקורס</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>מספר משתתף</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>השתתפויות בקורסים</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Partecipant__c/fields/course__c.field-meta.xml
<CustomField>
    <fullName>course__c</fullName>
    <label>קורס</label>
    <referenceTo>courses__c</referenceTo>
    <relationshipName>partecipants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Partecipant__c/fields/Partecipant__c.field-meta.xml
<CustomField>
    <fullName>Partecipant__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>שם משתתף</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>partecipation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app-modified/main/default/classes/BulkSMSController.cls
/**
 * Created by Nabhan on 12/31/2020.
 */

public with sharing class BulkSMSController {
    final static String FROM_ADDRESS = 'yonatan@sea-time.co.il';
    final static String TO_ADDRESS = 'bodygw@sms.inforu.co.il';

    @AuraEnabled
    public static Boolean sendSMSToCourseMembers(String courseId) {
        List<Partecipant__c> partecipants = [
                SELECT Id, Partecipant__r.Phone, course__r.SMS_Message__c
                FROM Partecipant__c
                WHERE course__c = :courseId
        ];

        List<OrgWideEmailAddress> owes = [
                SELECT Id
                FROM OrgWideEmailAddress
                WHERE Address = :FROM_ADDRESS
        ];

        try {
            List<Messaging.SingleEmailMessage> emailMessages = new List<Messaging.SingleEmailMessage>();

            for (Partecipant__c objPartecipant : partecipants) {
                Messaging.SingleEmailMessage objSingleEmailMessage = new Messaging.SingleEmailMessage();
                objSingleEmailMessage.setOrgWideEmailAddressId(owes[0].Id);
                objSingleEmailMessage.setSubject(objPartecipant.Partecipant__r.Phone);
                objSingleEmailMessage.setPlainTextBody(objPartecipant.course__r.SMS_Message__c);
                objSingleEmailMessage.setToAddresses(new String[] {TO_ADDRESS});
                emailMessages.add(objSingleEmailMessage);
            }
            Messaging.sendEmail(emailMessages);
        } catch (Exception ex) {
            System.debug(ex.getMessage());
            System.debug(ex.getStackTraceString());
            return false;
        }
        return true;
    }

    @AuraEnabled
    public static Boolean sendSMSToCruiseMembers(String cruiseId) {
        List<Co_Cruise_Members__c> cruiseMembers = [
                SELECT Id, Cruise__r.SMS_Message__c, Account_Co__r.Phone
                FROM Co_Cruise_Members__c
                WHERE Cruise__c = :cruiseId
        ];

        List<OrgWideEmailAddress> owes = [
                SELECT Id
                FROM OrgWideEmailAddress
                WHERE Address = :FROM_ADDRESS
        ];

        try {
            List<Messaging.SingleEmailMessage> emailMessages = new List<Messaging.SingleEmailMessage>();

            for (Co_Cruise_Members__c objCruiseMember : cruiseMembers) {
                Messaging.SingleEmailMessage objSingleEmailMessage = new Messaging.SingleEmailMessage();
                objSingleEmailMessage.setOrgWideEmailAddressId(owes[0].Id);
                objSingleEmailMessage.setSubject(objCruiseMember.Account_Co__r.Phone);
                objSingleEmailMessage.setPlainTextBody(objCruiseMember.Cruise__r.SMS_Message__c);
                objSingleEmailMessage.setToAddresses(new String[] {TO_ADDRESS});
                emailMessages.add(objSingleEmailMessage);
            }
            Messaging.sendEmail(emailMessages);
        } catch (Exception ex) {
            System.debug(ex.getMessage());
            System.debug(ex.getStackTraceString());
            return false;
        }
        return true;
    }
}