force-app/main/default/objects/Co_Cruise_Members__c/Co_Cruise_Members__c.object-meta.xml
<CustomObject>
    <label>לקוח משנה להפלגה</label>
    <nameField>
        <displayFormat>M-{00000}</displayFormat>
        <label>מספר מפליג משנה</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>לקוחות משנה להפלגה</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Co_Cruise_Members__c/fields/Cruise__c.field-meta.xml
<CustomField>
    <fullName>Cruise__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>הפלגה</label>
    <referenceTo>Cruise__c</referenceTo>
    <relationshipLabel>לקוחות משנה להפלגה</relationshipLabel>
    <relationshipName>Co_Cruise_Sailres</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app-modified/main/default/objects/Co_Cruise_Members__c/fields/Cruise_Points__c.field-meta.xml
<CustomField>
    <fullName>Cruise_Points__c</fullName>
    <label>שווי ניקוד הפלגה</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app-modified/main/default/objects/Co_Cruise_Members__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>TEXT(Cruise__r.Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>סטטוס הפלגה</label>
    <type>Text</type>
</CustomField>

force-app-modified/main/default/objects/Co_Cruise_Members__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>עסקה</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>לקוחות משנה להפלגה</relationshipLabel>
    <relationshipName>Co_Cruise_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/Cruise__c.object-meta.xml
<CustomObject>
    <label>הפלגה</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>מספר הפלגה</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>הפלגות</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cruise__c/fields/Boat__c.field-meta.xml
<CustomField>
    <fullName>Boat__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>סירה</label>
    <referenceTo>Boats__c</referenceTo>
    <relationshipLabel>הפלגות</relationshipLabel>
    <relationshipName>Boat</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/fields/Cruise_Points__c.field-meta.xml
<CustomField>
    <fullName>Cruise_Points__c</fullName>
    <label>שווי ניקוד הפלגה</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>סטטוס</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Guide Matching</fullName>
                <label>לתיאום מדריך</label>
            </value>
            <value>
                <fullName>Awaiting for Approval</fullName>
                <label>ממתינה לאישור</label>
            </value>
            <value>
                <fullName>For Payment</fullName>
                <label>ממתין לתשלום</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
                <label>מבוטלת</label>
            </value>
            <value>
                <fullName>Ready</fullName>
                <label>מוכן להזמנה</label>
            </value>
            <value>
                <fullName>Occupied</fullName>
                <label>תפוס</label>
            </value>
            <value>
                <fullName>No Qualification</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app-modified/main/default/objects/Cruise__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <label>עסקאות</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>הפלגות</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Cruise__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>סוג הסירה</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>מפרשית</fullName>
            </value>
            <value>
                <fullName>יאכטה</fullName>
            </value>
            <value>
                <fullName>קטמרן</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app-modified/main/default/objects/PriceListLine__c/PriceListLine__c.object-meta.xml
<CustomObject>
    <label>שורת מחירון</label>
    <nameField>
        <displayFormat>PLL-{0}</displayFormat>
        <label>שם שורת מחירון</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PriceListLines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app-modified/main/default/objects/PriceListLine__c/fields/Boat__c.field-meta.xml
<CustomField>
    <fullName>Boat__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>סירה</label>
    <referenceTo>Boats__c</referenceTo>
    <relationshipLabel>PriceListLines</relationshipLabel>
    <relationshipName>PriceListLines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app-modified/main/default/objects/PriceListLine__c/fields/Global__c.field-meta.xml
<CustomField>
    <fullName>Global__c</fullName>
    <defaultValue>false</defaultValue>
    <label>גלובלי</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PriceListLine__c/fields/HPrice__c.field-meta.xml
<CustomField>
    <fullName>HPrice__c</fullName>
    <label>תעריף חג</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PriceListLine__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>תעריף</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PriceListLine__c/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <defaultValue>TIMEVALUE(&apos;00:00:00.000&apos;)</defaultValue>
    <label>שעת התחלה</label>
    <required>true</required>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/PriceListLine__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>סוג</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Abroad</fullName>
                <isActive>false</isActive>
                <label>Abroad</label>
            </value>
            <value>
                <fullName>Course</fullName>
                <isActive>false</isActive>
                <label>Course</label>
            </value>
            <value>
                <fullName>General</fullName>
                <isActive>false</isActive>
                <label>General</label>
            </value>
            <value>
                <fullName>Introduction</fullName>
                <isActive>false</isActive>
                <label>Introduction</label>
            </value>
            <value>
                <fullName>Maintenance</fullName>
                <isActive>false</isActive>
                <label>Maintenance</label>
            </value>
            <value>
                <fullName>Renting</fullName>
                <isActive>false</isActive>
                <label>Renting</label>
            </value>
            <value>
                <fullName>Certification</fullName>
                <label>הסמכה</label>
            </value>
            <value>
                <fullName>Friends</fullName>
                <label>חברים</label>
            </value>
            <value>
                <fullName>Enriching</fullName>
                <label>מודרכת</label>
            </value>
            <value>
                <fullName>Club</fullName>
                <default>true</default>
                <label>מועדון</label>
            </value>
            <value>
                <fullName>Renewal</fullName>
                <label>ריענון</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app-modified/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>עסקה</label>
    <nameField>
        <label>שם עסקה</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>עסקאות</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app-modified/main/default/objects/Transaction__c/fields/Used_Points__c.field-meta.xml
<CustomField>
    <fullName>Used_Points__c</fullName>
    <defaultValue>0</defaultValue>
    <label>נקודות שנוצלו</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app-modified/main/default/classes/TransactionPoints.cls
/*
 * @Author: ZedXagE 
 * @Date: 2019-04-23 11:10:23 
 * @Last Modified by: ZedXagE
 * @Last Modified time: 2019-04-28 10:06:11
 */

public  class TransactionPoints implements Queueable{
	public Set <String> tranids;
	public TransactionPoints(Set <String> trnids) {
		tranids = trnids;
	}
	public void execute(QueueableContext context) {
        Map <String, Transaction__c> trans = new Map <String, Transaction__c>();  
		for(String trid:tranids)   trans.put(trid,new Transaction__c(id=trid,Used_Points__c=0));
		List <Co_Cruise_Members__c> ccms = [select id,Cruise_Points__c,Transaction__c from Co_Cruise_Members__c where Transaction__c in:tranids and Transaction__c!=null and Cruise_Points__c!=null and Cruise__c!=null and Cruise__r.Status__c!='Canceled'];
		for(Cruise__c crs:[select id,Cruise_Points__c,Transaction__c from Cruise__c where Transaction__c in:tranids and Transaction__c!=null and Cruise_Points__c!=null and Status__c!='Canceled'])
			trans.get(crs.Transaction__c).Used_Points__c += crs.Cruise_Points__c;
		for(Co_Cruise_Members__c ccm:[select id,Cruise_Points__c,Transaction__c from Co_Cruise_Members__c where Transaction__c in:tranids and Transaction__c!=null and Cruise_Points__c!=null and Cruise__c!=null and Cruise__r.Status__c!='Canceled'])
			trans.get(ccm.Transaction__c).Used_Points__c += ccm.Cruise_Points__c;
		Database.update(trans.values(),false);
	}
	public Static Decimal getPTS(String typval,String btval,Boolean isHoliday,List <PriceListLine__c> plls,Decimal def,DateTime st,DateTime ed){
		Decimal pts=0;
		List <Decimal> ords = new List <Decimal>();
		Map <Decimal,Decimal> ptsbyjump = new Map <Decimal,Decimal>();
		for(PriceListLine__c pll:plls)
			if(pll.Type__c==typval&&pll.Boat__c==btval){
				Decimal jump = getDtm(pll.Start__c);
				ords.add(jump);
				ptsbyjump.put(jump,isHoliday ? (pll.Hprice__c!=null?pll.Hprice__c:pll.Price__c):pll.Price__c);
				if(pll.Global__c == true)	return isHoliday ? (pll.Hprice__c!=null?pll.Hprice__c:pll.Price__c):pll.Price__c;
			}
		if(ptsbyjump.keyset().size()==0){
			for(PriceListLine__c pll:plls)
				if(pll.Type__c==typval&&pll.Boat__c==null){
					Decimal jump = getDtm(pll.Start__c);
					ords.add(jump);
					ptsbyjump.put(jump,isHoliday ? (pll.Hprice__c!=null?pll.Hprice__c:pll.Price__c):pll.Price__c);
					if(pll.Global__c == true)	return isHoliday ? (pll.Hprice__c!=null?pll.Hprice__c:pll.Price__c):pll.Price__c;
				}
		}
		System.debug(ed+' '+st);
		Decimal tottime = ((Decimal)(ed.getTime()-st.getTime())/(1000*60*60));
		Decimal calctime = 0;
		Decimal star = getDtm(st.time());
		Decimal done = getDtm(ed.time());
		Date stDate = Date.newinstance(st.year(),st.month(),st.day());
		Date tempDate = stDate;
		Date edDate = Date.newinstance(ed.year(),ed.month(),ed.day());
		System.debug('Total time: '+tottime);
		while(tempDate<=edDate){
			Decimal st4day = tempDate==stDate?star:0;
			Decimal ed4day = tempDate==edDate?done:24;
			for(integer i=0;i<ords.size();i++){
				Decimal stjp = ords[i];
				Decimal edjp = ords.size()>i+1?ords[i+1]:24;
				Decimal hrs4jp = (ed4day<edjp?ed4day:edjp)-(st4day>stjp?st4day:stjp);
				if(hrs4jp>0){
					System.debug('Hours in jump: '+hrs4jp);
					calctime += hrs4jp;
					pts+=hrs4jp*ptsbyjump.get(stjp);
					System.debug('pts: '+pts+' calctime: '+calctime);
				}
			}
			tempDate = tempDate.addDays(1);
		}
		pts += (tottime-calctime)*def;
		pts = pts.setScale(2);
		System.debug('final pts: '+pts);
        return pts;
    }
	public static Decimal getDtm(Time tm){
		return tm.hour()+((Decimal)tm.minute()/60);
	}
}